### ISSUE TITLE
[meta] Establish DARCI

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#1]
Need to come up with DARCI structure for these:
- Project MGMT
- Administrative & Financial MGMT
- Designing Interventions
- Designing Software for Interventions
- Designing Curriculum for Interventions
- Designing Evaluative Interviews
- Conducting Interviews
- Data Collection Plan
- Community Participation
- Communications

**Comment by secretrobotron** [comment]
#### Project management
- Running the substance and the machine of the project
- Keeping documentation and keeping stakeholders informed
- Figuring out how to do research report-outs on a regular basis
- **Responsible**: @LauraReynal, @secretrobotron

#### Administrative and financial management
- Formal communications, budget, grant management
- Reporting structure CF what Kelly sent through email
- **Responsible**: @metaphorista, Kalpana

#### Designing interventions
- Based on interview responses and patterns, determine the seven experiences we want to test
- Each needs to have a hypothesis
- This will be done on a rolling (agile/iterative) basis but determined in advance
- Each needs to have some correlation / cross-checking potential in the research design
- The research design must back up the hypothesis we want to test of these seven, two need to be on device experiences

##### Engineering lead / software
- Developing and deploying the 2 software prototypes that will be introduced
- Needs engineering and design resources 
- **Responsible**: (_TBD_) @secretrobotron, @adamlofting → @simonwex, @cassiemc?
- Question: Do we need to build something to do data collection?

##### Designing evaluative interviews
- Paired with each of the seven experiences, we need to have an evaluative interview with participants
- **Responsible** : DDD, @adamlofting, @LauraReynal, @secretrobotron

#### Designing data collection plan
- Paired with some of the seven experiences, we need to have an data collection plan for participants to opt into
- People hand over devices, they harvest things like transaction data, usage data, etc. anonymize data and put in the repo
- **Responsible** : DDD, @adamlofting, @secretrobotron

#### Participant interviews
- Collect data in monthly interviews
- **Responsible**: DDD, (@LauraReynal, @secretrobotron when in field)

#### Content creation (curriculum and prototype testing)
- Localizing and testing curriculum as part of the research design
- Making sure that it’s **_contextually appropriate**_ and makes sense / fits in the research design
- **Responsible**: ??? / Simeon ? / Chad

#### Communications - Bobby is the supreme communicator - everyone contributes

##### Strategic / partners
- **Responsible**: @benrito, @secretrobotron

##### Publications (blog or press moment)
- **Responsible**: @secretrobotron, @kevzawacki, all to contribute

#### Working open (ambient / tweeting)
- **Responsible**: @secretrobotron / all

#### Community role

##### Community management: Maintaining day-to-day contact with volunteer
- **Responsible**:

##### Training designing and running prep sessions for trainers as part of the research design
- **Responsible**: 

#### Data analysis

##### Qualitative
- Analysis of DDD Interview data 
- Analysis of device usage data (collected by DDD)
- **Responsible**: DDD + @LauraReynal + @secretrobotron + Mozillians

##### Quantitative
- Analysis of DDD Interview data 
- Analysis of device usage data (collected by DDD)
- **Responsible**: DDD + @adamlofting

**Comment by lauradereynal** [comment]
Closing this. We are up and rolling. :fireworks:
