### ISSUE TITLE
Update our blog / website with the new ghost template 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#101]
@secretrobotron

**Comment by secretrobotron** [comment]
Done! https://mozilla-foundation-research.herokuapp.com

@LauraReynal feel free to pick a different cover photo. :whale2:

**Comment by lauradereynal** [comment]
Thanks. I have really mixed feelings about this template. Let's check with designers and see. It's really too big and makes me want to run away from it really fast. 
I'd be curious to hear from the community as well.

**Comment by secretrobotron** [comment]
@LauraReynal do you want to talk about it? We can leave this open and chat with people!
