### ISSUE TITLE
DSO - Social

### ISSUE THREAD

**Issue by chanditome** [MozillaFoundation/digital-skills-observatory#102]
Think of this as the global DSO "friendly" timeline for you to share about your general daily experience(s) at the DSO project. Think of it as the dining table, where we can all laugh and talk about everything we are doing. You do not have to be right here :-)

**Comment by lauradereynal** [comment]
That's exciting @chanditome ?
Where would you encourage this social behavior to happen ? 

cc @secretrobotron

**Comment by secretrobotron** [comment]
Yeah, cool, @chanditome. Can you describe a little bit more?

**Comment by chanditome** [comment]
Hey guys!
Great news from Kenya Commercial Bank on their announcement of their 2015 FY results. So, apparently, 95% of their loans are now on mobile with over 3.4 million applications in 2015 alone. 

What does this mean for mobile money? 

The bank also announced that they have 98% repayment rate of all mobile borrowers.

**Comment by secretrobotron** [comment]
Cool, @chanditome . Do you have a link? Would love to read more.

**Comment by chanditome** [comment]
@LauraReynal @secretrobotron something like what I have posted above. Not directly a major contribution to the project, but with discussions meant to strengthen our understanding and participation to the project but in a more informal way. 

I cannot tell for sure if this is the platform. Please let me know your thoughts. Thank you.

@secretrobotron about the KCB results. Please check this [link](https://twitter.com/hashtag/KCB2015FYResults) for the hashtag conversation by the Bank's official Twitter account.

**Comment by lauradereynal** [comment]
Hey @chanditome we are happy to let you explore different ways to make the project social and enjoyable for the community. Feel free to use telegram or slack or other channels.

**Comment by chanditome** [comment]
I'll close this one for now. Not unless someone else sees the need to keep it open.
