### ISSUE TITLE
List and analyse existing DFS 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#104]
_Goal_: we need to keep a list of DFS (not necessarily apps) that are existing and upcoming. 
This will help us to understand the landscape and the different products possible. If possible, we should try and use them to get familiar with them as much as possible. 

Lead: @denomain 
Team: everyone? 
cc @secretrobotron

**Comment by AI-DennisNdegwa** [comment]
MPESA
AIRTEL MONEY (MPESA version of Airtel)
ORANGE MONEY (MPESA version of orange)
KCB bank mobile app
Bank Of Africa mobile app

**Comment by chanditome** [comment]
Mshwari  - Commercial Bank of Africa savings and lending service for MPESA users
Kopa Cash - KopaCash is a lending service for Airtel Money users
Branch - (www.branch.co) lends money to users through their Android. They pull MPESA texts data from users' phones to make decision on borrower credibility.

**Comment by lauradereynal** [comment]
Thanks @denomain and @chanditome for your contribution. 
:smile: 
@denomain would you like to lead this task and start documenting the different existing DFS ?

**Comment by AI-DennisNdegwa** [comment]
@LauraReynal Definitely do. Will get a document set up on it and ask people to add all the ones they can think of. 
@chanditome we can start with all the ones we can think of and ask anyone who can think of anything that we've left out to add what they can.

**Comment by AI-DennisNdegwa** [comment]
I have created a doc with atable for adding the different DFS. Will keep adding more as I go https://docs.google.com/document/d/1tjNPZ8mxfZJwrFvp4oX5ntlPR4F-4veQflUsYwyPM4w/edit

HELP??? @Amuti @xelawafs @zuma1 @zuma1 @festolangat @FauziaIsmail @Obadha @Shey02 @uwanja @WinnieMakokha @Ednahkiome @josiahmuyesu @Arwa40 @ChristabelAchieng @dobbz
@nekesawekesa @nmarita @marywashe @alexanderamolo @nao07

**Comment by lauradereynal** [comment]
Awesome, thanks @denomain

**Comment by lauradereynal** [comment]
This table will be super helpful to get an overview of the DFS landscape

**Comment by chanditome** [comment]
@denomain great! Let's do this.

**Comment by WinnieMakokha** [comment]
Aye, @denomain the document is not open for editing. its view only :-) Mind changing that?

**Comment by WinnieMakokha** [comment]
As you work on that @denomain  cc @LauraReynal @chanditome  MPESA is a platform for many other DFS, if i understand DFS correctly in this context. For example CFC pocket/ KCB bankika(platforms that my banks have for me to conduct financial transactions while some of the transactions are intergrated into the MPESA) is that included too? even though i have a feeling this will be toooo many. maybe we consider broadening the definition of MPESA on the table. Yes/No/Maybe?

are crypto currencies(spell check alert) included in this? Like BitPesa? again MPESA appears somewhere here?

**Comment by WinnieMakokha** [comment]
the world bank normally has a regional  yearly competition where it invites youths between the ages of 18-25 to participate on a the chosen topic by writing blog posts.
The 2015 competition was on how to boost opportunities for youths in Kenya Uganda and Rwanda. I was one of the participants, however i didn't make it to the finals.

They have recently given the participants  feedback on the competition and one of the winning blog entries is from a 19 year old Kenyan lady, and it touches a bit on the power of DFS in boosting opportunities for the youth.
insightful read for the project. 
here [https://blogs.worldbank.org/nasikiliza/technology-sound-record-keeping-and-access-to-finance-could-be-the-keys-to-youth-unemployment-in](url) 

cc @denomain @LauraReynal @secretrobotron

**Comment by lauradereynal** [comment]
@WinnieMakokha sounds awesome, but the link is broken :-)

@WinnieMakokha you are right about the different platforms including Mpesa. They are also DFS. 
Mpesa or Mobile Money is only one of them. Think of anything that is finance related and that you can do online. From bank apps to insurance to sending money on snapchat (yes it exists) ...

Makes sense?

**Comment by lauradereynal** [comment]
@denomain thanks for making a document - can you allow us to edit?

**Comment by WinnieMakokha** [comment]
https://blogs.worldbank.org/nasikiliza/technology-sound-record-keeping-and-access-to-finance-could-be-the-keys-to-youth-unemployment-in

hope this one opens @LauraReynal

**Comment by JoashMango** [comment]
very interesting and inspiring blog. Love this part,'The application should also be able to create financial projections for the SMEs. When one downloads the App they should be able to enter their business particulars, including; goods they are trading in, sales targets, actual sales, costs, unit prices, sale date, among others. The app with these details should create financial projections as well as perform economic analysis'. can the app developer do this @LauraReynal ?

**Comment by WinnieMakokha** [comment]
[mobile banking adoption in Kenya_thesis paper.pdf](https://github.com/MozillaFoundation/digital-skills-observatory/files/185518/mobile.banking.adoption.in.Kenya_thesis.paper.pdf)

i have annotated a few parts of interest to the project in terms of background info/literature review.good read especially those whose interest is open researcher cc @denomain @chanditome @zuma1 @LauraReynal @nekesawekesa @Amuti etc... 

this is a research proposal by an MBA student from University of Nairobi, accessed from the University public(internet library)

link http://chss.uonbi.ac.ke/sites/default/files/chss/ESTHER%20A.%20OUKO%20ODERA%20D61-71319-2008_0.pdf

**Comment by lauradereynal** [comment]
Hey @WinnieMakokha I loved the idea of a financial profile that people could use when they are looking for getting new credits. Thanks for sharing this article :smile: :cat: :books: 

Do you have more interesting readings to share ? this one was cool

**Comment by WinnieMakokha** [comment]
@LauraReynal  i am still rummaging through the world wide web for other readings, when i come across them I will most definitely share.

**Comment by lauradereynal** [comment]
From @chanditome 
https://branch.co/
Zidisha.org

**Comment by AI-DennisNdegwa** [comment]
So so sorry everyone. I haven't been on Git for a while. I'm back now.....full force!! The document should be editable now.

@Amuti @xelawafs @zuma1 @zuma1 @festolangat @FauziaIsmail @Obadha @Shey02 @uwanja @WinnieMakokha @Ednahkiome @josiahmuyesu @Arwa40 @ChristabelAchieng @dobbz
@nekesawekesa @nmarita @marywashe @alexanderamolo @nao07

**Comment by secretrobotron** [comment]
@denomain not a lot of input on the document. Maybe we can fill this out in July and publish?

**Comment by AI-DennisNdegwa** [comment]
@secretrobotron agreed. Totally forgot about this. Will talk to @chanditome to see if we will have put down something substantial by then.

**Comment by secretrobotron** [comment]
@LauraReynal can put this on a blog or make part of mid-study report. Let's revisit.
