### ISSUE TITLE
Work on questions for interview 2 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#105]
Goal; create script for interview 2

Collaborate with the community. cc @secretrobotron

**Comment by JoashMango** [comment]
Let discus this in today call

**Comment by lauradereynal** [comment]
Yes awesome.

**Comment by lauradereynal** [comment]
Meeting planned for Monday. 

@JoashMango @DuncanGW is there an existing document we should focus on ?

**Comment by DuncanGW** [comment]
Yes we have google doc we worked on for the brainstorming questionnaire.

**Comment by JoashMango** [comment]
i agree with Duncan, we can improve on the document we have

**Comment by lauradereynal** [comment]
Let's share with the community for feedback and awareness

**Comment by lauradereynal** [comment]
https://docs.google.com/a/digitaldividedata.com/document/d/1LXQ9flN4r8DFU3AM6ZZs0wXFcKSq7tJ0-clMynEcKvQ/edit?usp=sharing for those who want to comment on the doc

**Comment by lauradereynal** [comment]
Interview 2 is done
