### ISSUE TITLE
Make plan and assign roles specific for Mozilla Kenya community members

### ISSUE THREAD

**Issue by Amuti** [MozillaFoundation/digital-skills-observatory#106]
Hey guys

I've noticed that most community members are getting lost in the midst of the project and finding github a bit overwhelming to use
Could we skim out where the community members could contribute as per where we are on the project  and also heading forward?
We could create teams and assign roles? To know where specifically one can adequately contribute

@chanditome @Uwanja @shey02 could you help out on this?

**Comment by shey02** [comment]
Thats true and yes i would be happy to help in anyway.

**Comment by Obadha** [comment]
Hello @Amuti, allow me. I'll give it a shot. 

**Where we are**
Participants have been identified for each location.Initial interviews have been conducted,feedback and data collected.

**Work in Progress**
Curriculum/Lesson Plan/Intervention development. This is being done by @chadsansing . 
In an email Chad sent out earlier, he was trying to gather material from us that would help him understand the Kenyan Culture better as he set out on this venture. So here is a first where _anyone_ can jump in and help. Help can be in the form of sharing material or content or links or books or acts that shed any light or explain or depict the Kenyan Culture. This is to help with developing of the curriculum.

From the communications set out, this should be done by 30th March, in readiness for the interventions in April.

**To Do List**
Plan for Interventions - In the last community call (3rd) teams were formed and each team assigned tasks and roles. Find the list [here](https://docs.google.com/document/d/1xI437hHk8TPrxNfATXll5ypSf83MCyBTbj97oMI4x6k/edit#) . Depending on the team you select to be in (Software, Analysis, Events, Curriculum ), roles will vary. Pick where you feel you will be most useful, edit the document including your name, or contact Bobby and Laura and see what the way forward is for each team.

**Immediate Up Next**
Events Team is up next. They are currently holding talks to hold interventions on their respective locations. After the first interventions are held, then I guess the way forward from then will be determined then.

To Wrap it up:
1. Way Forward- Interventions up next.
2. Teams and Roles, simply where one is most interested in. Make your pick, and dive in. I think you can pick more than one team and one is not restricted to just one.

cc @chanditome @shey02 @WinnieMakokha @secretrobotron @LauraReynal @FauziaIsmail @zuma1  could you confirm or deny the above? uh, did I get it right? What have I left out?

**Disclaimer:** This is not exhaustive. I have left out some parts we can and should contribute to including not limited to contributing to blogs, material that might be relevant to curriculum and content creation etc.

**Comment by secretrobotron** [comment]
Thanks for the summary, @Obadha! I'll publish the teams somewhere on here as a followup.

**Comment by secretrobotron** [comment]
One thing I noticed:

> Teams and Roles, simply where one is most interested in. Make your pick, and dive in. I think you can pick more than one team and one is not restricted to just one.

That's totally true, but @LauraReynal and I did a quick scan of the roles everyone already chose and tried to form the teams from that. Do let me know if you're on a team that you don't feel like you can contribute to, and we'll work something out.

**Comment by Uwanja** [comment]
I would like to believe that the intervention is of the highest priority now. I am also somehow lost in the communications. At times there is a new Google doc, a new issue here etc. I can't seem to find the teams either. Was I added to one based on my interests at the DSO bootcamp? Or is their a new basis of forming teams?

**Comment by chanditome** [comment]
Thanks @Obadha for the breakdown. I personally needed this. @Amuti I agree that it has been a challenge for many to follow the updates. Good thing we are not working in teams and this should hypothetically make communication and participation easy and effective. 

In the next few I will be following up with my core team on our next activity.

**Comment by secretrobotron** [comment]
@Uwanja 

> Was I added to one based on my interests at the DSO bootcamp?

Yes! We also talked about building teams on the community call last week. Happy with the results?

**Comment by Amuti** [comment]
Hey @Obadha thank you so much for this!

 @Obadha @chanditome could we now come up with a google doc with the teams outlayed and pin it to this issue so that people now where to go from here? @Uwanja this would help right?

@secretrobotron do you mind drafting activities for the intervention that people could also contribute to? People are also lost in this

**Comment by secretrobotron** [comment]
@Amuti yeah, certainly! I think when the curriculum and events teams meet, we can discuss what that looks like. @chadsansing has already done a bunch of work drafting some activities, and several of the people in the DSO community have some experience doing Webmaker/FSA/etc. activities. Let's talk about it when we meet :grinning:

**Comment by chanditome** [comment]
@Amuti yes. @secretrobotron sent an email on March 7th detailing information on proposed workgroups. Could be copied on a doc, that's fine. But it looks something like this;

**In the meantime, these lovely people have volunteered to lead our working groups:

```
Curriculum: TBD (if you want the job, let me know!)

Software: Alex

Analysis: Faith

Events: Walter

Community: Chandi
```

Please do treat these people with utmost kindness, for they are brave :). Each team has a pretty clear set of objectives, which team leaders will be consulting you to dig into this week. We tried our best to put everyone on a team that makes sense. If you think you’re in the wrong place, or really want to contribute to another group as well, give Laura and I a shout so we can talk about it. Here are the teams:

```
Curriculum: Simeon, Alexander, Ash, Faith, Marita, Chandi, Walter, Ednah, Jack, Laura, Bobby, [Chad]

Software: Ash, Marie, Dobbz, Victor, Walter, Bobby

Analysis: Nekesa, Walter, Winnie, Christabel, Dennis, Chandi, Steve, Joash, Duncan, Laura

Events: [At least one person from each location], Steven, Shehnaz, Fauzia, Bobby, Laura

Community: Naomi, Nekesa, Josiah, Festus, Shehnaz, Fauzia, Bobby, Laura**
```

Please let me know if this helpful.

**Comment by secretrobotron** [comment]
:+1: thanks @chanditome !

**Comment by lauradereynal** [comment]
Thanks everyone. 
We know there are lots of github tickets and emails and doc. It's true that this project is big, so don't hesitate to reach out again with questions like these. 

Also, our calls are a good place to raise up these issues and get real time discussions and explanation. 

I'm going to close this ticket since we now have teams, but feel free to reach out again if you have more questions.

**Comment by marywashe** [comment]
How did the selection of guys in teams happen, cos I can't see me in any..@secretrobotron

**Comment by lauradereynal** [comment]
Hey @marywashe thanks for flagging. 
We have assigned people to teams based on what they said they wanted to do during the bootcamp. 
Do you have a preference? Since you are a researcher, we would love your help on organizing the interventions. Do you want to be in the analysis team ?

**Comment by marywashe** [comment]
@laura, I get it now, that day I was in research team only, which is not highlighted here. I would be glad and comfortable to be part of community and/or analysis teams.

**Comment by lauradereynal** [comment]
Awesome @marywashe 
@chanditome is leading the community team and can welcome you

**Comment by lauradereynal** [comment]
Since we have run our first intervention, it seems that people have a better idea about the roles they play in the project and the way that they can contribute. 

If anything is unclear, please reach out to us 🐼 😄 !
