### ISSUE TITLE
Biweekly skype call

### ISSUE THREAD

**Issue by marywashe** [MozillaFoundation/digital-skills-observatory#107]
Hi everyone,  Im sorry that I  had not been participating in the 3 previous skype calls, @secretrobotron, kindly add me up in the coming calls, my username is "marychizi". 
Thanks.

**Comment by marywashe** [comment]
Also, try to figure out guys who are not participating and see what their problem is, the more ideas we get from everyone in the team, the better we grow.

**Comment by secretrobotron** [comment]
Of course, @marywashe! Accept my Skype request :).

**Comment by secretrobotron** [comment]
@marywashe do you want to do some outreach to the group to see how we can improve attendance? I was thinking about sending out a remind a day in advance, and an hour in advance. Wanna help?

**Comment by marywashe** [comment]
@secretrobotron  right, that would help,  plus make it that everyone should participate unless in 'very' held up.

**Comment by lauradereynal** [comment]
Hey @marywashe we missed you today. 

Are you on the DSO mailing list? we sent a link to a google hangout. It works way better than skype so we are using this channel now. 
Hope to see you in the call in 2 weeks from now
