### ISSUE TITLE
Work on the data collection plan

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#11]
Task: Based on the research questions and the overall project, figure out what data needs to be collected and how we can do so. 

Driver: @adamlofting with DDD 
Informed : @secretrobotron and I

**Comment by lauradereynal** [comment]
Follow up from today's call: Need to reduce the currrent list to a smaller number of things to track.

## From the proposal

Research participants will install a mobile application, allowing researchers and metrics experts to analyze a detailed phone usage history. We will collect data including: browsing history, social communications, use of digital financial services, and business related interactions. We will not release detailed phone usage data openly to protect the privacy of research participants; we will however, likely include aggregated and completely anonymized datasets in public research releases. 

We will request respondents to install an App to give phone usage history regarding:
·     number of contacts
·    number of social communications in the past week (calls, messages, WhatsApp messages, Facebook messages etc.)
·      use of search and search terms
·      photos taken – number and characterization e.g. selfies
·      YouTube history (noting how-to vs. entertainment)
·      browser history
·      games
·      music
·      GPS and maps
·      formal educational usages, including apps, student-teacher interactions
·      mobile money
·      mobile banking (savings, loan etc.)
·     use of phone for other financial purposes (personal accounts, investments, insurance, savings group ledgers etc.)
·      use of phone for business purposes (business accounts, mobile marketing)
·      use of phone for work purposes (assignments by employer)
·      payment for any online activity (app download, ad purchase, online shopping, anything else)
·      e-government (e.g. for taxes, driver license renewal etc.)
·      number and types of apps downloaded and used
·      usage for practical/physical applications such as clock, alarm, flashlight, doorkey etc.
·      maker activities

**Comment by adamlofting** [comment]
- @JoashMango @DuncanGW 

Here's a first draft of the data collection plan that I've worked on today. This is only a draft, so please feel free to comment and edit as much as you like. 

https://docs.google.com/document/d/1Xb6mSjDqlFMVWKsMO1Sc3YbYY_vsKaXPRUiHMQFsMBE/edit#

**Comment by adamlofting** [comment]
I'm back at work today. Do you need any further input from me at this stage? Or is this document enough for you to make next decisions?

In particular:
1. Do you agree we should track all of the 'relative easy to track' data in the plan?
2. Do you want to include the suggestion for documenting a user narrative based on browsing history? It could add a lot of content to the interviews, but would also add time to the interviews.

cc @benrito @secretrobotron @JoashMango @DuncanGW

**Comment by lauradereynal** [comment]
I believe this can be closed. 
@adamlofting and @dobbz reopen if Im wrong :smile:
