### ISSUE TITLE
Follow up questions 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#110]
Each time we learn something new, we have follow up questions that we aren't yet ready to organize. 
Here is a document to store them all 
https://docs.google.com/document/d/1cq8EbpzJwItygbC0AI17e1B1tyDkVinJEx9vDo5RUS4/edit#

Feel free to contribute 
@JoashMango @DuncanGW @secretrobotron

**Comment by lauradereynal** [comment]
Leave this ticket open so that we can tag people and continue building on it 
cc 
@chanditome @WinnieMakokha @xelawafs @denomain @Amuti feel free to add follow up questions too

**Comment by secretrobotron** [comment]
@LauraReynal do you want to follow up on this every month or so? Or is this documented somewhere else now?

**Comment by lauradereynal** [comment]
Let's keep this document open for now. It's been a good place to dump some thoughts so far.
