### ISSUE TITLE
Produce an online verison of curriculum for intervention 1 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#111]
Goal: Put the curriculum for intervention one online somehwere

@secretrobotron what do you think?

**Comment by lauradereynal** [comment]
Is there a template I could use to do that ? I'm happy to give it a try

**Comment by chanditome** [comment]
@LauraReynal Can we use the curriculum stying on [teach.mozilla.org](teach.mozilla.org) as a template?

**Comment by lauradereynal** [comment]
@chanditome I love this idea 👍 
@chadsansing what do you think for our first curriculum ? 
Can we upload it on the teach database with a DSO tag or something similar ?

**Comment by chadsansing** [comment]
I think this sounds promising. I would suggest we work on developing, testing, and delivering the interventions now and then migrate them into the curriculum template for sharing online later. We would also want to loop in @ldecoursy and @hannahkane on anything that might show up on https://learning.mozilla.org/activities.

**Comment by hannahkane** [comment]
I'm hoping we can use the same templates for each of our curricula (web literacy, leadership, DSO, etc.), but perhaps visually distinguish them from one another (e.g. with colors). Regarding where they should live, we are still planning on building a central repository for curriculum in H2, but if it's ready sooner, we can certainly add to the Learning site in the meantime.

**Comment by lauradereynal** [comment]
Decision: 

**Short term:** @chadsansing will put intervention 1 in the template for a first review and making it easy to share right now.
**Long term:** will see with Lainie when we have enough activities for making a module that can go on the learning website

**Comment by secretrobotron** [comment]
@chadsansing is well on his way to having this done. Needs to be checked over.

**Comment by secretrobotron** [comment]
Supplanted by https://github.com/MozillaFoundation/digital-skills-observatory/issues/247.
