### ISSUE TITLE
Create Swag for the community 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#114]
Goal: Create a DSO-only-unique-super cool swag. 

@secretrobotron we should offer someone to take the lead here. 

Ideally we would be able to produce it in Kenya?

**Comment by lauradereynal** [comment]
- [ ] Design a cool Tshirt
- [ ] Make some stickers

**Comment by secretrobotron** [comment]
@LauraReynal would love to follow up on this for July.

**Comment by lauradereynal** [comment]
Me too. Can we ask @flukeout to help us create a cool DSO image / logo for a t-shirt and a sticker? 
What do you think ?

Maybe we could have a simple copy that says: 

Digital Skills Observatory 
Open Researcher 
Kenya 

is that lame ? That's a little lame.

**Comment by lauradereynal** [comment]
@chanditome @zuma1 @xelawafs @icarius06 @denomain 
Do you have any idea about the kind of swag that would be cool ?

**Comment by lauradereynal** [comment]
We are good for now.
