### ISSUE TITLE
Publish DSO teams in a single ticket 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#122]
Goal: can we publish the DSO community teams somewhere? 
@secretrobotron

**Comment by secretrobotron** [comment]
I believe it's this:

Curriculum: **Laura**, Simeon, Alexander, Ash, Faith, Marita, Chandi, Walter, Ednah, Jack, Bobby, Chad

Software: **Alex**, Ash, Marie, Dobbz, Victor, Walter, Bobby

Analysis: **Faith**, Nekesa, Walter, Winnie, Christabel, Dennis, Chandi, Steve, Joash, Duncan, Laura

Events: **Walter**, [At least one person from each location], Steven, Shehnaz, Fauzia, Bobby, Laura

Community: **Chandi**, Naomi, Nekesa, Josiah, Festus, Shehnaz, Fauzia, Bobby, Laura

**Comment by secretrobotron** [comment]
@LauraReynal where do you want to publish?

**Comment by lauradereynal** [comment]
🌴 This is done / no longer relevant.
