### ISSUE TITLE
April trip logistics 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#123]
- [x] get visa letters from Mozilla
- [x] book accomodation for Nairobi
- [x] book accomodation for Kisumu
- [x] book accomodation for Mombasa 
- [x] book intra country plane tickets 
- [ ] Schedule the days with each team 
- [ ] bring some swag ? 

@secretrobotron let's start taking notes here, im forgetting tones of things

**Comment by chanditome** [comment]
Hey @LauraReynal @secretrobotron,
1. Can you please also carry me tons of Mozilla stickers for Mozilla Kisumu? Please? :-)
2. When are the dates for Kisumu?

**Comment by lauradereynal** [comment]
We will see what we can find Chandi. Im not sure of how many stickers are here :D but we will do our best

**Comment by lauradereynal** [comment]
Done !
