### ISSUE TITLE
Monthly reporting - March 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#124]
Goal: create and send monthly reporting document to Gates 

@secretrobotron @KalpanaSimhan and I

**Comment by lauradereynal** [comment]
@KalpanaSimhan feel free to jump in. I did a first pass today. We should be good to send really soon. 
@JoashMango @DuncanGW Please jump in the Monthly reporting document, and add/ correct / edit as much as you want.

**Comment by lauradereynal** [comment]
@KalpanaSimhan what do you think ? 

It's good to go for me. The april one will be a bit bigger.

**Comment by JoashMango** [comment]
It looks okay for me

**Comment by lauradereynal** [comment]
Thanks to everyone who helped review / copy.
