### ISSUE TITLE
Add 3 new members to our mailing list

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#125]
@secretrobotron can you please add 
Michael Odhiambo
Bonface Odhiambo
Sharon Gisore

From Kisumu, in our mailing list? 

Thanks !

**Comment by secretrobotron** [comment]
Done!

**Comment by chanditome** [comment]
@secretrobotron @LauraReynal My personal thanks!

**Comment by shey02** [comment]
Hello Laura,is it possible to add one more member from Mombasa into the mailing list?

**Comment by lauradereynal** [comment]
Hey @shey02 of course. 
Please send us an introduction email :smile: ?

**Comment by shey02** [comment]
Here you go Laura,
mukhtarsalim80@gmail.com

Thanks :)

**Comment by shey02** [comment]
Mukhtar is a mozillian.He has been volunteering and participating in various mozilla related events.He is also taking part in planning for the intervention and has volunteered to help out on the particular day itself.

**Comment by secretrobotron** [comment]
Hey @shey02. Mukhtar is already on the mailing list. Let us know (or tell him to let us know!) if he's not getting any correspondence.

Can't wait to meet him, and see you again :).

**Comment by shey02** [comment]
Okay i will let him know.

Can't wait to see u,laura and everyone else too :)
