### ISSUE TITLE
Store finale version of each interview in a google drive folder 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#126]
@DuncanGW and @JoashMango can store the final version of each interview in a drive folder 

@secretrobotron and @LauraReynal to figure out how to publish them nicely

**Comment by secretrobotron** [comment]
Since @DuncanGW has so carefully designed them, I think publishing the excel document might be appropriate. It's the most flexible and explicit format before it goes into ODK.

We _can_ pull it out into a PDF, but it will have less information—just for readability.

**Comment by secretrobotron** [comment]
The files should definitely go into
- A blog post
- The DSO website

**Comment by JoashMango** [comment]
The excel format is the version we use in the ODK

**Comment by secretrobotron** [comment]
@DuncanGW, can you let us know when (and where) you've got these in PDF/Excel format? It's probably good to have both lying around (PDF so that we can publish on a blog).

**Comment by lauradereynal** [comment]
@DuncanGW any update on this ? Please let us know when you have a link

**Comment by secretrobotron** [comment]
@DuncanGW can you share a link to this folder with @LauraReynal and me?

**Comment by secretrobotron** [comment]
We've got this setup now, and stuff is added to the folder on an ongoing basis.
