### ISSUE TITLE
Create a Global #Hashtag to Track Conversations Everywhere

### ISSUE THREAD

**Issue by chanditome** [MozillaFoundation/digital-skills-observatory#127]
We need one global hashtag. It will be useful for anyone within the project and the public to track conversations whether on Facebook, Twitter, Instagram etc. 

Some suggestions: #DSO2016 #DSOKenya2016 #DSOKenya - problem with acronyms like these ones they do not immediately give an immediate summary of the hashtag. 

But we do need one for the purposes of tracking the project's entire web footprint. Thoughts?

**Comment by lauradereynal** [comment]
that's a great idea ! 

I've been using DSO as a # when I tweet. 
DSO Kenya might be better :D good thinking

**Comment by lauradereynal** [comment]
we have been using #DSO . It's not perfect but it does the job :smile:
