### ISSUE TITLE
Review initial timeline and share with team

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#13]
Task: Review inital project timeline. Iterate with DDD. Share with Dave 

Driver: yours truly + @secretrobotron 
Consulted / informed: @metaphorista @adamlofting @benrito @JoashMango

**Comment by lauradereynal** [comment]
Hey team, 
Can you jump in this timeline and provide comments if needed  ?

@JoashMango what do you think ? https://docs.google.com/spreadsheets/d/18GXkDPQedFEeTVBxajkzRBoAyUYST3pfIW-z-fQiX74/edit#gid=989915141&vpid=A1

**Comment by JoashMango** [comment]
The timeline is okay with me but its cast in stone we can amend it if need be

**Comment by lauradereynal** [comment]
this timeline has been updated. 
Tab 1 - has an overview of the project timeline 
Tab 2 -  is where we will keep a detail planning for January 
Feel free to edit / add comments. I'm closing this ticket for now
