### ISSUE TITLE
Things to cover in Nairobi and Kenya for our April trip 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#133]
Goal: Go through a maximum of that to-do list when in Nairobi
@JoashMango @DuncanGW @secretrobotron please add / remove items.
- [x] Interventions logistics and check 
- [x] meet with Dave 
- [x] Hackathon prep 
- [x] dinners with community members in each region 
- [x] Debrief of what we learned running 5 interventions (project management debrief)
- [x] General check on the timeline 
- [ ] What do we put in a half project report ?
- [ ] Learn how to use the dashboard 

Preparing for the next phase: 
- [ ] Overview of how we run intervention 2 in June
- [ ] Overview of the software calendar 
- [ ] Preparing the next couple interviews 
- [ ] Participating in the analysis calls with the researchers

**Comment by LauraReynal** [comment]
Let's take notes in our DDD minute call if possible
