### ISSUE TITLE
Create a wrapper for the hackathon

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#134]
Goal: Create/find a wrapper for web site inside a native Android app that can be used as a starting point for the hackathon. It should reduce friction if hackathon memeber want to build an HTML/CSS/JS project distributed as an app,

Lead: @secretrobotron @alanmoo 
Consulted / informed: @flukeout @xelawafs

**Comment by lauradereynal** [comment]
Please add a relevant description in this ticket. I don't really know what you will aim to build.

**Comment by alanmoo** [comment]
@k88hudson Do you have any suggestions for an existing project we could use for this? Or maybe @ryanwse does?

**Comment by ryanwarsaw** [comment]
@alanmoo I'm not sure I totally understand what you guys are trying to do. If you're trying to make a web app into an actual Android application, then you'd probably have to use something like Crosswalk or Cordova, or perhaps even something like Intel XDK.

**Comment by alanmoo** [comment]
@ryanwse that's the gist of it, though I'm considering what our goal really is...those might just add bloat and I'm not sure that's a good thing for this use case.

@secretrobotron what concerns/constraints should we have at this point in time? Bandwidth, compatibility, ...? This will be an option for a jumping off point in the hackathon, but if that's the case it'll probably be used to continue into the real app, right? So we should make sure it would be ready for that.
