### ISSUE TITLE
Intervention 1 Reporting Production List

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#137]
Acquire the following assets for documentation, reporting, mozcast of Intervention 1.
## Audio
- [ ] Stories of participants in introductions (Activity 1)
- [ ] Duncan describing how smartphones work (Activity 2)
- [ ] Dennis and Alex explaining Air Time vs. Data (Activity 2)
- [ ] Alex describing the Internet (Activity 3)
## Video
- [ ] Participants performing (Activity 4)
- [ ] Participants drawing and interviewing one another (Activity 5)
## Images
- [ ] Dennis doing Ice Breaker
- [ ] Participants shaking hands and introducing themselves in Ice Breaker
- [ ] Naomi and Hilda facilitating introductions (Activity 1)
- [ ] Duncan describing how smartphones work (Activity 2)
- [ ] Dennis and Alex explaining Air Time vs. Data (Activity 2)
- [ ] Alex describing the Internet (Activity 3)
- [ ] Participants performing (Activity 4)
- [ ] Participants drawing and interviewing one another (Activity 5)
- [x] Participants helping one another install apps (Activity 6)
- [x] Facilitators helping participants with their phones (Activity 6)

**Comment by lauradereynal** [comment]
lets do activities outside for the next round.

**Comment by secretrobotron** [comment]
Got these:
- Nairobi intervention participants activities
- Nairobi debrief
- Kisumu intervention participants activities
- Ksiumu debrief

**Comment by lauradereynal** [comment]
Interventions are done. We got a lot of data. Will triage and upload
