### ISSUE TITLE
Blog - Write blog post about intervention 1 for each location 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#138]
@secretrobotron let's make sure there is a blog post for each intervention, written in collaboration with the community.
- [x] Nairobi 
- [x] Kisumu and Vihiga 
- [ ] Mombasa and Kilifi

**Comment by lauradereynal** [comment]
Blog post number one is online for Nairobi
https://mozilla-foundation-research.herokuapp.com/dso-nairobis-first-intervention/

**Comment by lauradereynal** [comment]
Blog post number 2 is in progress for Kisumu and Vihiga - if you would like to join and add some bullet points: https://docs.google.com/document/d/1FUE8sULZPbRvZT60ETkNglt19P2IwZjhCHA5DJGmFB4/edit @JoashMango @DuncanGW

**Comment by secretrobotron** [comment]
One more: Mombasa!

**Comment by secretrobotron** [comment]
@nmarita jump in and check it over! https://docs.google.com/document/d/1YZ0Rnlcu_F9RrI8eN4fCkjIx4iCrCYx_fGBwfjMO4Gk/edit

We'd love to publish soon :).

**Comment by secretrobotron** [comment]
@LauraReynal we never published the mombasa/kilifi post. Should we put it up now just to put the synthesis online?
