### ISSUE TITLE
Software - feedback on prototypes 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#148]
Team: @flukeout @secretrobotron @alanmoo @icarius06

Here are a few mockups from Luke. Let's build on this
https://www.dropbox.com/sh/tyvzz33q9bnlvwo/AAC01YT3mSQNcSuJDFkXrCgMa/mocks?dl=0&preview=chat-bot.png

![account-info](https://cloud.githubusercontent.com/assets/8261945/14823396/186e65e0-0bdb-11e6-923e-7b750cd143db.png)
![chat-bot](https://cloud.githubusercontent.com/assets/8261945/14823395/18619612-0bdb-11e6-9114-0728799069fa.png)
![quiz](https://cloud.githubusercontent.com/assets/8261945/14823394/186099c4-0bdb-11e6-93ad-32f59293952c.png)

**Comment by lauradereynal** [comment]
Ideas: 
- Keep in mind that vocabulary is difficult and people don't know words like "settings" 
- Editing screenshots to ask a question (like snapchat)

**Comment by flukeout** [comment]
**Updates**
- I updated the Chatbot app to include an image of the settings gear
- Added a new two-screen mockup of the annotate & ask app

Folder - https://www.dropbox.com/sh/tf27fgg0vugjxx9/AAAOpryKpUF9ixez1QmrSK9da?dl=0

cc @LauraReynal @secretrobotron

**Comment by lauradereynal** [comment]
thanks @flukeout we are printing them and using them for the hackathon tomorrow

**Comment by flukeout** [comment]
Cool, I added one more, it's also in the folder... let me know if it makes sense and if the prices are formatted correctly!

![data-usage](https://cloud.githubusercontent.com/assets/25212/14868203/4ddb6dee-0c81-11e6-89e9-24c52aaca980.png)

cc @secretrobotron @LauraReynal

**Comment by secretrobotron** [comment]
Thanks a billion for these! They should be creatively inspiring :).

I put them all in the hackathon >> mocks folder for posterity.

**Comment by JoashMango** [comment]
very informative i like them

On Thu, Apr 28, 2016 at 8:46 AM, Bobby Richter notifications@github.com
wrote:

> Thanks a billion for these! They should be creatively inspiring :).
> 
> I put them all in the hackathon >> mocks folder for posterity.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/148#issuecomment-215315866

## 

Mr. Joash Mango
Research Director
Digital Divide Data
Paramount Plaza, 7th floor
Nairobi, Kenya
joash.mango@digitaldividedata.com
Tel: +254 772 191 795
Cell: +254727280364

  http://www.digitaldividedata.com/*Creating a World of Digital
Possibilities http://www.digitaldividedata.com/   *

http://www.digitaldividedata.com/

**Comment by AI-DennisNdegwa** [comment]
Very useful app. I can see why many people (including myself) would find it useful.

**Comment by secretrobotron** [comment]
Thanks for this, everyone :). Moving focus to https://github.com/MozillaFoundation/digital-skills-observatory/issues/149.
