### ISSUE TITLE
Choose first software idea to pursue

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#149]
Based on hackathon results, we should choose an avenue for developing the first software prototype.

_More details to come today. This ticket is a placeholder so that I don't forget what I'm doing._

/cc @flukeout @LauraReynal @denomain @xelawafs @Obadha @chanditome @brianmwadime @alanmoo @icarius06

**Comment by secretrobotron** [comment]
cc @thebonface

**Comment by flukeout** [comment]
Was experimenting a bit with putting together a quiz & trivia app. Right now I just have text based questions, but I'll expand it to also include images (like icons)

![trivia](https://cloud.githubusercontent.com/assets/25212/15060628/6815548e-12e1-11e6-9d44-d431fb3ed423.gif)

I'll review the rest of the ideas from the write-up tomorrow and pitch in my thoughts!

**Comment by secretrobotron** [comment]
Excellent!

Here's the final hackathon writeup: https://mozilla-foundation-research.herokuapp.com/results-from-tamasha-hack/

**Comment by festolangat** [comment]
The article is amazing. I like it. #TeamTamsha

_My Life My Message by Mahatma Gandhi_

_Linkedin https://www.linkedin.com/in/festus-langat-57814165| Mozilla
https://mozillians.org/en-US/u/festolangat/|Twitter
https://mobile.twitter.com/festolangat|Blog
<www.festolangat.wordpress.com>|Facebook
https://www.facebook.com/fes.route.fes04|_
_| Mobile +254725077838|__Home: +254726554319 |_

**Comment by JoashMango** [comment]
Love it good article

**Comment by JoashMango** [comment]
The idea on trivia app looks good to me but i would like to ask if we could also have an video part of it to address the illiteracy issues we have in the project areas

**Comment by lauradereynal** [comment]
@JoashMango what about the ideas from the hackathon, not just the trivia app. 
- Which one do you think it's interesting to pursue for this project? and Why ?

**Comment by lauradereynal** [comment]
I've been thinking a little bit, and I think 2 threads might be interesting for the first prototype: 
- The icon game
  Pros: simple, fun, interesting, different style of learning, addresses direct demand from the research. 
  Cons: maybe it only addresses a part of the participants, and maybe that portion is too small. 
  Idea: Can we work on it by adding difficulty levels? or other topics than icon? I'm thinking we could pair it with the trivia from @flukeout 
- The data cost 
  Pros: really huge demand for understanding cost, very tailored to people's needs, innovative.
  Cons: is it really a digital skill ?

What do you guy think ?

**Comment by JoashMango** [comment]
i don't know if i will be biased here because i was in that team. I would go for Duma concepts.
my argument is the same as Laura but i would also add based on the interventions most people do not use they full potential of their phone due to lack of knowing the functionality of some app. With this in mind we can add the usage of different common app using the same @flukeout idea

**Comment by TheBonface** [comment]
I think the Trivia game and the icon game can be combined to form a single game , with each forming different levels 
pros: hitting two birds with one stone and creating more fun levels with both text and graphics

**Comment by alanmoo** [comment]
@LauraReynal, to your question of data cost- I think that having better insight into what's going to cost you money is definitely a digital skill, as it will lead less "fear" of technology and a better connection with the digital world and understanding of how to take advantage of it. That being said, I think that participants' current digital literacy skills have to be taken into account when choosing which project to move forward.

**Comment by JoashMango** [comment]
I do not think knowing the cost of data is a digital skill to me this is a financial skill. There are tow things here we need to separate the cost of data and the connectivity. Knowing on how to connect the data and it usage is a digital skill but its costing  is not.

**Comment by secretrobotron** [comment]
>  I think that participants' current digital literacy skills have to be taken into account

I agree, and I'm going to go against the grain a little and propose that the ideas from Jisort! (and Nifunze) would be good to explore. They also address a bunch of direct demand from research, albeit as a set of "tutorials". It's potentially less game-like, and more simple, but it addresses practical needs and helps people solve problems they have with connectivity, app installation, and really, whatever other questions arise. Also, the personalization aspect of it may make it more approachable (less boring).

Here's my suggestion:
- Build out some (or all) of Jisort! because it's a great entry point for troubleshooting and learning about your phone directly—not through a game.
- Package a game _inside_ Jisort if we've got the bandwidth. We might find that people have fun with it, and it's a simple enough concept that it makes sense to package with a more robust knowledge tool (like the rest of Jisort!).
- **Potentially, it would then serve as a platform for adding new content later.** Think: if people get comfortable with Jisort in this round, there is potential to add sections or content to it later, or at least have it be a method of collecting inquiries from participants more often (e.g. a little form you can fill out to ask a question). Something to measure.
- How can we add some form of reliable metrics to see how people are using the app? Maybe just some specific questions researchers can ask in the field?

**Comment by secretrobotron** [comment]
Another example: Jisort! + Data Usage seems pretty natural to me, and could feel natural to participants after they've been introduced to it.

**Comment by JoashMango** [comment]
I agree with you @secretrobotron

**Comment by secretrobotron** [comment]
cc @Obadha

**Comment by secretrobotron** [comment]
For reference, @Obadha and @flukeout's work: https://docs.google.com/document/d/1SXI7P4xRoG4AtJ4-Cpct8n--IfQZXSy_aWfMGKys22s/edit?ts=5722854c

**Comment by Erict19** [comment]
I love the forward-looking ideas coming out of this hackathon, and my apologies for chiming in late to the discussion. I think there are elements across all of the ideas that would resonate and be helpful to users, and am wondering if there is a way to pull aspects of each together in a coherent user experience (as other have also suggested). In particular, I could envisage combining the Jisort-style virtual assistant with the trivia/gamification elements as the underlying UI design that weaves in important learnings around data-costs, icon identification, and broader Duma FAQ insights. To incentivize these learnings, it could be powerful to have the user earn data alongside their progression. Happy to share parallel examples from other markets of some of these ideas in action if it would be helpful.

**Comment by flukeout** [comment]
Hi @Erict19 - please share any examples or benchmarks that you're aware of, it would be very helpful.

**Comment by secretrobotron** [comment]
> it could be powerful to have the user earn data alongside their progression

That's a super interesting aspect we hadn't addressed yet. I'm not sure we'll be able to pull off that specific incentive within this project, but I love the direction you're thinking in.

Thanks for the input @Erict19. We had thinking along similar lines this morning, and decided to build something of a hybrid. Would love your thoughts.

We've just created some more github issues to follow up:
- Develop Wireframes: https://github.com/MozillaFoundation/digital-skills-observatory/issues/153
- Choose content: https://github.com/MozillaFoundation/digital-skills-observatory/issues/151
- Figure out the technical bits: https://github.com/MozillaFoundation/digital-skills-observatory/issues/154

**Comment by secretrobotron** [comment]
@Erict19 and as @flukeout said, please do share any examples you've seen. Anything that can help us hone in on content, design, and technical considerations.

**Comment by Erict19** [comment]
Apologies for the slow response @secretrobotron  -- just getting back from a work trip -- you might find some of the examples and optimization strategies here relevant: http://www.cgap.org/blog/optimizing-next-billion-users

**Comment by secretrobotron** [comment]
Thanks @Erict19. Great support. Will read.

**Comment by secretrobotron** [comment]
Work has begun on Jisort! https://github.com/MozillaFoundation/digital-skills-observatory/issues/174
