### ISSUE TITLE
Brainstorming for the January training

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#15]
2.5 days of awesome learning. Let's write here all the ideas we had for Mozfest that we were not able to do and make them happen for real in Kenya.

**Comment by secretrobotron** [comment]
Empathy Café

**Comment by lauradereynal** [comment]
**colllaborative toolkit** : can we have this as a deliverable for this training where every researcher and volunteer leaves with their project toolkit, that would have been designed together

**Comment by lauradereynal** [comment]
Banyan Tree for Kenya

**Comment by lauradereynal** [comment]
Slow ethnography

**Comment by lauradereynal** [comment]
Asking questions - think critically

**Comment by lauradereynal** [comment]
DFS 
Short debrief from the Kenya Financial Diaries

**Comment by secretrobotron** [comment]
Github + data collection

**Comment by lauradereynal** [comment]
These ideas have been incoroporated into a draft agenda. 
A v1 can be found here. https://docs.google.com/spreadsheets/d/1Jh8hUyAkLFQPpm1m58Rl8Lx2V1iqWRw7OwKsq4dilt0/edit#gid=22209634

closing this
