### ISSUE TITLE
Monthly reporting - April 2016 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#150]
Send monthly reporting to Gates for April. 

Accountable: @KalpanaSimhan 
Responsible: @secretrobotron and I 
Consulted @JoashMango and @DuncanGW

**Comment by lauradereynal** [comment]
Hey @JoashMango and @DuncanGW would you please be able to jump in the usual monthly reporting document and review ?

**Comment by JoashMango** [comment]
done

**Comment by lauradereynal** [comment]
thanks. Im also done a first pass. 
It's ready for @secretrobotron and @KalpanaSimhan to jump in :smile:

**Comment by lauradereynal** [comment]
@Kalpana and @secretrobotron did you get a chance to review? 
I think we can send it today or tomorrow latest.

**Comment by secretrobotron** [comment]
Sent!
