### ISSUE TITLE
Wireframe several approaches to the Quiztorial game.

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/digital-skills-observatory#153]
**To consider**
- How do users start, how do they ask a question or select the right content section.
- How is the tutorial information presented?
  - Text
  - Images
  - Audio
  - Video
- How are the questions presented
- Is progress tracked

Currently we have some work done in 
- @flukeout's quiz prototype
- Hackathon team's icon game

**Comment by secretrobotron** [comment]
From @Obadha's question in https://github.com/MozillaFoundation/digital-skills-observatory/issues/154#issuecomment-218202045:

> Will this come up as the user goes about their business on the phone, or will it be running separately so that user interacts with the app separately?

**Comment by flukeout** [comment]
Some early wireframes here, will continue with more options & approaches
https://dl.dropboxusercontent.com/u/109902/quiz-wires-2.pdf

**Comment by secretrobotron** [comment]
Some more ideas from the call today:
- Maybe we invert voice recognition, like when I click on an icon it asks, "Do you want to learn about x? Tap here again." cc @chadsansing 
- Double-tap w/in a time interval launches the scenario for users who've learned what each icon does. cc @chadsansing 
- Wifi topics: Am I on wifi? Can I connect to wifi? Am I on the cellular network? How much data do I have left? Content - a mash up of questions from blog posts + hack jam ideas. cc @chadsansing 
- Use user's current activity to figure out how to help them better; where to guide them when they open the app cc @flukeout

**Comment by secretrobotron** [comment]
- analytics: measure where people are clicking on the app cc @LauraReynal

**Comment by secretrobotron** [comment]
Note from @adamlofting about analytics: "Google Analytics android SDK can collect stats offline and then syncs when there is a connection" cc @brianmwadime

**Comment by secretrobotron** [comment]
cc @Amuti would love your feedback on @flukeout's wireframes. We're starting to translate this stuff into implementation bugs.

**Comment by secretrobotron** [comment]
We've got a better idea of how to do this now.
