### ISSUE TITLE
Decide how we will build the Quiztorial from a technical standpoint

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/digital-skills-observatory#154]
- Will this be a native android app?
- Will this be an HTML app (phonegap)?
- Will we use a framework like React etc?

**Considerations**
- What can we iterate on quickly?
- What's easy to modify
- What's the best setup to allow people to contribute

**Other questions**
- How will we distribute this app?
- What's the maximum size for the app based on typical phone capacity in the field?

**OS Questions**
- Can our app be aware of what someone is doing in the OS?
- Can we float a button over the OS while someone is using it?
- Look into the Facebook 'faces' app?
- Check out the work from the Prototype from hackathon

**Comment by secretrobotron** [comment]
@DuncanGW @dobbz @brianmwadime can you help us out here?

**Comment by Obadha** [comment]
Suggested Consideration :
Will this come up as the user goes about their business on the phone, or will it be running separately so that user interacts with the app separately?

**Comment by secretrobotron** [comment]
Note: can we use "chat heads" on every version of android?

**Comment by Obadha** [comment]
They are called "Floating Action Buttons". I'm not sure about what version
supports it or doesn't, I'll have to verify and get back to you with the
answer to that.
On 10 May 2016 19:15, "Bobby Richter" notifications@github.com wrote:

Note: can we use "chat heads" on every version of android?

**Comment by Obadha** [comment]
This should be a **native** android application for the following reasons:
1. **All our target users will be using android smartphones.** It would make little sense to therefore use a multi-platform development tool.
2. With native android, we are able to **implement all (android) features we can dream up**, limited of course only by the android versions. Going hybrid might limit us in what we might want to do.
3. Also, the readily available skill set is heavily android ready. Not sure if this is a valid point though.

Distribution should be through the Google Play Store. This way, users will also get to learn how to install an application and use the play store.

**Comment by Obadha** [comment]
I just pushed the Jisort code from the hackathon [here](https://github.com/Obadha/jisort) but I however figured looking at the raw code might not be as useful.
I'm therefore publishing the application on the Google Play Store such that anyone with an android smartphone can download, install and run it and see it in action. It should make better sense then and be easier to follow.

**Comment by secretrobotron** [comment]
> I'm therefore publishing the application on the Google Play Store

@Obadha that's super cool. You could also just drop us the APK. I'm happy to put it on our google drive, actually.

**Comment by secretrobotron** [comment]
> Distribution should be through the Google Play Store. This way, users will also get to learn how to install an application and use the play store.

@Obadha that's a really good idea. Previously, we worried that there would be a problem using Google Play, because some participants are very, very weary of data consumption (even though our app may help them!). However, maybe we can arm the field team (who will install the app on participants' phones) with good hotspots & data so that participants can go through the Play Store experience.

Regardless, I'd like to have an APK hanging around so we can Flashare it to people's phones if needed. Getting it up onto the Play Store is a bonus, imo.

**Comment by secretrobotron** [comment]
@DuncanGW @LauraReynal @JoashMango ^^ what do you think of this Play Store delivery idea?

**Comment by Obadha** [comment]
Good idea @secretrobotron  , here's the [apk file](https://drive.google.com/file/d/0B_oJywu23qXqY3dIc2wxYUk4RGc/view?usp=sharing). You can download it and extract and, stuff.
If you can, confirm receipt and that it works. 
Also, how do you quote someone or their comments in your own comment or reply? =)

**Comment by JoashMango** [comment]
in order to increase respondents digital skills there is need for them to go through the process of navigation through the phone by using the Play Store to download the App and install. This will make them have know how on downloading App not only for this project but for future skills that might help them

**Comment by secretrobotron** [comment]
> Also, how do you quote someone or their comments in your own comment or reply? =)

Is there a pencil icon in the top-right of my comment? You can click on that and see how I do things. Regardless, just use the ">" character in front of quoted text, just like email. e.g. `> Also, how do you quote someone or their comments in your own comment or reply? =)`

Btw, success:

<img width="329" alt="screenshot 2016-05-12 15 30 38" src="https://cloud.githubusercontent.com/assets/403231/15227706/8425f956-1856-11e6-9ca4-8896f9692fe9.png">

Thanks, @Obadha !

**Comment by secretrobotron** [comment]
> there is need for them to go through the process of navigation through the phone by using the Play Store to download the App and install.

Yeah, definitely, @JoashMango. Should we prepare to have hotspots that participants can connect to when we go to deploy the app?

**Comment by JoashMango** [comment]
@secretrobotron Yes we need to have hotspot for connection as this to me will have the participants who have not used wifi have chance to use it. The last option also we need to have the App incase we go to areas without internet then we can install directly to participants phone

**Comment by dobbz** [comment]
> > Considerations
> > What can we iterate on quickly? **UI (the look)**
> > What's easy to modify
> > I agree on sticking with android
> > What's the best setup to allow people to contribute
> > I believe github would be the best place to edit.
> > I also think the documentation is what can really help even non technical people to give ideas
> > I guess the steps would be
> > 1. List all features we want the app to have(what we want to address and UX)
> > 2. Categorize the features and break them down to tasks and to do's
> > 3. Prioritize to do's and assign tasks
> > 4. Most importantly comment all classes, functions, loops so the code can be easily maintained and those with less experience can actually help

**Comment by brianmwadime** [comment]
Hi guys,
you can find the repo link here:  [Mozilla DSO Quiz Application](https://github.com/ihub/Mozilla-DSO-Quiz-Application)
