### ISSUE TITLE
Coms - Create the Mozilla internal communications material

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#156]
with @secretrobotron 
To do 
- [x] write the position paper for DSO #155
- [ ] create the DSO Mofo working group
- [ ] send an email with all mofo 
- [ ] schedule a call and QA with all mofo 
- [ ] prepare something for the project call 
- [x] Prepare something for london all-hands #157

**Comment by secretrobotron** [comment]
We've submitted some stuff to Kristina for circulation already. @LauraReynal do you want to do more here yet?

**Comment by lauradereynal** [comment]
It's good.
