### ISSUE TITLE
DSO at london all hands 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#157]
Goal: Communicate about DSO during the london all hands, in order to raise awareness about the project, improve it and build on it. 

@secretrobotron do you already have ideas of what we can do ?
- It would be nice to have a Mozfest like experience with an installation somewhere for example. I would love to build another photo wall. 
- Can we make a flyer ? 
- Can we make a poster?

**Comment by secretrobotron** [comment]
@LauraReynal spec'd it out a bit in the position paper. Let's finish this up and file an all-hands bug to get on the schedule.

**Comment by secretrobotron** [comment]
I think it would be nice to create posters/flyers once we have more analysis done. For now though, an all-hands session is scheduled, and we're in the process of inviting people.
