### ISSUE TITLE
Publish research questions on our website

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#158]
Goal: Publish the research questions on our website

@secretrobotron

**Comment by secretrobotron** [comment]
Can publish a static list right on the website.

**Comment by lauradereynal** [comment]
YES please. The file https://github.com/MozillaFoundation/digital-skills-observatory/blob/master/questions.md is up to date if you want to copy paste that !

**Comment by secretrobotron** [comment]
Done! Check http://mzl.la/dso.
