### ISSUE TITLE
Interview 4 - Prepare Interview Questions

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#159]
Include the icons screenshot ?

**Comment by lauradereynal** [comment]
Add the Privacy questions from interview 3

**Comment by lauradereynal** [comment]
Should we start and try to tackle that today ? @DuncanGW @JoashMango 

Sure we can start it today in the after lunch

**Comment by secretrobotron** [comment]
Done @ bootcamp.
