### ISSUE TITLE
Plan interview schedule for Mozilla team in the different field trips. 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#16]
Ask DDD what we can do when we come on the field. 
We want to meet participants and conduct qualitative interviews / get to know them. 
Would this be a problem ? Out of scope from the initial contract with the particiants ?

**Comment by JoashMango** [comment]
This is doable . It will also be fun to know what the participants think as it will form the basis of the research

**Comment by lauradereynal** [comment]
Ok. perfect. Let's follow up for January next time we meet.

**Comment by lauradereynal** [comment]
Perfect thank you ! closing this for now, will file new tickets when we need proper scheduling.
