### ISSUE TITLE
Analysis - do an early analysis between treatment and control group 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#160]
Do we observe any difference so far?
@secretrobotron @DuncanGW @JoashMango Let's do a first analysis at the end of this month

**Comment by JoashMango** [comment]
will see the difference when we do interview 3. With that we will see the effect of the interventions on the treatments

**Comment by lauradereynal** [comment]
Awesome. Let's do a session after interview 3 to do a first analysis

**Comment by secretrobotron** [comment]
Moving to next milestone, for followup after Interview 3.

**Comment by secretrobotron** [comment]
👍 we can do another pass at this when the DDD activity report is done.

**Comment by lauradereynal** [comment]
This is done and we are moving forward, refining for the next phase of the project.
