### ISSUE TITLE
Add the graphic timeline on our website 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#162]
@secretrobotron If you want to redo this graphic, feel free. 
And let's add it to our website 
![dso simplified - new page](https://cloud.githubusercontent.com/assets/8261945/15251626/42336868-1922-11e6-997f-c2e47198f76b.png)

It looks very informative but research wise we do not share our methodology in the public before we publish it otherwise someone can have the same idea and publish a head of us thereby making our finding obsolete that is just my thoughts

**Comment by secretrobotron** [comment]
![program structure](https://cloud.githubusercontent.com/assets/403231/15255894/9aa68fcc-190c-11e6-97b1-9c47ff22eb7e.png)
