### ISSUE TITLE
Make the PAR research model graphic and upload it on our website

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#163]
Update this graphic and add it to our website @secretrobotron 
![dso venn diagram - plain](https://cloud.githubusercontent.com/assets/8261945/15251964/c1cee808-1923-11e6-8ecd-e2bbfc19c987.png)

**Comment by lauradereynal** [comment]
Need to edit the "Action section" and remove the Webmaker software

**Comment by secretrobotron** [comment]
![par-black](https://cloud.githubusercontent.com/assets/403231/15258901/0dc0b186-191c-11e6-9d06-fbd3b4d78219.png)

@LauraReynal I think this describes the approach enough. If we write some text to augment (can go in reports and on the website), it will be clear.

**Comment by secretrobotron** [comment]
Assigning to @LauraReynal for some review.

**Comment by lauradereynal** [comment]
Here is a new copy suggestion: 
- **Participatory**: Capacity-building, volunteering experience, multi-node research and learning network
- **Action**: Iterative, introduction of digital skills workshops and prototypes, user-centered design
- **Research**: Experimental research, hypothesis based, quantitative, ethnographic.

**Comment by lauradereynal** [comment]
what do you think @secretrobotron ?

**Comment by secretrobotron** [comment]
I don't think a simple copy change is going to cut it here. I'll make a new diagram.

**Comment by secretrobotron** [comment]
I've made this a little interactive thing and put it on the website. That'll suffice for now.
