### ISSUE TITLE
Follow up and close intervention 2

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#164]
Here is a first checklist for intervention 2 based on our experience for intervention 1. 

**Date:** Weekend of June 18th - to be confirmed 
**Leaders**: one leader for each region will be the main point of contact. We can rotate leaders for the next intervention. 

**Checklist**
- [x] DDD and Open Researcher leads identified
- [x] Dates confirmed
- [x] Prep meeting scheduled for people on the ground
- [x] Participants attendance confirmed for chosen dates
- [x] Open Researcher attendance confirmed for chosen dates
- [x] Mozilla team to confirm community members coming for the intervention prior to the intervention itself and the roles they will be taking the intervention.
- [x] Curriculum done with the community
- [x] Reporting guide ready
- [x] Curriculum and reporting guide piloted 
- [x] Locations suggested
- [x] Final location chosen
- [x] Intervention execution
- [x] During the intervention everyone takes notes on the reporting document and types them in an analysis document 
- [ ] Conduct debrief on skype with the team 
- [ ] Write a summary of learnings

@secretrobotron

For dates we need to discuss as a lot need to go in for planning

**Comment by secretrobotron** [comment]
@chanditome @DuncanGW @denomain @zuma1 @nmarita @alexanderamolo @nekesawekesa

**Comment by secretrobotron** [comment]
Notes here: https://docs.google.com/document/d/1jttgUXNl4ZgjfvYYt3e9WFo7SF6rpx8cSc1MKE_HZLI/edit#

**Comment by secretrobotron** [comment]
@marywashe

**Comment by secretrobotron** [comment]
from @FauziaIsmail:

> We made some progress. We're working on finding a suitable place that won't cause any inconvenience when it comes to time allocation.

**Comment by secretrobotron** [comment]
@chanditome @DuncanGW @denomain @zuma1 @nmarita @alexanderamolo @nekesawekesa just a reminder that this is here for you to use to get ready.

**Comment by lauradereynal** [comment]
almost everything has been done, but we still need to follow up and probably have a skype call about what is in the reporting guide

**Comment by secretrobotron** [comment]
@LauraReynal do you still want to do this? I think we've built on that work a bit since July.

**Comment by lauradereynal** [comment]
You are right. We should write a summary of the reporting guide for our mid-study report though.
