### ISSUE TITLE
July field trip logistics 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#165]
@secretrobotron we should start thinking about dates for the next trip in July, so that we can tell people to save the date for the bootcamp and all. 
- [x] Pick dates 
- [x] Pick locations 
- [x] Choose bootcamp dates and start organizing it 
- [x] Make sure we can interview participants with the field researchers / or organize special interviews 
- [x] Software prototype deployment

**Comment by secretrobotron** [comment]
We've made a bunch of progress on this. Still need to talk about logistics of prototype deployment, and waiting on final location from @DuncanGW.

**Comment by DuncanGW** [comment]
@LauraReynal @secretrobotron I have added a budget for 1 Malindi hotel (conference +Accommodation + Dinner). For prototype so long as we decide on the venue, it easier for as to sort out the logistics.

**Comment by lauradereynal** [comment]
Done. thanks everyone.
