### ISSUE TITLE
Publish early profiles of participants 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#166]
Goal: Create and pulbish a few profiles from participants so that we can refer them in our design and start sharing information about participants. 

@DuncanGW @JoashMango how is the profiling going ?

**Comment by JoashMango** [comment]
We are stilling compiling but at this point we don't have solid information on individual basis,. We will have concrete information after fourth interview at that point we can distinguish emerging trends on an individual

@LauraReynal

**Comment by lauradereynal** [comment]
Awesome - thanks @JoashMango 👯

**Comment by secretrobotron** [comment]
@DuncanGW has given us map data we can use, but we should anonymize it before we use it.

We're going to release a series of blog posts with images and detailed (anonymized) information about each participant and important things they indicate about the project. First up is Ken in Malindi.

**Comment by secretrobotron** [comment]
#241
