### ISSUE TITLE
What is our consent form with participants 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#17]
@metaphorista do you know what kind of consent form we have with participants for the study?
Are we creating it or is DDD creating it ? 

Im curious about pictures, recording etc. 

cc @secretrobotron

**Comment by KalpanaSimhan** [comment]
One related question to add: Have we already addressed the issue of whether this research is subject to IRB or IEC approval? 

Also, just adding in the bit about participant consent from the proposal: We will explain to respondents about the purpose of the study, and that we are going to seek to interview them six times in the coming year. We will explain that we are likely to ask to see their phone records. We will confirm that all data will be anonymized and that any case studies will disguise their identities; any photos will be used only with their prior permission.

**Comment by hockenstein** [comment]
From a previous note of mine to Lynn:

"For your information, we do require permission from the Government to do
research in Kenya (which includes giving them a copy of any final research
report, which we assume is ok in this case). We already have this
permission.

We are not aware of any Institutional Review Board that has jurisdiction
over this project (usually they are affiliated with universities).We do
sometimes have to apply for IRB certification for doing projects for
academics."

## 

Jeremy Hockenstein
CEO and Co-Founder
DDD
115 West 30th Street, Suite 400
New York, NY 10001 USA
jeremy@digitaldividedata.com jeremy@digitaldividedata.org

+1 212 461 3703 Tel
+1 212 813 3209 Fax
www.digitaldividedata.com

Creating a World of Digital Possibilities

**Comment by JoashMango** [comment]
DDD can create the consent form and incorporate as research you partners, this is because we will be dealing with participant directly

**Comment by lauradereynal** [comment]
That would be perfect @JoashMango 
Can you send us the form when you have it so that we can check from our side too ?

**Comment by lauradereynal** [comment]
Note from today's call: @JoashMango will add the  phone data collection in the consent form

**Comment by lauradereynal** [comment]
more precisely: participants will be asked to share the download of their financial activities such as MPesa monthly usage

Correct @JoashMango ?

**Comment by JoashMango** [comment]
This is correct if we ask them to do so in the initial introduction of the project

**Comment by lauradereynal** [comment]
ok thanks ! feel free to share any doc you already have :)

**Comment by JoashMango** [comment]
I have attached consent form for review by the team
[Informed Consent Form for the Kenya Digital skills observatory Project.docx](https://github.com/MozillaFoundation/digital-skills-observatory/files/56697/Informed.Consent.Form.for.the.Kenya.Digital.skills.observatory.Project.docx)

**Comment by lauradereynal** [comment]
Submit to legal Mofo team to check if okay
Add Mozilla logo

**Comment by secretrobotron** [comment]
Thanks @JoashMango. We'll...
- [x] have someone from our legal team check this over, and
- [x] see if we can add our logo.

cc @LauraReynal

**Comment by lauradereynal** [comment]
I have written to Legal and sent the doc for review 
will keep you all posted

**Comment by lauradereynal** [comment]
Abigail will send an update early next week

**Comment by lauradereynal** [comment]
Update: work in progress - needs another pass regarding images / media collection 

https://drive.google.com/open?id=0B0X05aIHuAbebmJJTV9MdmdnUS1SZk5DNUZFam5YaHZzXzkw

@JoashMango @DuncanGW would you like to have a look?

**Comment by lauradereynal** [comment]
@JoashMango & @DuncanGW 
Abigail just pointed out that the consent form does not include the collection of photos and other medias.
 We would actually need / want to photograph and record some interviews. 

Is it okay with you if we add that in the form? 
thanks

**Comment by JoashMango** [comment]
@LauraReynal 
Its okay to add that component in the form

**Comment by lauradereynal** [comment]
what is our status on this consent form? Can we close this ?

**Comment by DuncanGW** [comment]
Updated : [https://docs.google.com/a/digitaldividedata.com/document/d/1223rd9_1rvDU_gb1oGzo5YVZz1F-W-KES4jRqkcClJg/edit?usp=sharing]
