### ISSUE TITLE
Come up with name for Prototype 1

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#175]
Voting is open.

**Comment by secretrobotron** [comment]
"Jisort" is the current frontrunner.

@LauraReynal @DuncanGW @Obadha @icarius06 @TheBonface @chanditome @Amuti @flukeout @nao07 @WinnieMakokha @nekesawekesa

**Comment by lauradereynal** [comment]
works for me

**Comment by JoashMango** [comment]
Okay with me

**Comment by brianmwadime** [comment]
Thumbs up from me as well.

**Comment by secretrobotron** [comment]
CONFIRMED:

Long live Jisort!
