### ISSUE TITLE
Design Floating Action Button

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#176]
Design an icon for the Floating Action Button that will launch the app.

Questions:
- Should it involve a character to humanize our app a bit? (@LauraReynal)
- Can it be animated? (potential danger: Clippy)

![](http://vignette1.wikia.nocookie.net/uncyclopedia/images/c/cb/Clippy.png/revision/latest?cb=20081018021125)

**Comment by secretrobotron** [comment]
cc @Amuti

**Comment by festolangat** [comment]
The idea of Floating icon or tooltips is an important concept. I think
i like that.

On 5/18/16, Bobby Richter notifications@github.com wrote:

> cc @Amuti
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/176#issuecomment-219856341

## 

_My Life My Message by Mahatma Gandhi_

_Linkedin https://www.linkedin.com/in/festus-langat-57814165| Mozilla
https://mozillians.org/en-US/u/festolangat/|Twitter
https://mobile.twitter.com/festolangat|Blog
<www.festolangat.wordpress.com>|Facebook
https://www.facebook.com/fes.route.fes04|_
_| Mobile +254725077838|__Home: +254726554319 |_

**Comment by secretrobotron** [comment]
This is super done.
