### ISSUE TITLE
Host APK to access for testing

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#178]
Once there is a stable build process, put a regular APK somewhere that multiple people can access to test.

**Comment by secretrobotron** [comment]
Basically, provide a URL that will be updated regularly.

**Comment by dobbz** [comment]
I believe DDD can help with this as we have cloud hosting service dedicated to this project.

Do we want/need push updates in case we add new features to the app it can prompt the user to update? #174
If so we may need certs to sign the app.

**Comment by secretrobotron** [comment]
@dobbz yeah, that's a great point. We would need to set the app up through the Play Store in that case, right?

In the meantime, for hosting the APK, @brianmwadime thought that tagging releases on github will work so that they're downloadable right from here. Think we need something else?

**Comment by brianmwadime** [comment]
@secretrobotron @dobbz  you can find the release versions here :
[Mozilla DSO *.apks](https://github.com/iHub/Mozilla-DSO-Quiz-Application)

**Comment by secretrobotron** [comment]
Looks good for now :).
