### ISSUE TITLE
Prototype 1 - Test Prototype 1 Alpha

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#179]
Ask several people to reach out to friends, relatives, and other people to test the alpha version of Prototype 1. Can happen in Kenya, Canada, London, USA, India, etc., as long as we get lots of device exposure.

@DuncanGW it would be good to write out a specific list of devices to test if we have that data.

Followup from #174.

**Comment by secretrobotron** [comment]
What devices do we have? Please list device type and version of Android.

**Comment by secretrobotron** [comment]
cc @Obadha

**Comment by secretrobotron** [comment]
cc @TheBonface

**Comment by Obadha** [comment]
Are we talking about what we have on us, or what the participants have, or what we can get access to?

**Comment by secretrobotron** [comment]
It would be good to have a list from @DuncanGW about which devices/versions we need to cover. But, we should also have an inventory of phones we have access to for testing.

**Comment by brianmwadime** [comment]
@secretrobotron  @Obadha  @DuncanGW Do we already have a minimum android version we're working with?

**Comment by Obadha** [comment]
@brianmwadime that's a very important question.

As of now, I think not. I would think API Level 14 (Version 4.0 - Ice Cream Sandwich) would be a good bet.

@DuncanGW @JoashMango  might be able to advice better based on data they have from actual devices owned by participants of the study. That way we'll be building something that all the immediate participants should all be able to use.

**Comment by dobbz** [comment]
Actually we have a number of versions of android from 2.1 to 5.1.1

Here are some stats as at yesterday. 
2.3.5   1
2.3.6   4
4.0.4   2
4.1.2   3
4.2.2   31
4.3     3
4.4.2   70
4.4.4   8
5.0.2   4
5.1     2
5.1.1   2

There are some phones in which some removed the app(6) and about 3 are yet to sync due to the remoteness of their areas (there is no 3g or edge, just GPRS which really can't sync).

We have access to a low end chinese phone(2.3.6), standard phone(4.3), mid range (4.4.4). We can get access to a 5.1.1 phone and an android one (6.0) phone that are also common in this region.

**Comment by secretrobotron** [comment]
Thanks @dobbz.
I have some 5.x and 6.x devices lying around on which I can test. I have access to a Nexus 5 and a Nexus 5X.

@flukeout can you give those Nexus 5s to @kristinashu before you leave?

**Comment by dobbz** [comment]
Here is a better list. Notice all models are below USD $150 retail and there are no phones in the list with any official upgrade plans to version 6.

```
Make        Model               ver     Total
sprd        itel it1400         2.3.5   1
ALCATEL     ONE TOUCH 4010X     2.3.6   1
ALCATEL     ONE TOUCH 918       2.3.6   1
samsung     GT-S5300            2.3.6   1
HUAWEI      Y220-U00            2.3.6   1
samsung     GT-S5301            4.0.4   1
samsung     GT-S7560            4.0.4   1
lge         LG-E440             4.1.2   1
samsung     GT-S7262            4.1.2   2
TECNO       TECNO M3            4.2.2   2
Huawei      HUAWEI Y330-U11     4.2.2   7
samsung     GT-I8200N           4.2.2   1
Huawei      HUAWEI Y330-U01     4.2.2   4
TECNO       TECNO P5S           4.2.2   2
NLC         Mini S5             4.2.2   3
HUAWEI      HUAWEI Y511-U10     4.2.2   1
TECNO       TECNO H5            4.2.2   3
samsung     GT-S7580            4.2.2   3
samsung     GT-S7582            4.2.2   2
alps        M8                  4.2.2   2
alps        V3+                 4.2.2   1
TECNO       TECNO B5S           4.3     2
samsung     GT-I9300            4.3     1
Huawei      T1 7.0              4.4.2   2
Infinix     Infinix X507        4.4.2   3
TECNO       Y3S                 4.4.2   15
HUAWEI      HUAWEI Y221-U22     4.4.2   2
TECNO       TECNO R5            4.4.2   1
Vodafone    VF685               4.4.2   20
HUAWEI      HUAWEI Y541-U02     4.4.2   1
itel        itel_it1503         4.4.2   3
Spreadtrum  LG-H815T            4.4.2   2
TECNO       TECNO-Y5S           4.4.2   1
HUAWEI      HUAWEI Y360-U31     4.4.2   3
TECNO       TECNO H6            4.4.2   1
itel        itel it1407         4.4.2   3
HUAWEI      HUAWEI Y336-U02     4.4.2   2
samsung     SM-G350E            4.4.2   1
M3          M3                  4.4.2   1
alps        SM-G900H            4.4.2   1
TECNO       TECNO L6            4.4.2   1
HUAWEI      HUAWEI Y520-U12     4.4.2   2
TECNO       TECNO-Y4            4.4.2   2
TECNO       TECNO-M6S           4.4.2   1
FOTOLA      C552                4.4.2   2
samsung     SM-J100H            4.4.4   5
samsung     SM-J110F            4.4.4   1
samsung     SM-G316HU           4.4.4   2
samsung     SM-T355             5.0.2   1
TECNO       TECNO-C8            5.0.2   3
Infinix     Infinix NOTE 2      5.1     1
InnJoo      Max2_3G             5.1     1
Infinix     Infinix X510        5.1.1   2

```

IMO I think we should try as much as possible to test with phones that have the lowest specs
(1Ghz _[single core]_, 512Mb ROM and 256MB RAM) as this covers almost three fifths of our respondents devices.
Another thing to consider is application size, especially if it will have an sqlite database. These phones usually have very limited memory and will start to show significant increase in response times if the app does not truncate the data it collects periodically.
