### ISSUE TITLE
Create Intervention 2 invitation video

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#186]
@shey02 offered to lend her creative videography talents to create an invitation video for Intervention 2 that will encourage study participants (including those that didn't show up to the first intervention) to show up.

Rough storyboard:
1. introduction
2: some activity from the intervention
3: quotes from participants
4: more activity
5: more quotes
6: @shey02 & @FauziaIsmail saying hello

cc @JoashMango @LauraReynal @DuncanGW

**Comment by shey02** [comment]
glad to do it :)

On Wed, May 18, 2016 at 1:32 AM, Bobby Richter notifications@github.com
wrote:

> Assigned #186
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/186
> to @shey02 https://github.com/shey02.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/186#event-663694420

## 

Shehnaz Abubakar K.
Kenyatta University, BSCIT.
Volunteering Committee,MombasaTech.
Intern,Techbiz Limited,Msa.

**Comment by JoashMango** [comment]
This will be very great as some people understand more easily by visually seeing

**Comment by lauradereynal** [comment]
@shey02 @FauziaIsmail do you think that you can produce a first draft by the end of the month of May ?

**Comment by shey02** [comment]
Yes ! Once am done with the first part i will be able to send it to you guyz so that you can put in your comments/opinions/suggestions

**Comment by lauradereynal** [comment]
hey friends, let us know if we can help you here 😄

**Comment by shey02** [comment]
hey laura,thanks i will be able to send in my work soon so that you guys
can tell me your views :)

On Tue, May 31, 2016 at 5:02 PM, Laura de Reynal notifications@github.com
wrote:

> hey friends, let us know if we can help you here 😄
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/186#issuecomment-222697879,
> or mute the thread
> https://github.com/notifications/unsubscribe/AP9VrbjRAggRvf1660zi8fzrPJmVJsnyks5qHD9ygaJpZM4IgxNh
> .

## 

Shehnaz Abubakar K.
Kenyatta University, BSCIT.
Volunteering Committee,MombasaTech.

**Comment by secretrobotron** [comment]
@shey02 were you able to upload a copy to youtube today?

**Comment by shey02** [comment]
Hello Bobby,yes i managed to do that.Here's the link

https://youtu.be/Ar3B7Rq68mE

I would like to request everyone to comment and suggest anywhere they think
it needs correction/editing.

On Thu, Jun 2, 2016 at 9:15 PM, Bobby Richter notifications@github.com
wrote:

> @shey02 https://github.com/shey02 were you able to upload a copy to
> youtube today?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/186#issuecomment-223376277,
> or mute the thread
> https://github.com/notifications/unsubscribe/AP9VrYz_6IQOABTSn7QdQKV19_x5MyF0ks5qHx3TgaJpZM4IgxNh
> .

## 

Shehnaz Abubakar K.
Kenyatta University, BSCIT.
Volunteering Committee,MombasaTech.

**Comment by Obadha** [comment]
It's awesome! Excellent video quality.
Good stuff Shy.

I'd suggest adding subtitles. If not for the whole video, for the parts where Swahili is spoken.

**Comment by marywashe** [comment]
Wow, that was great. 
I second the idea of adding subtitles.
Towards the end, some photos were too flashy.

**Comment by JoashMango** [comment]
The video is great but where kiswahili is spoken add the subtitles

**Comment by marywashe** [comment]
You can also consider adding swahili subtitles where English is spoken, for the sake of some respondents.

**Comment by sangson07** [comment]
I agree to this..swahili subtitles would really helpMozillaFoundation/digital-skills-observatory wrote:You can also consider adding swahili subtitles where English is spoken, for the sake of some respondents.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

Best regards,

Sang Edwin

**Comment by lauradereynal** [comment]
thanks for this hard work @shey02 
The video is super awesome. 

My only main feedback, is that it's a bit long. Do you think that you might be able to do a shorter one? 
What do you think could be cut a little bit ?

**Comment by secretrobotron** [comment]
👍 yeah, I totally agree. This is a great first cut! Thanks @shey02 😄.
* It would be helpful to aim for a video that's 1:00 or 1:30 in length. Then people can share it more easily and watch it quickly. Think that's possible?
* The participants look great in there, and the cuts between them work well. That's the material a shorter video should focus on.

I'll try to dissect it a bit more this week and give you some more feedback :).

**Comment by secretrobotron** [comment]
@shey02 thanks again for putting this together. I'd love to finish it as an asset that we can publish for the project. Can we work on this again soon?
