### ISSUE TITLE
Pilot the curriculum for intervention 2 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#187]
Goal: run a couple of tests for intervention 2 that will help us improve the curriculum and analysis questions. 

Method: 
- A volunteer finds a learner and schedules a couple of hours to run the curriculum with him / them. 
- They teach the curriculum with the learner and observe what works well and what needs improvement 
- The volunteer runs a debrief session with Bobby and Laura 
- We adjust the curriculum accordingly 

@secretrobotron

**Comment by secretrobotron** [comment]
Pilot is being run by @zuma1 and @chanditome and maybe @denomain. This is "in flight"; closing.
