### ISSUE TITLE
Fix header image transitions on website

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#188]
In Firefox, mzl.la/dso's header image changes suddenly, but in Chrome it does a smooth transition. I think this is due to [background-image not working as a transition property in Firefox](http://stackoverflow.com/questions/19808764/transition-for-background-image-in-firefox), but I'm not sure.

What do you think, @Obadha?

**Comment by Obadha** [comment]
Oh man @secretrobotron  I totally missed this. My bad! :laughing: 

Yes, and from the search results it appears to be a common and known issue with Firefox. I'll look deeper into and see if there exists a fix or a work-around.

**Comment by secretrobotron** [comment]
Cool! Thanks @Obadha :). I couldn't figure out a way to do with without a tremendous amount of CSS/JS to support it.

**Comment by secretrobotron** [comment]
I think we'll just have to live with this until Firefox and Chrome can agree on stuff 💃 .
