### ISSUE TITLE
Itemize system-level information that an app has access to.

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/digital-skills-observatory#189]
What does an app running in the background on Android know about the state of the phone?

Knowing this can help up design a feature that can suggest a helpful topic for a user. For example, if we know the battery is low on the phone, we can suggest information about battery life.

Here are the [API methods](https://developer.android.com/reference/android/app/package-summary.html) we have access to

**Useful info**
- Is the phone connected to WiFi
- Is the phone connected to the mobile data network
- Is the phone battery low
- Are there unread SMS messages? - possible?

**Comment by icarius06** [comment]
As long as the app running in the background has the permissions, it has access to a wide array of states through a TelephonyManager object you can check them out here .
https://developer.android.com/reference/android/telephony/TelephonyManager.html. Technically its possible

**Comment by flukeout** [comment]
Thanks, @icarius06 - let's identify some we think might be useful.

**Comment by brianmwadime** [comment]
To add on to @flukeout list
**Useful info**
- Is bluetooth enabled [bluetooth api reference summary](https://developer.android.com/reference/android/bluetooth/package-summary.html)
- External storage access (space used/remaining)

**Comment by brianmwadime** [comment]
@secretrobotron @alanmoo this functionality can be viewed on the latest release at [Mozilla DSO android app](https://github.com/iHub/Mozilla-DSO-Quiz-Application/releases)
- Wifi/network states
- Location enabled
- Bluetooth state
- Battery level event
- Applications installed event
- Low storage event
- Boot completed (for restarting the chat head service)

**Comment by secretrobotron** [comment]
@brianmwadime how can we check out that functionality? Is there a way to test with the latest release?

**Comment by brianmwadime** [comment]
Yes @secretrobotron For the items, either switch of/on wifi, location,
switch on Bluetooth e.t.c the cards will appear at the top of the screen.

Brian Mwadime M.
Phone: +254728956895
Skype: brian.mwadime
Work: Web & Mobile software engineer
Personal E-Mail: brian.mwadime@gmail.com
Work E-mail : info@brianmwadime.com
Website(s): brianmwadime.com, f http://code-hive.netortunekidew.co.ke

**Comment by secretrobotron** [comment]
👍 ok, I tried a few things and got some mixed results. 

This is the card that's always up when Jisort is running. It never shows anything different.
<img width="330" alt="screenshot 2016-06-14 12 44 52" src="https://cloud.githubusercontent.com/assets/403231/16041545/d2b6ba56-322d-11e6-86cd-15da4f84ab31.png">

Sometimes, a little grey notification appears for a few seconds when I turn things on and off. Is Jisort doing that?

**Comment by secretrobotron** [comment]
See https://github.com/mozilla/Mozilla-DSO-Quiz-Application/issues/193.
