### ISSUE TITLE
Explore suggested-topics UX

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/digital-skills-observatory#190]
Here's one approach we can take to suggest timely information.

**Scenario**
- The helper app is running in the background on the users's phone
- It detects that the phone battery is low
- The Floating Action Button shows a 'suggestion'
- Clicking the button takes the user to the Helper app with the suggested topic highlighted
  - They can learn more about the suggested topic
  - They can dismiss the suggestion
- If they Learn More, the suggestion is also dismissed when they return

**Flow**
![image](https://cloud.githubusercontent.com/assets/25212/15406035/77062242-1db9-11e6-9634-a512a12f02b4.png)

**Comment by icarius06** [comment]
This is really cool. A much cleaner implementation although i think it would not be a Floating Action Button but rather a View Overlay shaped to look like the button that is clicked to allow the button to be attached to any window. (but that is just semantics). So the service will respond to "events" like the low battery for instance.

**Comment by secretrobotron** [comment]
Hey, @Amuti, what do you think of this flow?

@brianmwadime does this make sense to you? Anything to be aware of? Is it possible to demo this approach (without taking a ton of time)?

**Comment by secretrobotron** [comment]
> but rather a View Overlay shaped to look like the button that is clicked

@icarius06 I think I see where you're going with that, but I'm a bit confused. Can you give an example?

**Comment by icarius06** [comment]
Basically im just thinking about the implementation of the screen shot. A floating Action button cant be attached to any app (system wide) but an overlay can. So when implementing the button, we will use the overlay instead but i believe we can style it to look like what you are referring to as the floating action button.

**Comment by flukeout** [comment]
@secretrobotron @LauraReynal 

This would be a good place to list the different scenarios we'd like to 'help out' with, like the large download you mentioned in the other thread. Feel free to edit the original issue to add them.

**Comment by brianmwadime** [comment]
@secretrobotron yes this is possible. Android does have api's for 'tracking' such system events like low battery , or bluetooth set to on/off e.t.c

**Comment by brianmwadime** [comment]
@secretrobotron  I'll post up the various data points we can access from the device other than the telephony api pointed out by @icarius06.

**Comment by secretrobotron** [comment]
Unfortunately, couldn't fully explore this, but it became the notification system. Filed https://github.com/mozilla/Mozilla-DSO-Quiz-Application/issues/193 and wrote about it on the Jisort release blog post: https://mozilla-foundation-research.herokuapp.com/dso-software-prototyping-update-jisort/
