### ISSUE TITLE
Produce content for Tutorials

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#191]
We need (at least) 3 tutorials for prototype 1. They should focus on a specific topic (e.g. WiFi) within a category (e.g. connectivity), and include copy/images (or sketches of them).

https://docs.google.com/document/d/1PMK72_jRepGkhtKoK1wHv4NPwnBhub9yjK7pIwVzeTM

Followup from #151.

**Comment by secretrobotron** [comment]
cc @LauraReynal

**Comment by nekesawekesa** [comment]
Hi,
Can we teach them about
use of computer and  computer operation in General
How to open and use emails
How to use search engines

Thanks
NEKESA

**Comment by lauradereynal** [comment]
Thanks @nekesawekesa that's super helpful. 

Can you explain why computers would be important here?

**Comment by lauradereynal** [comment]
@secretrobotron what is our deadline here?

**Comment by nekesawekesa** [comment]
Hi,
Most respondents wanted to learn about computers and laptops

Thanks
Nekesa

**Comment by secretrobotron** [comment]
Work started here: https://docs.google.com/document/d/1PMK72_jRepGkhtKoK1wHv4NPwnBhub9yjK7pIwVzeTM/edit#

**Comment by secretrobotron** [comment]
@brianmwadime I love the idea of using gifs as tiny movies in our tutorial sections. Is that possible?

**Comment by secretrobotron** [comment]
Note for later: once we have something substantial, @chadsansing should take a peek.

**Comment by secretrobotron** [comment]
@brianmwadime, I'm finishing a couple of tutorials so that there is some content to sit inside the app as it's developed this week. It's definitely nowhere near completion, but there is some structure. We can treat them as dummies until I'm back and can finish the job.
- Aiplane Mode: https://docs.google.com/document/d/1PMK72_jRepGkhtKoK1wHv4NPwnBhub9yjK7pIwVzeTM/edit#heading=h.qo6kwqe2u28a
- Connecting to Wi-Fi: https://docs.google.com/document/d/1PMK72_jRepGkhtKoK1wHv4NPwnBhub9yjK7pIwVzeTM/edit#heading=h.k7v2ejh1laf2

**Comment by secretrobotron** [comment]
cc @LauraReynal

**Comment by brianmwadime** [comment]
We also need to think of the format the content will be in?

**Comment by secretrobotron** [comment]
For simplicity with Tutorials, we're going to just pick a few that are particiularly relevant. We'll focus on
- Connecting to WiFi
- Data Usage
- The App Store
- Problems with SD Cards
- Freeing up memory

**Comment by lauradereynal** [comment]
I reviewed Tutorial Number 1. The content is good. It's missing the GIFS and the SHENG when necessary. Im going to reach out for help in Sheng.
