### ISSUE TITLE
Screenshot Question Flow

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/digital-skills-observatory#193]
Here's the screenshot question feature revisited in more detail...

![screenshot-flow](https://cloud.githubusercontent.com/assets/25212/15592400/460a7e1e-2358-11e6-9f5e-16ca995c7921.png)

**Questions**
- Can asking the question turn into a chat-like conversation?
- Would asking a question by recording audio be good?
- What are some other ideas to start taking a screenshot?
  - Maybe if you press and hold the floating app badge?
  - Maybe tapping the app badge gives you a few options including a screenshot?
- What types of screenshot annotations are best?
  - Finger-paint circle highlight?
  - Adding arrows?

cc @secretrobotron @LauraReynal 

**Notes**
- I've changed the design of the home screen a bit in the app, I'll make sure that's reflected in the rest of the wireframes for the quiz and tutorials (coming tomorrow)

**Comment by secretrobotron** [comment]
Unfortunately, couldn't fully explore this. Wrote about it on the Jisort release blog post: https://mozilla-foundation-research.herokuapp.com/dso-software-prototyping-update-jisort/
