### ISSUE TITLE
Implement Home Screen

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#196]
From [wireframes](https://dl.dropboxusercontent.com/u/109902/DSO/dso-app-wireframes.pdf)
![screenshot 2016-06-02 11 01 24](https://cloud.githubusercontent.com/assets/403231/15739667/5e80fa64-28b1-11e6-9c37-e3182f533c32.png)

**Comment by brianmwadime** [comment]
@secretrobotron @alanmoo this functionality can be viewed on the latest release at [Mozilla DSO android app](https://github.com/iHub/Mozilla-DSO-Quiz-Application/releases)

**Comment by secretrobotron** [comment]
👍 💥 woo!
