### ISSUE TITLE
Implement Screenshot Questions List

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#199]
See [wireframes](https://dl.dropboxusercontent.com/u/109902/DSO/dso-app-wireframes.pdf) >> Screenshot Section >> last three screens

![screenshot 2016-06-02 11 15 21](https://cloud.githubusercontent.com/assets/403231/15740038/58649670-28b3-11e6-9aca-fb1bc833e0d8.png)

I'm still not 100% sure how we're going to do this, server-side. Should we store these somewhere, or let people share on WhatsApp in a specific group? @LauraReynal @DuncanGW @Obadha

**Comment by icarius06** [comment]
The issue with saving them on a platform such as whatsapp would be scaling the search functionality. Perhaps server side would be a better option if only coz u could optimize retrieval.

**Comment by secretrobotron** [comment]
👍 good thinking, @icarius06. I want to make sure that users are able to ask their questions, and that it's easy for us to have them answered. Maybe,

User asks question >> screenshot delivered to server >> screenshot delivered to whatsapp channel with DSO community in it

or

User asks question >> screenshot delivered to server >> screenshot delivered to dso-community@mozillafoundation.org

Not sure which one is easier for us to reply to. Thoughts?

**Comment by secretrobotron** [comment]
We never got to implement this because it crept out of scope. Wrote about it in the Jisort launch blog post though (https://mozilla-foundation-research.herokuapp.com/dso-software-prototyping-update-jisort/).
