### ISSUE TITLE
Figure out mobile application to track data from the phone

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#20]
Goal; figure out wich method we use to track phone usage

Task:

@adamlofting will look at the one we used in Bangladesh and see if possible / suitable for this project 

@JoashMango and Duncan will look on their side at applications that would work. 

We decide together during our next meeting

**Comment by adamlofting** [comment]
I haven't done any broader research on this yet, but wanted to add one option:
- http://www.qualitytimeapp.com is an app mostly used by people for _reducing_ the amount of time 'wasted' on apps, but it provides friendly easy to read reports on which apps use when, and for how long.
  - We'd have to think through the implications of how this was installed, and how it would affect behaviour, but it might be a good option for the list.

**Comment by adamlofting** [comment]
Also, linking this ticket to our data collection plan #11

**Comment by DuncanGW** [comment]
Another option:
 Data Usage Monitor: [https://play.google.com/store/apps/details?id=com.andcreate.app.trafficmonitor]
True Adam, after looking for the app, there is a high tendency of behavior change on most of the apps. We might end up selecting a few whom we can track phone usage and avoid affect the  whole sample.

**Comment by lauradereynal** [comment]
@adamlofting what do you suggest as a next step here? 
Should we try some options ? Should we choose one now ? 

We should make that decision by the 14th of January if possible, so that we can train / practise during the bootcamp. What do you think ?

**Comment by DuncanGW** [comment]
Option to capture Browser History : [https://play.google.com/store/apps/details?id=com.smart.browserhistory&hl=en]

**Comment by adamlofting** [comment]
Also this app usage tracker could be useful (it has an export to CSV function) so wouldn't take up much time during the interview process: https://play.google.com/store/apps/details?id=com.agrvaibhav.AppUsageTracking&hl=en

**Comment by lauradereynal** [comment]
I believe this can be closed. 
Re-open if im wrong.

**Comment by Amuti** [comment]
Hey guys I found a great app that can do this ,

App Usage tracker
[https://play.google.com/store/apps/details?id=com.agrvaibhav.AppUsageTracking&hl=en](url)

It basically track how much time the user is spending on any type of app on the phone; and whether the user has installed a new app

Let me know what you guys think

**Comment by JoashMango** [comment]
Oh this is okay but we had closed up this as we settled for another app

**Comment by Amuti** [comment]
My bad! Thanks @JoashMango
