### ISSUE TITLE
Implement Suggested Topic Flow

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#201]
See [wireframes](https://dl.dropboxusercontent.com/u/109902/DSO/dso-app-wireframes.pdf) >> Suggested Topic UX

Detect problem -> suggest something on the home screen of the app

![screenshot 2016-06-02 11 23 40](https://cloud.githubusercontent.com/assets/403231/15740275/7e03e61e-28b4-11e6-9743-5fd7aed1c4e4.png)

**Comment by brianmwadime** [comment]
@secretrobotron @alanmoo this functionality can be viewed on the latest release at [Mozilla DSO android app](https://github.com/iHub/Mozilla-DSO-Quiz-Application/releases) 
missing the icon for suggested topics though.

**Comment by secretrobotron** [comment]
👍 awesome. How do I simulate this?

**Comment by secretrobotron** [comment]
(especially in the android emulator)
