### ISSUE TITLE
Set up Google Analytics to collect information about what users click on

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#208]
Need to collection information about what users are doing with the app. Can use Google Analytics if possible. Just need to be able to track where problems arise and which things people want to know about most.

**Must** work offline because most people won't have a persistent data connection.

**Comment by brianmwadime** [comment]
@secretrobotron please provide account to link to.

**Comment by brianmwadime** [comment]
Also do we have a google play account?

**Comment by secretrobotron** [comment]
@brianmwadime do you have a personal account you can use during development? I can find a more permanent one we can use for the project.

**Comment by secretrobotron** [comment]
> Also do we have a google play account?

Do we need a Google Play account to develop the app? Or are you trying to put it on Google Play?

**Comment by brianmwadime** [comment]
For google play distribution later on that is. For now if there's an account we can link to for the statistics collection bit. Putting this down for permanency.

**Comment by brianmwadime** [comment]
@secretrobotron which email will we use to collect the analytics with?

**Comment by secretrobotron** [comment]
@brianmwadime finding an answer to that problem presently. Emails flying. ✉️ ✈️

**Comment by brianmwadime** [comment]
@secretrobotron great!

**Comment by secretrobotron** [comment]
Wrote a super-simple analytics gathering system instead. Will gather from participants phones at @dobbz and @DuncanGW's advice.
