### ISSUE TITLE
Create January bootcamp agenda and description to share

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#21]
- [ ] solidify agenda/timeline
- [ ] write description
- [ ] share with volunteers and DDD researchers
#### Aspects of Agenda
- Design challenge for software prototypes
- Design challenge for curriculum

**Comment by secretrobotron** [comment]
cc @LauraReynal @JoashMango @DuncanGW

**Comment by lauradereynal** [comment]
agenda v1 is done 
description is written
