### ISSUE TITLE
Investigate text-to-speech capabilities to read tutorials to users

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#212]
To assuage language/literacy problems in tutorials, it may be useful to have tutorials read to the user by the phone's robotic voice.

I'm not sure on what devices/OS's this is possible. Maybe @dobbz, @allankimata, @icarius06 @TheBonface have an idea?

/cc @alanmoo @brianmwadime This is firmly low-priority.

**Comment by TheBonface** [comment]
the problem will arise when some of the signs or symbols are translated to sheng , the pronunciation by the robot won't bring the exact meaning out.  'i stand corrected though'

**Comment by secretrobotron** [comment]
Unfortunately, couldn't fully explore this. Wrote about it on the Jisort release blog post: https://mozilla-foundation-research.herokuapp.com/dso-software-prototyping-update-jisort/
