### ISSUE TITLE
Develop follow-up plan for app installation

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#213]
Discussion forked from [@dobbz's comment](https://github.com/MozillaFoundation/digital-skills-observatory/issues/178#issuecomment-221724196) in #178:

> Do we want/need push updates in case we add new features to the app it can prompt the user to update?

We should figure out
- if the app will be updated at all
- with what and why
- if the app will eventually be tied to the play store to be updated
- if not, then how?

cc @dobbz

**Comment by dobbz** [comment]
The app can be updated with new content, bug fixes, performance improvements etc.

Play Store is the easiest but not everyone has access to it. (some in the field didn't have an email address or internet was so slow we couldn't download a 1mb file). 
We may need to install manually but that means playstore won't update the app(at least google officially says it won't).

Another method is hosting the app ourselves and signing it. Then the app can periodically check for an updated version and update itself.

**Comment by secretrobotron** [comment]
Let's re-evaluate this after we get some feedback at the intervention.

**Comment by secretrobotron** [comment]
@DuncanGW executed a backup plan.
