### ISSUE TITLE
Launching Jisort should bring up the home screen

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#220]
Clicking on the app icon should launch the home screen. Currently, it places the floating helper on the screen (which it should also still do).

Thoughts, @brianmwadime ?

For #215.

**Comment by mdeche** [comment]
I actually agree with @secretrobotron, @brianmwadime. I had the same problem figuring out whether the app had opened then realised I need to click on the floating icon. We can add it to the backlog

**Comment by brianmwadime** [comment]
I think this was fixed Please confirm @secretrobotron or @mdeche .

**Comment by secretrobotron** [comment]
Yep! Fixed. Thanks @brianmwadime.
