### ISSUE TITLE
Extract home screen icons for Jisort

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#221]
@brianmwadime needs the home screen icons to put in Jisort from @flukeout's PDF.

@flukeout, are you able to put them in a google drive folder or something?

**Comment by secretrobotron** [comment]
Here are a bunch of the icons: https://drive.google.com/open?id=0B-7F6kqkuFwdeHZyeHRILVVTdGc

![dso-app-icons](https://cloud.githubusercontent.com/assets/403231/16201568/ec8d4d92-3709-11e6-8d42-84a8c6f5f227.png)

Let me know which other ones you need!

**Comment by secretrobotron** [comment]
@brianmwadime do you need any others?

**Comment by secretrobotron** [comment]
@brianmwadime also, lmk if you need these as SVGs or JPGs or anything else.

**Comment by secretrobotron** [comment]
Also worth noting that the SD card symbol in material design is different: https://design.google.com/icons/#ic_sd_card

**Comment by secretrobotron** [comment]
And the bluetooth one there is probably more accurate: https://design.google.com/icons/#ic_bluetooth

**Comment by brianmwadime** [comment]
@secretrobotron cool. Can they be split up into individual icons? :)

**Comment by brianmwadime** [comment]
All of them.

**Comment by secretrobotron** [comment]
@brianmwadime yeah, definitely. Specific size or format? PNG/JPG?

**Comment by brianmwadime** [comment]
@secretrobotron png (transparent)

**Comment by secretrobotron** [comment]
https://drive.google.com/open?id=0B-7F6kqkuFwdVnNPY2k5UHdKaVE

@brianmwadime ^^
Let me know if you need more.
