### ISSUE TITLE
Bootcamp 2 logitistics 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#222]
To do list for Bootcamp 2 
- Departure: June 30th 
- Return: July 3rd 
- Location: Malindi

Todo 
- [x] book planes for KIS team. Assigned to @LauraReynal
- [x] book van for KIS team. Assigned to @DuncanGW 
- [x] book plane for NBO team. Assigned to @LauraReynal
- [x] book van for Mombasa team. Assigned to @DuncanGW 
- [x] book venue for everyone. Assigned to @DuncanGW 
- [x] book everything for DDD researchers. Assigned to @DuncanGW / @JoashMango 
- [x] Prepare agenda and content of the bootcamp. Everyone

**Comment by lauradereynal** [comment]
@DuncanGW 
@JoashMango Let me know if this seems okay for the to-do 
I tried to assign tasks to each of us

**Comment by JoashMango** [comment]
This is quite okay for us.

Thanks

**Comment by lauradereynal** [comment]
All the planes are booked for everyone. 
@DuncanGW let us know how things are doing and if you need any help

**Comment by DuncanGW** [comment]
@LauraReynal That great, we are finalizing on on flights on our side. I am working also on the vehicle hires - transport. In case of anything from our side I will let you know.

**Comment by lauradereynal** [comment]
Everything has been done !
