### ISSUE TITLE
Remove tutorial quizzes from Jisort

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#225]
Having a Quiz for each tutorial is redundant. We'll just stick with the tutorial content and not implement quizzes.

**Comment by brianmwadime** [comment]
@secretrobotron  This will be returned on the next iteration?

**Comment by secretrobotron** [comment]
I'm not exactly sure when the _next iteration_ will be, so let's say no for now. If we do need the code later though, we can dig it out of git, right?

**Comment by brianmwadime** [comment]
Yes, we can.

**Comment by lauradereynal** [comment]
As far as I can tell, this is done. Let me know if need to re-open.
