### ISSUE TITLE
Implement redesigned UI for Jisort

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#227]
Here is a proper design cleanup of the UI for Jisort.

<img width="1174" alt="image" src="https://cloud.githubusercontent.com/assets/403231/16149112/49aeeb42-3486-11e6-9ca9-005811e53f13.png">

This applies to:
- [ ] Home screen
- [ ] Tutorial screen
- [ ] Icon quiz screen

@brianmwadime **please** let me know which parts of this are difficult or particularly time consuming. From my perspective, it doesn't look like there is too much complexity, but do let me know if anything seems scary.

@flukeout I noticed that the icon quiz screen is missing, but the color scheme is probably the same. Any pointers?

**Comment by brianmwadime** [comment]
@secretrobotron not particularly scary at all. Dashboard looks slimmer. :-)

**Comment by TheBonface** [comment]
I don't know if it's too early to talk about user experience;  the app frequently notifies me about my WiFi connection being on even if I have active WiFi connection.  Can it be made such  that it only notifies when I  turn on the WiFi  or the timing between rate of notifications be increased.

**Comment by brianmwadime** [comment]
@TheBonface Please raise them up. It's all useful feedback. You can also create an issue of them as well for easier tracking and QA'ing once implemented.

**Comment by brianmwadime** [comment]
@secretrobotron @flukeout do we also have the new color scheme?

**Comment by secretrobotron** [comment]
@TheBonface can you file that as a new issue, actually? You can reference #215 to keep track of QA items.

**Comment by secretrobotron** [comment]
@brianmwadime, here are the colors as per Digital Color Meter in RGB:
- Background: `53, 53, 53`
- Home screen icons: `228, 188, 77`
- Toggle button primary color: `105, 165, 227`
- Toggle button secondary color: `73, 97, 123`
- Primary text color: `255, 255, 255`
- Secondary text color: `220, 220, 220`
- Tutorial back/next button enabled background color: `106, 166, 229`
- Tutorial back/next button enabled foreground color: `255, 255, 255`
- Tutorial back/next button disabled background color: `68, 86, 106`
- Tutorial back/next button disabled foreground color: `112, 112, 112`

For those enabled/disabled tutorial buttons, it looks like there's an opacity shift of `0.439` if that's easier than using new RGB values.

@flukeout if you're able to check these, much appreciated.

**Comment by brianmwadime** [comment]
@secretrobotron @flukeout does this new home screen remove the suggested cards at the top that were on the old home screen?

**Comment by secretrobotron** [comment]
Sorry @brianmwadime. Let's keep the suggestion cards. We're also missing the button for the icon quiz. I'll mock something up.

**Comment by brianmwadime** [comment]
@secretrobotron okay. Was wondering about that.

**Comment by secretrobotron** [comment]
![home screen mockup](https://cloud.githubusercontent.com/assets/403231/16230129/e6659fce-37b7-11e6-94a4-895bdad776f4.png)

@brianmwadime a home screen with a suggestion card ^^

**Comment by secretrobotron** [comment]
@brianmwadime and light bulb icon added to icons folder (with the others)

**Comment by brianmwadime** [comment]
@secretrobotron is the blue color on "Lean More" the selected color or is it blue?

**Comment by secretrobotron** [comment]
> is the blue color on "Lean More" the selected color or is it blue?

It's blue, to draw attention. I used the same blue as the toggle switch.

**Comment by brianmwadime** [comment]
@secretrobotron I think we have this task locked down. No? :)

**Comment by secretrobotron** [comment]
Indeed!
