### ISSUE TITLE
Identify UX (User Experience) problems 

### ISSUE THREAD

**Issue by TheBonface** [MozillaFoundation/digital-skills-observatory#228]
Let's post User experience issues here for the software prototypes Prototype 1

**Comment by secretrobotron** [comment]
Contributes to #215.

**Comment by secretrobotron** [comment]
@TheBonface do you want to bring this up on the software/community call?

**Comment by TheBonface** [comment]
@secretrobotron  yes sure ,maybe for those who have installed the prototype 1 can share  their user experiences
