### ISSUE TITLE
Floating helper icon has a square background

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#229]
Behind the circle icon is a square:

![screenshot jun 20 2016 17 15 04](https://cloud.githubusercontent.com/assets/403231/16201804/e5bb542c-370a-11e6-9999-bfb51ff1b3ba.png)

Should it (can it) be transparent? Does it need to be there at all?

**Comment by brianmwadime** [comment]
Shouldn't be there.
