### ISSUE TITLE
Place content in Jisort

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#230]
The content from #191 is pretty close to done. Let's put it in the app.

https://docs.google.com/document/d/1PMK72_jRepGkhtKoK1wHv4NPwnBhub9yjK7pIwVzeTM

**Comment by secretrobotron** [comment]
@brianmwadime let me know if you need help taking apart any of the imagery/titles/text/gifs/etc. There's a lot in there, so I'm happy to guide you through the confusing bits.

**Comment by brianmwadime** [comment]
@secretrobotron @DuncanGW @LauraReynal  the **json** structure for the tutorial content should will match this structure moving forward.

```
{
    "tutorials": [
        {
            "tag": "wifi",
            "header": "Connecting to Wi-Fi",
            "photoUrl": "url",
            "steps": [
                {
                    "title": "Finding Names and Passwords",
                    "gifUrl": "url",
                    "description": "To connect to a Wi-Fi hotspot, you will need the name of the hotspot and, in some cases, its password. If you are in a business, cafe, or other public space, you can usually ask the owner of the hotspot for this information. Some places charge a small fee for using their Wi-Fi."
                },
                {
                    "title": "Turning on Wi-Fi",
                    "gifUrl": "url",
                    "description": "On most Android phones, you can begin looking for Wi-Fi by swiping down the Title Bar at the top of the screen and tapping  the Wi-Fi icon. If you are close to a Wi-Fi network you have joined in the past, your phone will try to connect to it automatically."
                }
            ]
        }
    ]
}
```

**Comment by brianmwadime** [comment]
@secretrobotron can I get a link to the folder containing the gifs? I'm unable to extract from the google doc :(

**Comment by secretrobotron** [comment]
No probalo: https://drive.google.com/open?id=0B-7F6kqkuFwdbFNKYlc0bGV6bE0

LMK if something is missing. I think it's all there though.

**Comment by secretrobotron** [comment]
@brianmwadime do you have some code that uses this structure already? Even without the gifs in place, it'll be good to see it in the app. I can even edit the json myself and send you pull requests.

**Comment by dobbz** [comment]
@secretrobotron the gifs and icons seem to be android 5+. However majority
of the audience are on android 4. I'm abit worried it may confuse those
with earlier versions of android.

**Comment by secretrobotron** [comment]
@dobbz yeah, that's important.
- gifs: for things like Wi-Fi, i think it's pretty similar. any specific gifs that worry you though? i can create a new emu on my machine and record some new ones.
- icons: we're using material design to avoid taking a billion screenshots, but maybe we don't have a better option.

**Comment by brianmwadime** [comment]
@secretrobotron working on that. Should have an **apk** sample up today.

**Comment by secretrobotron** [comment]
Any updates, @brianmwadime ?

**Comment by brianmwadime** [comment]
@secretrobotron we're able to bootstrap the data from the [bootstrap_data.json](Mozilla-DSO-Quiz-Application/app/src/main/res/raw/bootstrap_data.json) That's where the tutorial content will be housed.

**Comment by brianmwadime** [comment]
Hey @secretrobotron , @DuncanGW , @TheBonface , @LauraReynal  first **MVP** with some of the wifi content in place. [download me! v1.0.0](https://github.com/iHub/Mozilla-DSO-Quiz-Application/releases/tag/v1.0.0)

Adding the rest of the content and will issue an update later in the date.

**Comment by festolangat** [comment]
Thats good job me👆

**Comment by secretrobotron** [comment]
Well-underway and almost done.
