### ISSUE TITLE
Special communication mission during the bootcamp

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#233]
**Goal**: Take advantage of the fact that we are in the bootcamp to do a special community and storytelling project. 
**Leaders**: @nmarita @chanditome 
**Project members:** @shey02 @FauziaIsmail 

**Mission**: produce a beautiful community blog post based on the different personalities and stories that you see here. 

A few ideas can include to: 
- Ask everyone a few questions about themselves and the project - Questions to be drafted. 
- Take everyone's picture 
- Collect interesting anecdotes and stories from research participants. 
- Publish them online, either in a blog post or on a community story page. 

Linked with previous ideas #66

**Comment by lauradereynal** [comment]
I think @shey02 has led this work with brio 😄 
Can you share what you have so far in this ticket ?

**Comment by shey02** [comment]
I have just shared the google form with you guyz :)

On Tue, Jul 5, 2016 at 6:00 PM, Laura de Reynal notifications@github.com
wrote:

> I think @shey02 https://github.com/shey02 has led this work with brio 😄
> Can you share what you have so far in this ticket ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/233#issuecomment-230504132,
> or mute the thread
> https://github.com/notifications/unsubscribe/AP9VraBWXx_g1oDd13ZySuSG-fjlFckfks5qSnGMgaJpZM4JB5uE
> .

## 

Shehnaz Abubakar K.
Kenyatta University, BSCIT.
Intern,Techbiz Limited.
Volunteering Committee,MombasaTech.

**Comment by sangson07** [comment]
@Chad @Laura @Shay02 @Bobby @Boniface i think what chad had suggested
earlier we use scale of 1-5 because this gives the respondents more
room to express themselves more

On 7/5/16, shey02 notifications@github.com wrote:

> I have just shared the google form with you guyz :)
> 
> On Tue, Jul 5, 2016 at 6:00 PM, Laura de Reynal notifications@github.com
> wrote:
> 
> > I think @shey02 https://github.com/shey02 has led this work with brio
> > 😄
> > Can you share what you have so far in this ticket ?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/MozillaFoundation/digital-skills-observatory/issues/233#issuecomment-230504132,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AP9VraBWXx_g1oDd13ZySuSG-fjlFckfks5qSnGMgaJpZM4JB5uE
> > .
> 
> ## 
> 
> Shehnaz Abubakar K.
> Kenyatta University, BSCIT.
> Intern,Techbiz Limited.
> Volunteering Committee,MombasaTech.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/233#issuecomment-230550217

## 

Edwin Sang +254711842295

**Comment by lauradereynal** [comment]
Thanks @sangson07 this is actually on a different topic :D 

@shey02 thanks for sharing. I'll have a look soon and we can decide how we move forward with this super cool project.
