### ISSUE TITLE
Jisort Feedback form 

### ISSUE THREAD

**Issue by TheBonface** [MozillaFoundation/digital-skills-observatory#235]
Hey guys this the feedback form we came up with @chadsansing  and others what do u think ?

https://docs.google.com/forms/d/16NNwUbLtDwGA95O8iYCJLuvu5VHupJM8uVjlIZAsKRw/viewform

**Comment by chadsansing** [comment]
Looks good to me. Is there any advantage do using a 5-point scale over Agree/Disagree? For example, 

"I though the tutorials were clear" 1 - Not clear at all 2 - Mostly unclear 3 - Unsure/No opinion 4 - Mostly Clear 5 - Always clear

**Comment by TheBonface** [comment]
@chadsansing The argument was based upon some respondent's   selecting either 2 when they actually meant 1 or not knowing the clear distinction between the scales. so we opted to a more direct approach either agree or not agree ; but again how about we use them interchangeably @xelawafs @secretrobotron

**Comment by lauradereynal** [comment]
Hey @TheBonface @secretrobotron what do we want to do with this form now ?
