### ISSUE TITLE
Prepare and ship intervention 4 curriculum 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#238]
Goal: Finish the preparation of the intervention 4 curriculum 
Timeline: Curriculum finished by the end of July,

Working document is here: 
https://docs.google.com/document/d/1YLyWA2fhuBG0pckhfEjr4eUzXEN1682VVVM14ee8A9M/edit# 

Leads: @zuma1 @nmarita @denomain @FauziaIsmail @chanditome 
with help from everyone and support from @chadsansing 
cc @secretrobotron and @DuncanGW and @JoashMango for FYI if you want to jump in some curriculum

**Comment by lauradereynal** [comment]
ok. so. I did a first pass tonight, and I think it's ready for @chadsansing to jump in and help flesh out the rest. A bunch of actiivities have been layed out but are missing some actual content and meet. 
For example, we have good learning objectives for aciivity 1- how to search online, but we don't have any activities to do with people. 
@chadsansing feel free to start the magic, and we can all follow along and help.

**Comment by chadsansing** [comment]
@LauraReynal, there are some spots where you have made direct asks to community members to add more content. Has this happened, or should I wait for community contributions before I hazard a few ideas?

**Comment by lauradereynal** [comment]
@chadsansing you can go ahead and start playing with the curriculum. People can contribute with you 😄

**Comment by secretrobotron** [comment]
https://mozilla.github.io/curriculum-final/kenya-dso-interventions/intervention-four.html#overview
