### ISSUE TITLE
Prepare logistics for intervention 4 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#239]

**Comment by secretrobotron** [comment]
@zuma1 @denomain and @ChristabelAchieng have been hard at work. So far, we have a couple of planning documents:
- [Mombasa](https://docs.google.com/document/d/1-Yz22jg-Cqaoi_j14Td7JevUpy08aOXHaWZSF2r3kTE/edit?ts=57a992b6)
- [Nairobi](https://www.google.com/url?q=https://docs.google.com/document/d/1MEVQ6rRxsyQD2Mkc9lOoBY-OzbldJhCcN3DIE5-w2xg/edit%23&sa=D&ust=1470737019093000&usg=AFQjCNH3u-Uu1kZ9el5d-gytrpWepTmaqw)

**Comment by secretrobotron** [comment]
Jisort analytics instructions and other information are available on the wiki: https://github.com/MozillaFoundation/digital-skills-observatory/wiki/Jisort-Analytics

**Comment by ChristabelAchieng** [comment]
Kisumu team have successfully had two dry runs for the upcoming intervention and so we have fairy familiarized with the curriculum. Whether or not this will impact the intervention positively is still a question and is left to be seen. It was great fun and I thank all who made it happen.

The Nairobi team already completed their intervention and we were hoping to get insights from the team on the same. Perhaps things that came up that can be addressed by the other teams (regions).

**Comment by JoashMango** [comment]
Hi Christabel,

Am coming to Kisumu tomorrow hope we will meet you guys we discuss some
insights based on Nairobi intervention.

**Comment by secretrobotron** [comment]
👍 thanks @ChristabelAchieng ! We'll also be able to share on the community call on Thursday.

One thing I want to make sure you saw was the [Jisort Analytics](https://github.com/MozillaFoundation/digital-skills-observatory/wiki/Jisort-Analytics) instructions above. If possible, at the end of the intervention, we should try to get analytics files from the participants' phones.

🐻 🐻 🐻 🐻 🐻 🐻

**Comment by ChristabelAchieng** [comment]
@JoashMango looking forward to seeing you guys tomorrow. I'll be able to meet up with you briefly in the evening after work.
@secretrobotron I did see that. I think we could add that into the Q&A session as you had suggested.
