### ISSUE TITLE
Write a short blog post about the digital skills cards 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#244]
Tell a story about the digital skills card and talk about the results of the activity.
@secretrobotron the deck we used is here https://docs.google.com/presentation/d/1NishZUsQKLSMTx0hPTN_1A-8Dl6FdxrrJ5m0ZRieWUI/edit#slide=id.g14a825228e_0_20

**Comment by secretrobotron** [comment]
I think we'll need to do this as a part of #166.

**Comment by secretrobotron** [comment]
I think we can skip this.
