### ISSUE TITLE
Publish Curriculum 1 and 2

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#247]
- [x] Review http://chadsansing.github.io/curriculum-testing/kenya-dso-interventions/01-intervention-one.html#overview
- [x] Review http://chadsansing.github.io/curriculum-testing/kenya-dso-interventions/02-intervention-two.html#overview
- [ ] Move both to Mozilla-owned repo
- [x] Add to DSO website
- [ ] Write blog

**Comment by chadsansing** [comment]
Not sure how to do steps 3-4 or if you want me to foxfood my own content, @secretrobotron - discuss after PTO?

**Comment by secretrobotron** [comment]
@chadsansing yeah, definitely not a rush.

Is there a repo you regularly use now to store curriculum? Can it go there?

I can add to the DSO website. Would just be a link to the right source.

**Comment by chadsansing** [comment]
Most of what I've done lives on my repo - we have yet to migrate much of anything, though this is on @hannahkane and @ldecoursy's radars. Team-up with them re: migration?

**Comment by secretrobotron** [comment]
🆗 ! thanks @chadsansing

**Comment by hannahkane** [comment]
cc @cadecairos to advise on the migration issue. Quick background: we have a lot of official Mozilla curriculum living in Chad's repo. I'm wondering about the process and effort involved in moving it to a MozillaFoundation-owned repo. Chris - can you help me figure out what the steps would be to do that?

**Comment by secretrobotron** [comment]
👍 awesome. Thanks @hannahkane. I think the github procedure is pretty straightforward. We should just be careful that too many URLs don't change (and, I think @cadecairos can simply fork if necessary). However, I'm not sure that 100% of the stuff in @chadsansing's `curriculum-testing` repo is all "production-ready".

**Comment by cadecairos** [comment]
> I'm wondering about the process and effort involved in moving it to a MozillaFoundation-owned repo. Chris - can you help me figure out what the steps would be to do that?

If we [transfer ownership](https://help.github.com/articles/about-repository-transfers/) to the MozillaFoundation org, it should automatically redirect everything except for GitHub pages.

We may have to modify the gh-pages versions in @chadsansing's repo so that they use JavaScript to redirect to the new home for the content.

**Comment by chadsansing** [comment]
I can also make individual repos for individual projects going forward (and/or to facilitate this work on past content). The curriculum-testing repo is a catch-all leftover from my early days of learning GitHub.

**Comment by lauradereynal** [comment]
I filled a bunch of tickets [here](https://github.com/chadsansing/curriculum-testing/issues) for the first curriculum. Aside from a few remaining information architecture questions it's good to go for me.

**Comment by lauradereynal** [comment]
ok, I checked both curriculum and they are super awesome. Thanks for putting them online @chadsansing

**Comment by chadsansing** [comment]
The second needs the layout treatment if we're happy with how it looks in the first. Can do that shortly,

**Comment by chadsansing** [comment]
Blog for review: https://docs.google.com/document/d/1XxLbskLO9swy6mcS8_UAdV1EX3eqLd2p9xG6iBm5KVA/edit

@secretrobotron, @LauraReynal, @KevZawacki
@chadsansing can i have access to the blog

**Comment by lauradereynal** [comment]
Wow this is an awesome blog post @chadsansing thanks for sending it. 
I have read it with delight, and added a few comments here and there, but nothing too big. 

Do you have a personal blog where you will publish? 
Can we cross-post on the research blog and the DSO website?

**Comment by chadsansing** [comment]
@LauraReynal - I would offer this to @KevZawacki first for the new Medium publication and then open it for cross-posting elsewhere.

**Comment by KevZawacki** [comment]
Echoing @LauraReynal -- this is an excellent read! Great writing and storytelling. Excited to post it on medium.com/read-write-participate

@chadsansing, thoughts on a headline and sub-headline? The current headlines up [on Medium](https://medium.com/read-write-participate) might serve as inspiration. 

For photos, I think any of [Laura's snapshots](https://www.flickr.com/photos/laura_nk/albums/72157663345939379) would be a good fit. Perhaps [this one](https://www.flickr.com/photos/laura_nk/25934556394/in/album-72157663345939379/)?

**Comment by secretrobotron** [comment]
👍 great post, @chadsansing. Let me know when you want it cross-posted on the research blog.

**Comment by lauradereynal** [comment]
These ones are also good to speak about global collaboration https://www.flickr.com/photos/laura_nk/28147344990/in/album-72157663345939379/
https://www.flickr.com/photos/laura_nk/27814209103/in/album-72157663345939379/ 
or even this one https://www.flickr.com/photos/laura_nk/28430295755/in/album-72157663345939379/ 
and this one is a fun team picture https://www.flickr.com/photos/laura_nk/26102335524/in/album-72157663345939379/
