### ISSUE TITLE
Blog post #1 - Project introduction 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#25]
Goal: introduce DSO 
Owner: @secretrobotron 

When? As soon as our Website is online. We can prepare the text now. We probably have things written in different places and can publish the slidedeck.

**Comment by lauradereynal** [comment]
pasting here the pad with our coms notes https://titanpad.com/DSO

**Comment by secretrobotron** [comment]
Linking to overal comms plan: #7

**Comment by secretrobotron** [comment]
Almost done here. Just fixing up a draft.

**Comment by secretrobotron** [comment]
Done. Incorporates much of #26 as well.
