### ISSUE TITLE
Blog: What is Open Research

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#250]
To back up other publications, should write a blog about the theory, models, and examples of what open research is and why it's beneficial.

Can use profiles of several community members to illustrate, and can be worked into final report.

@LauraReynal thoughts?

**Comment by lauradereynal** [comment]
Love the idea. Let's aim for August publication ?

**Comment by secretrobotron** [comment]
Yes. Ideally, we crowd-source the answer.

**Comment by secretrobotron** [comment]
@JoashMango you had some ideas you wanted to add here, right?
