### ISSUE TITLE
Create and share the reporting guide 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#251]
For intervention 4, we need to finish and share out the reporting guide.

**Comment by lauradereynal** [comment]
cc @denomain and @secretrobotron

**Comment by AI-DennisNdegwa** [comment]
Can we have it an editable document somewhere?

**Comment by lauradereynal** [comment]
I can make it a survey, and give you edit rights. Works for you ?

**Comment by AI-DennisNdegwa** [comment]
Yeah. That sounds great.

**Comment by secretrobotron** [comment]
Done https://docs.google.com/a/mozillafoundation.org/forms/d/1oOlg0RqbuBPGcO_jNstmB5MH9rVqNIU5qgmFbBuOQWM
