### ISSUE TITLE
DDD submits mid-study report 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#253]
DDD submits mid-study report with early analysis including gender lense and treatment lense. 
Includes headlines of qualitative work and headline of quantitative work.

Lead: @JoashMango 
Consulted: @DuncanGW @secretrobotron @lauraReynal

**Comment by lauradereynal** [comment]
The report has been submitted and we need to finish reviewing and reading it.

**Comment by lauradereynal** [comment]
I suggest we use this ticket to list follow up questions, and we can cover them in a meeting soon: 
1. What is the status of the Android data collection app? It is mentioned in the report, but no data about it.
2. How can we explain the different DFS usages such as savings in Mpesa, KCB, airtel money and Equitel. I wonder if this is striking because of the short period of time between interview 2 and 3. Maybe with one year overview, it will appear less striking. Is it a static question in each questionnaire?

**Comment by lauradereynal** [comment]
1. Im very curious about the fact that women with children save more, because they need to prepare. How does society deal with that? The father does not help ? Do we have data to help understand this?

**Comment by Uwanja** [comment]
Where is a link to the report?

**Comment by secretrobotron** [comment]
@Uwanja we're right in the middle of reformatting it for easier consumption. Will drop you a link when it's ready.

**Comment by lauradereynal** [comment]
@secretrobotron @JoashMango What do you suggest as a next step for this one?

**Comment by lauradereynal** [comment]
I think this is done and has recently been edited again. 

Thanks for all the hard work @JoashMango @DuncanGW
