### ISSUE TITLE
Design phone survey for Jisort!

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#254]
@secretrobotron @DuncanGW @JoashMango 
- [ ] Decide how we measure and collect the feedback from Jisort!
- [ ] Design the survey, or questionnaire, or questions or focus group

**Comment by JoashMango** [comment]
@LauraReynal @secretrobotron 
I do not support the FGD since the findings are subjective and based on the majority. We will not be able to collect key individual insights that might be importance to the project. I would propose key individual interviews

**Comment by secretrobotron** [comment]
Some questions from the [Jisort Launch Plan](https://docs.google.com/document/d/15SCeoLbm88i5gm9SvpFtcBn1JMPLI6sbJ1Jh1lDO7ZI/edit#):
- Is Jisort easy to use? Which parts are difficult? Which parts are useful?
- What’s missing from Jisort? What else do you want to learn?
- Is there too much text? Is it too complicated?
- Has anybody else used Jisort? Have you shown it to anyone else? Has it helped you answer someone else’s questions?
- Has Jisort helped you use discover new applications? 
- If yes, which ones? 
- Has it helped you discover apps or websites that help you save money, send or receive money, get loans, etc?
- How could we make Jisort more fun ? How could we make it aligned with what is trendy in Kenya these days?
- Do you think that Jisort is interesting for men and women in the same way ? or for one gender more than the other?
- If Jisort could teach you about using/saving money, what would you add to it? 
- Do people need “Jisort for money”?
- Do you feel more confident about using your smartphone with Jisort? Do you feel more confident using financial apps/websites now that you’ve used Jisort?
- If you wanted to share Jisort’s knowledge with a friend, how would you do it?
- If you wanted to share Jisort with a friend, how would you do it?
- Where might you find more apps like Jisort?
- Jisort helps you understand your smartphone. Could it help you understand how to use/save your money? What else could an app help you understand?
- Do you think your mom, sister, or girlfriend would like Jisort? What about your brother, dad, or boyfriend? What is the difference?
- Would boys want there to be different information in Jisort than girls?
- Would boys share Jisort more than girls?
- Would boys use Jisort differently than girls?
- Are you more likely to share information from Jisort, or show it to someone of the same gender?
- Did Jisort inspire you to look for more apps, or find more information? How? What information? What are some examples?
- Did Jisort inspire you to try to use your phone to manage your money?
- To whom would you have gone for help before using Jisort?
- Will you still go to them for help, or would you prefer Jisort?
- What would you change about the language in Jisort to make it easier, more useful or more enjoyable?
- Would you prefer that Jisort include more Sheng? More emoticons? More imagery? Where?

**Comment by secretrobotron** [comment]
@JoashMango @DuncanGW what format is most useful for doing a followup phone interview? Shall we pick a specific week to do it?

**Comment by JoashMango** [comment]
For phone survey we need to dedicate a specific week to do that

**Comment by secretrobotron** [comment]
This will be incorporated into Interview 5.
