### ISSUE TITLE
[blog] Bootcamp summary 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#26]
Goal: Document and publish accomplishements from the bootcamp and our first trip
Lead: @secretrobotron 
with the team

**Comment by secretrobotron** [comment]
@LauraReynal covered the basics in #25. We can write one that goes deep on the list of topics though.

**Comment by lauradereynal** [comment]
Yes let's revise the list of blog post we want to write

**Comment by secretrobotron** [comment]
I just meant a list of topics to cover for this blog post (e.g. the stuff in our debrief today).

**Comment by lauradereynal** [comment]
yes. sorry im tired

**Comment by secretrobotron** [comment]
:sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping::sleeping:

**Comment by secretrobotron** [comment]
@LauraReynal give it a read? I think it's ready to go out.

**Comment by secretrobotron** [comment]
https://docs.google.com/document/d/1XJWHDKbwC5YBTWgML8ovaQ_3ofQUwtrKfZ7RHD3RUq0

**Comment by secretrobotron** [comment]
Note: include survey results?

**Comment by secretrobotron** [comment]
[Published!](https://mozilla-foundation-research.herokuapp.com/what-we-learned-with-the-dso-community-bootcamp/)
