### ISSUE TITLE
Buy a phone and a SIM card

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#263]
@denomain @Josiahma1 @Uwanja and I chatted about which phone to buy. Looks like Samsung Galaxy J5 is the best, and it's about $150 USD in Kenya.

We also need a SIM card which we can fill up with data (principally for weekend use, since DDD's Wi-Fi can be used during weekdays).

**Need to purchase before September 27th so we can test [week 1 curriculum](https://github.com/MozillaFoundation/digital-skills-observatory/issues/262).**

**Comment by Uwanja** [comment]
Deadline for this should be September 27th and not October 27th. @secretrobotron

**Comment by secretrobotron** [comment]
Good catch, @Uwanja. Fixed 🔧 .
