### ISSUE TITLE
Write blog post about chat experiment week 1

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#268]
Let's put a blog post up on [mzl.la/research](mzl.la/research) with:
- Sterro's profile
- Impressions from the first week of interaction
- Plans for next week(s)

**Comment by secretrobotron** [comment]
Working document: https://docs.google.com/document/d/18yGy0uHGfB4CrsWAujGCXRN06uyH97LQnfe54yMknlQ

**Comment by secretrobotron** [comment]
https://mozilla-foundation-research.herokuapp.com/introducing-sterro-mjanja-dso-whatsapp-experiment-week-1/

**Comment by AI-DennisNdegwa** [comment]
Will just post my thoughts here to be included in any upcoming blogs on Chat Experiment.

**Comment by AI-DennisNdegwa** [comment]
Does the lack of internet connection affordability prevent users from trying new things OR does the lack of knowledge of utilizable internet and app features make users budget lower for data usage?
