### ISSUE TITLE
Update our website 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#269]
Update our website with the correct timeline and the most recent blog posts 
- [x] "current progress needs to be updated" 
- [x] Ken's profile could be highlighted 
- [x] Software 2 blog post could be highlighted too

**Comment by secretrobotron** [comment]
Bloop! Done. http://mozillafoundation.github.io/digital-skills-observatory/

@LauraReynal make sure blog posts have the "Digital Skills Observatory" tag, to benefit from some automation.
