### ISSUE TITLE
Sterros interview questions

### ISSUE THREAD

**Issue by Uwanja** [MozillaFoundation/digital-skills-observatory#277]
Pursuant to the Skype call two weeks ago I have started this issue to see if we can ship some questions to the interviewers as they go to the final interviews.
- Did you know that Sterro was 3 different people?
- What do you think of Sterros gender now that you spoke with him/her for the 6 weeks?
- Is there something that you found Sterro was not doing well?
-In a scale of 1-5 how would you rate how helpful Sterro was when he was still alive? (1 being least helpful)
- Some questions to compare Sterro vs physical interventions vs Jisort perhaps?

@Josiahma1 @denomain angalieni hii maneno

**Comment by AI-DennisNdegwa** [comment]
How would you gauge how much you learned from Sterro compared to how much you learned in the interventions?

**Comment by WinnieMakokha** [comment]
Q. Are there things you were comfortable in communicating with sterro as
opposed to face to face interventions?

Reason: During a session at MozFest(
https://app.mozillafestival.org/#_session-447) it became apparent from the
discussions that people, become comfortable with a 'bot' like sterro, when
they want to communicate personal issues, or if they are generally shy in
person and they want to get information.

 Regards,

Winnie Makokha

_Adopt the pace of nature, her secret is patience_

**Comment by secretrobotron** [comment]
cc @DuncanGW @JoashMango

**Comment by secretrobotron** [comment]
> people, become comfortable with a 'bot' like sterro, when they want to communicate personal issues, or if they are generally shy in person and they want to get information.

@WinnieMakokha that's a good insight! Did you learn anything else from that session?

**Comment by JoashMango** [comment]
I would like to get respondents opinion on the following
- Did you feel more comfortable communicating with sterro than face to face
  -In what areas did Sterro assist you most that you did not get in face to face
- What challenges did you think sterro did not assist you with

**Comment by secretrobotron** [comment]
👍 Thanks for these questions everyone. We worked them into Interview 6 today. Can't wait for the results 🛩 😄 🍄
