### ISSUE TITLE
SWAG 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#28]
Figure out what type of SWAG we bring to different bootcamps etc. 

@secretrobotron let's get the bags from Mozfest as a first start. 

What about the buttons you made for indoneisa?

**Comment by secretrobotron** [comment]
@LauraReynal I don't have any with me (I'm in London at the moment), but if we want to print some more on short notice, I have the design on my machine.

@Saallen what's available for us to take?

**Comment by Saallen** [comment]
I got you! Don't :sweat: 
Sole has some really nice T shirts for you, I have some team web buttons and I have some MozFest stuff too

**Comment by secretrobotron** [comment]
Thanks for the swag, @Saallen :).
