### ISSUE TITLE
Write Final Report- ALPHA 

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#280]
**IT IS TIME!!!!!!**

TOC or Executive summary
https://docs.google.com/document/d/1oe7LSWhrD2SHrfRuVVNT9GRk-xO9rd01d7ORncQcRc0/edit#heading=h.vctf810gfjq

**Comment by lauradereynal** [comment]
**Writing work**
- [x] Bobby finishes "Chapter 1" 
- [x] Laura reviews "Chapter 1"
- [x] Laura finishes "Chapter 2"
- [x] Bobby reviews "Chapter 2"
- [x] Laura writes a first pass on "Chapter 3"
- [x] Bobby takes a crack at Chapter 3
- [x] Bobby finalizes copy for Chapter 3 
- [x] Bobby finishes "The Digital Skills Observatory" section
- [x] Laura reviews "The Digital Skills Observatory" section
- [ ] edit the introduction with the economical framing 
- [x] Bobby does a pass on profiles 
- [x] Laura does a pass on profiles 
- [x] Bobby helps Luke finish infographics 
- [x]  Laura finalizes chapter 4 
- [x] Bobby does a pass on chapter 4 
- [x] acknowledgments and thanks 
- [x] conclusion 
- [x] Betting case study included 
- [ ]  Adoption case study 
- [ ]  Social media case study 
- [ ]  learning case study 
- [x] Digital Credit case study
- [ ] Laura does a pass on all sections and adds subtitles to make things easier to read
- [ ] do a pass with the dashboards and the report in // to see which ones we add 
- [ ] move some of the education method details to appendix 
- [ ] Community impact page with quotes 

**Check and clean:**
- [ ]  all the footnotes and links integrated 
- [x] Agree on titles capitalization and style - should they all be sentences when possible?
- [ ] all the comments left in the gdoc addressed 
- [ ] make sure we don't repeat ourselves 
- [ ] make sure we are sharp, short and clear 
- [ ] check that we have answered each research questions 
- [ ] clear all the paragraph styles 
- [ ] do a pass with the best quotes that we can add where it makes sense in the report 
- [x] do a pass on the mid-study report and check that we did not leave important information out 
- [ ] Make sure sections and titles are good and tell the right story

**Medias:**
- [ ] photos 
- [ ] map of Kenya 
- [ ] infographics with Luke
- [ ]  clickable links ! I don't know if that is possible  

**Data/Graphs**
- [ ] Make a better hourly graph for Sterro conversations based on averages

**Comment by secretrobotron** [comment]
- [ ] Bobby finishes "The Digital Skills Observatory" section
- [ ] Laura reviews "The Digital Skills Observatory" section
- [ ] Bobby finishes "Chapter 1" 
- [ ] Laura reviews "Chapter 1"
- [ ] Laura finishes "Chapter 2"
- [ ] Bobby reviews "Chapter 2"

**Comment by LauraReynal** [comment]
- [ ] make sure we don't repeat ourselves 
- [ ] make sure we are sharp, short and clear **# SSC**

**Comment by LauraReynal** [comment]
Medias:
- [ ] photos 
- [ ] map of Kenya 
- [ ] infographics 
- [ ]  clickable links ! I don't know if that is possible

**Comment by secretrobotron** [comment]
>  clickable links ! I don't know if that is possible

Maybe not! But still cool.

**Comment by LauraReynal** [comment]
I'd like to reference #1 as a nostalgic moment, over a year ago, we started this project. 
🚀 LET'S SHIP IT 🚀

**Comment by lauradereynal** [comment]
what do we put in the appendix? If anything

**Comment by secretrobotron** [comment]
- [ ] agree on title capitalization

**Comment by JoashMango** [comment]
In the Appendix, can we put the links to the questionnaires? @LauraReynal

**Comment by lauradereynal** [comment]
Good thinking @JoashMango we will see when we have a final draft this week.

**Comment by lauradereynal** [comment]
add key takeaways when necessary

**Comment by lauradereynal** [comment]
Why don't we send the DDD case studies to the community members for help?

**Comment by lauradereynal** [comment]
Maybe we should add a summary of all our research questions and an indication of where we cover the answers (eg. chapter 1, page 67 )

**Comment by secretrobotron** [comment]
> Maybe we should add a summary of all our research questions and an indication of where we cover the answers (eg. chapter 1, page 67 )

👍 
In an appendix?

**Comment by lauradereynal** [comment]
- [ ] Add more data about DFS usage amongst participants in chapter 1 
- [ ] add the graphs from the comprehensive analysis

**Comment by secretrobotron** [comment]
- [ ] Fix image links (put them in the images folder)

**Comment by secretrobotron** [comment]
From review with Dave:
- [ ] measuring internet health compared to other countries and individuals; is there a scorecard?
- [ ] make sure we connect internet health section to broader mozilla program
- [x] add profiles to chapter 1
- [x] "93% of people" in infographic fails to make the point
- [x] soften the gambling part. it's not the top reason, nor is it a good reason. contextualize the role gambling plays in adoption.
- [ ] make "why people bought smartphone" graph bigger and prettier
- [ ] add paragraph about how people don't want ot feel left out, and how they're left out in society; they don't want to feel left out in the digital world; people are vulnerable, have to fight everyday; they want to feel included, not left behind. they're already disconnected; product designers should be careful not to exacerbate the problem with the growing digital divide.
- [ ] if you can use whatsapp on your feature phone, why do people want to use it on a smartphone? experience on a featurephone isn't what people are seeking. no selfies, camera, images, videos, etc. the *can* use featurephones, but they're going to try to get smartphones anyway because of those features; *they don't wan to be left behind*; feature phones aren't really a choice—if you can avoid them, you will.
- [x] Re-generate top URLs list for gambling; show that people use the web primarily for betting
- [ ] contextualize why some women get into betting; what are their motivations? do they not want to be poor, or want to take part? something else?
- [ ] gambling is a concern for people in this line of work (e.g. foundations). people use mshwari to get loans for betting. it's a big deal; *people are looking for consumer protection solutions.*
- [x] add another profile beside "where there's a will there's a way" to illustrate the dark side of betting; e.g. Evan
- [ ] lottery-based savings already exist in the US; designing systems where you always win, but there is perceived risk (i.e. same feeling as gambling)
- [ ] expand on section about hardware manufacturers and what they can do to improve the smartphones that people have (improve the experience); dave's team is working on this problem: how to design a smartphone for this population? these devices aren't adopted for this audience, so if we were to design a smartphone for them tomorrow, what would it look like? "reimagine what a smartphone could look like"; "reimagine the smartphone"
- [ ] add graphs about how many people had to get a new smartphone over the course of the study
- [ ] point to the dashboards more frequency to show people that we have way more data
- [ ] idea: using sheng as a language that can be used as a language that you can add to android?
- [ ] technical language is difficult--make the point clearer; imagining a new phone, how do you avoid language that is difficult?
- [ ] cost: "when it's not free, it's too expensive"
- [ ] do women spend more than men in data bundles? how does their usage pattern different in terms of money? do the different behaviours they have translate financially?
- [ ] don't mention Sterro in quotes without explaining
- [ ] pre-installed applications: if we worked with manufacturers to pre-install DFS applications, there are problems to avoid, but it's not necessarily the case that it won't work. you can do it with the right approach and the right conditions (and training) in place, but don't assume that it will be used just because it's pre-installed.
- [ ] people have trust in institutions: if it's there, it's vetted. need to teach people the critical thinking
- [ ] opposite story: how they aren't exposed to how open the web is. there are few things like this in the world. intrinsic openness makes them behave strangely
- [x] talk about how people "play mshwari" instead of "use". reference KFD
- [x] representative depiction of the DFS products that people use; which services do people use?
- [x] which ones are apps, which are SIM toolkit-based
- [x] vicious cycle of the market as opposed to virtuous cycle that includes android, apps, services, etc. talk about the tension of orgs that want to make apps and the market forces. people don't know where to put themselves. people want to make apps for the future, but the market isn't ready for it. *this could be a graphic, with a cool circle in it*. "the market is failing". "products aren't created that use smartphone technology. when they are created, they aren't adopted."
- [x] it's important to have an executive summary because you don't know the whole DFS section is coming!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

- [ ] use chapter 4 to have a different approach: it's about the **so what**. use this chapter to reflect. more than facts, recommendations. answer the thesis.

**Comment by lauradereynal** [comment]
## Cool quotes to add 

What is a hustler?
person that you don’t have a specific job
work for any job you get
person calls you and ask if you can do a job
you can be called by someone “can you fetch water?"

----


why don’t you have that kind of job today? why is it difficult?
in order to get job, you must have money
to get a job from you, i have to give you some money

---- 

about jirsort's quizz 
> this game is too easy for you
yeah, but before, i never knew
the first time, i got 4/17

> and now?
i normally get 16 or 17

----
> ever used branch?
i applied for a loan

> did you get one?
yes, for 500

> how did you use it?
i used it to bet

----
about ignoring loans
comfort
     before: comfortable, because i never knew
     now: i’m stressed, because now that i borrow money i receive messages, [rambling]
          but i’m happy, because they give me money
          they message me about registering me in the RB (blacklist)
          [pissed about safaricom reminding him to pay them]
          okoa jahazi for 100; they disturbed me too much! so i just ignore the line
               “why do you tend to remind me i have to be when i know i’m supposed to pay!!?"
                    so i just ignore it

----

Do you have electricity ?
not now
charge at my neighbour's
for free

**Comment by secretrobotron** [comment]
- [x] Add a community impact section about using local expertise to build skills within the community  which will shape the future of healthy technology adoption for Kenya.

**Comment by secretrobotron** [comment]
> Cool quotes to add

@LauraReynal these all came from your evernote? There's so much gold in there. I was looking for a quote from Halina as well. Anything?

> about jirsort's quizz

Is this from Evans too?

**Comment by lauradereynal** [comment]
add quote from community member about the program's impact on them. Pick from the interviews.

**Comment by secretrobotron** [comment]
> add quote from community member about the program's impact on them. Pick from the interviews.

really great idea.

**Comment by secretrobotron** [comment]
- [ ] clean up all the graphs so that they're the right colour and don't have drop-down menus in them (they're too obviously screenshots right now)

**Comment by lauradereynal** [comment]
>  clean up all the graphs so that they're the right colour and don't have drop-down menus in them (they're too obviously screenshots right now)

Will move this to Beta along with all the design and media work.

**Comment by secretrobotron** [comment]
# DONE
