### ISSUE TITLE
Create slide deck to talk about this project

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#3]
@secretrobotron will help :smiley_cat:

**Comment by lauradereynal** [comment]
Here is the deck 
https://docs.google.com/presentation/d/1TnJk4bBLetG1KQvVoTb17wvQdt5o_JveLUOvVIIAhOQ/edit#slide=id.gd6434fe64_1_0

It needs a final pass and a peer review and then we can share this with communities and stakeholders?

@adamlofting @metaphorista @benrito @JoashMango 
Can you make sure you check it add flag anything before we share this ? 

thanks !

**Comment by lauradereynal** [comment]
The slide deck is done and being shared. 
Closing this ticket. Thanks to everyone who reviewed !
