### ISSUE TITLE
Create the first list of hypotheses that will drive our different interventions

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#30]
_Goal_: Create a first list of hypotheses that we want to test and learn from. 
These hypotheses will drive the design challenges for the interventions. 

Team: @secretrobotron @JoashMango @DuncanGW 
Consulted: @benrito 

Steps: 
1. Identify a first list of hypotheses that we will want to verify with our interventions
2. Take that list to different advisers and stakeholders and choose the most important ones that we would focus on 
3. Design interventions and methods for evaluation. 
4. Maybe create a template to evaluate them
5. Learn 
6. Iterate 
7. document iterations 

Notes: 
- we want to document each result in a blog post, and to have a consistent method 
- we want to create a tree of interventions that will show the iterations in a visual way, and would help understand the logic

**Comment by benrito** [comment]
Is there a document or spreadsheet we can populate?

**Comment by lauradereynal** [comment]
hey @benrito can you start populating on this spreadsheet. 

Tab 3 https://docs.google.com/spreadsheets/d/1-UPaBLNLAbqYZ-u3QQIxdPWT7MgJ6cSXBphCTWbVY4g/edit#gid=0

**Comment by benrito** [comment]
Yes, do we have a hard deadline?

**Comment by lauradereynal** [comment]
Can you jump in before Wednesday, and we can see how long it takes us to make progress ?

**Comment by lauradereynal** [comment]
@benrito let's do a working session on these soon. Have any input on the first draft ?

**Comment by lauradereynal** [comment]
the first list is created in this document.
https://docs.google.com/spreadsheets/d/1-UPaBLNLAbqYZ-u3QQIxdPWT7MgJ6cSXBphCTWbVY4g/edit#gid=2146668059
Next step is to do a review with informal advisors
