### ISSUE TITLE
Create the tree of hypotheses and of the different things we would want to test 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#31]
@secretrobotron we could use a simple online mindmapping tool ?
Let's give it a first try when we are in Kenya 

cc / @benrito to consult and keep informed

**Comment by secretrobotron** [comment]
Yes, yes! At the very least, a small diagram in this issue to start.

Do we have a set of "clean" hypotheses to start from that will be the roots of our tree (forest...)?
