### ISSUE TITLE
Finalize the recruiting questionnaire 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#35]
@JoashMango @DuncanGW Would you be able to share the recruitment questionnaire on the drive ? 

We can finalize it after our pilot recruitment on monday. 

@secretrobotron

**Comment by JoashMango** [comment]
Yes we will share

**Comment by secretrobotron** [comment]
The team is going to start using this tomorrow. Re-open this issue if you need to talk about it some more!
