### ISSUE TITLE
Add the research questions into the ReadMe file and the first blog post 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#38]
Goal: we need to document the research questions better, and have them easy to find anywhere. 
- Let's add them to the Readme
- Let's add them to the first blog post about the project #25 

cc / @secretrobotron

**Comment by lauradereynal** [comment]
Research Questions (for reference)
- What are the immediate _barriers_ to usage for first time smartphone users?
- How does _limited literacy_ impact the usage and adoption?
- What _formal and active education methods_ including training programs and outreach increase adoption?
- What _informal and passive education methods_ including pre-loaded applications, improved device on-boarding, and improved user experience increase adoption?
- Does _improved digital literacy and smartphone adoption_ change expectations for _financial stability_?
- Since most people buying a smartphone today have never used the Internet, they may have no prior concept of _the web, or search_. Do new users _understand the application metaphor_? How do they discover new applications? How does this _shape their understanding_ and use of DFS?
- _Most people get help_ using their new phones – from whom and for what? What other help might be appropriate or more helpful?
- What _spelling, syntax and language_ do they use online. Are text contractions, emoticons etc. standardized? Do people use sheng (mixture of Swahili and English) and if so for what communications?
- Who _purchased the phone_? Was it purchased on credit? Many phones are gifts, especially from boyfriends, parents and urban relatives – how does this influence full adoption and use of the phones and DFS?
- Who else _uses the phone and for what purpose_? Our general hypothesis is that smartphones are private and personal, but are there use case exceptions?
- What is the _route to discovery_ of uses outside of social media e.g. do people discover the web via links they receive in social media?

**Comment by lauradereynal** [comment]
Somehow, the gender research question has disapeared. Needs to be re-included

**Comment by lauradereynal** [comment]
Can we separate formal and informal  from passive and active education methods? 
They actually dont make sense to be together and exclusive from each others. 

What we want to test are the different active methods and passive methods. 

Thoughts @benrito ?

**Comment by chanditome** [comment]
@LauraReynal great idea Laura. We should head that way.

**Comment by lauradereynal** [comment]
We could also go like this: 

|  | Active | Passive |
| --- | --- | --- |
| Formal |  |  |
| Informal |  |  |

Where a hypothesis would be tested inside any one of those cells (by using a workshop, app, etc., depending on where you are in the matrix).

This requires us to define formal and informal methods –– i.e. do we actually mean that the formal education methods are institutions/schools?

**Comment by lauradereynal** [comment]
New questions: 
- Are digital skills more / less / equally important than financial skills when it comes to the adoption of DFS? 
  i.e. digital literacy vs. financial literacy

**Comment by chanditome** [comment]
Invite received. Action taken. :-D

**Comment by JoashMango** [comment]
We need to include gender questions as well;

Do gender have an effect in the use of different applications in smartphones?

**Comment by alexanderamolo** [comment]
Yes, there is something about males with smartphones compared to females
that we need to find out

**Comment by Arwa40** [comment]
Gender as a factor contribute highly in determine smartphone users on DFS hence should be included

**Comment by secretrobotron** [comment]
Done. Let's refine & add to that file in typical git/md fashion.

**Comment by secretrobotron** [comment]
Will add [blurb about] questions in #26.
