### ISSUE TITLE
Add a questions about Data plans and sim cards in interview 1 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#39]
Add questions about the number of sim cards and data plans that participants have 
- Do you have multiple sim cards? 
- Why ? 
- How do you use them ? How do usage differ ?
- Do you use different data plans ? How do you organize yourself ? 

@secretrobotron @JoashMango @DuncanGW

**Comment by lauradereynal** [comment]
https://docs.google.com/document/d/1Pw05h0AjucIIE-zNuqZ-XX1nyAiOKR4EfjQS7r2hUA4/edit#

**Comment by lauradereynal** [comment]
Should we make this one a recurring question ?

**Comment by secretrobotron** [comment]
@LauraReynal these are totally in the first interview now. How should we mark recurring questions? (Where should we put them?)

**Comment by JoashMango** [comment]
We can call the repeated questions as diaries

**Comment by lauradereynal** [comment]
OK we can close this issue then. Thanks
