### ISSUE TITLE
Make plan specific to community for 2016

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#4]
- Trainings 
- Roles 
- Feedback
- Growth and skills development 

@secretrobotron will help :boom:

**Comment by lauradereynal** [comment]
https://docs.google.com/document/d/1_fMsUBHhagm3AJAApgNrP0QVv9aN-ZG09mQ9oRndTwY/edit

First attempt is here. 
@secretrobotron could you help flesh this out ?

**Comment by secretrobotron** [comment]
Of course!

**Comment by secretrobotron** [comment]
:boom:

**Comment by lauradereynal** [comment]
mmmmmm @secretrobotron I feel like we need to do some detailed work on this one. 

:rose: Moving to next milestone

**Comment by lauradereynal** [comment]
Scheduled a meeting with Lucy for next week.

**Comment by Amuti** [comment]
@LauraReynal @secretrobotron  Could we look into roles and a specific plan for the Moz Kenya community members because I feel like guys are getting lost in the midst of the project plus Github is a bit overwhelming for most

Should I create an issue for this?

**Comment by lauradereynal** [comment]
Hey @Amuti I think you are right ! Yes, please feel free to make a new issue. 

We wanted to bring this to the call today and create small teams.

**Comment by Amuti** [comment]
Ok!
