### ISSUE TITLE
Document global data collection plan

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#40]
_Goal_: create a very simple and clear graphic or flow chart or bullet point to illustrate our data collection plan. The objective is for anyone in this project to understand how we collect, gather and analyze the data.

Lead: @secretrobotron do you think you could do that based on the meeting this morning ?

by "global" I meant : 
- Data from the phone usage (quanti)
- Data from the interviews (quanti + quali)
- Data from the interventions (quali)

**Comment by secretrobotron** [comment]
A very quick description of the data flow:

### Data from Interviews

_Interviewers => ODK => ODK DB (=> DDD) => MySQL_
1. Interviewers collect data on ODK on tablets
2. Data is uploaded to ODK database from tablets, **accessible only to a few people** (@DuncanGW Sometimes requires reminding field researchers because data fails to upload, right?)
3. Data is cleaned through scripts and manual processing (@DuncanGW and I talked about ways we might be able to automate, but he's cautious about missing important data.)
4. Cleaned data is regularly mirrored to a MySQL database, **accessible to more people**
5. Sets of cleaned, anonymized data (probably specific queries?) are exposed to community (and, consequently, public) to help build dashboards/software/curriculum/reports

### Data from Usage Recording App

Where the app works: _App => Log Files (=> DDD) => ¿¿MySQL??_
Where the app doesn't work: _Interviewer => ¿¿ODK?? => ¿¿MySQL??_
1. Interviewers install app on respondent phones where applicable
2. App routinely collects and uploads small packets of data and uploads them to AWS database (@dobbz: correct?)
3. Interviewers collect data manually where app isn't available
   - @dobbz @adamlofting: Where do they upload this data? Through ODK?
4. ¿¿¿Data is available in a MySQL database??? (@dobbz, is this going to be similar to how the cleaned interview data is stored? The same?)

### Data from Interventions

_DDD researcher + Mozillian lead intervention => observation and documentations => google docs => MySQL ??_
- Need to have a good sense of what kind of curriculum/software we're going to develop first
- Ideally, usage data from any software winds up in a MySQL database, similar to above
- Ideally, some results from software that can tell us about hypothesis results => MySQL
- Ideally, interview data or surveys specific to interventions => MySQL
- @dobbz @adamlofting what do you think here?
- @LauraReynal missing something important?

**Comment by adamlofting** [comment]
Thanks @secretrobotron this is really helpful.

> Sets of cleaned, anonymized data (probably specific queries?) are exposed to community (and, consequently, public) to help build dashboards/software/curriculum/reports

I'm just flagging that properly anonymizing the raw data for sharing is somewhere between really difficult and impossible. But we'll work to share as much as we can in the most sensible way possible. 

> Interviewers collect data manually where app isn't available
>     @dobbz @adamlofting: Where do they upload this data? Through ODK?

I imagine we just add these as extra fields at the end of the interview survey. No need to build extra data flows.

> Data from Interventions
> @dobbz @adamlofting what do you think here?

Mostly, the effect of interventions should show up in the interview and phone data overtime. That's the 'causal' piece we'll be looking for.

But, we could add some further evaluation/interview type questions at the end of the interventions, noting that we should consider that part of the intervention in terms of how repeatable they are. (E.g asking people to reflect on what they learn in a training, is a further part of the training).

We could also ask people to reflect back on the interventions at the end of the study, and see which they remember or felt caused changes or tipping points in behaviour etc. This will likely give different results to the feedback immediately after the interventions.

**Comment by dobbz** [comment]
Yes  @secretrobotron https://github.com/secretrobotron you are right on
all assumptions.

The interview data and the data collected from the interviewers will be on
the same server.

I propose software for the interventions also collect specific data that we
can analyse to test the interventions and upload to our DB.
For other types of interventions we can add specific data collection
methods to the existing app to see if the results of the interventions

@adamlofting https://github.com/adamlofting
I totally agree

On 18 February 2016 at 01:39, Bobby Richter notifications@github.com
wrote:

> A very quick description of the data flow:
> Data from Interviews
> 
> _Interviewers => ODK => ODK DB (=> DDD) => MySQL_
> 1. Interviewers collect data on ODK on tablets
> 2. Data is uploaded to ODK database from tablets, _accessible only to
>    a few people_ (@DuncanGW https://github.com/DuncanGW Sometimes
>    requires reminding field researchers because data fails to upload, right?)
> 3. Data is cleaned through scripts and manual processing (@DuncanGW
>    https://github.com/DuncanGW and I talked about ways we might be able
>    to automate, but he's cautious about missing important data.)
> 4. Cleaned data is regularly mirrored to a MySQL database, _accessible
>    to more people_
> 5. Sets of cleaned, anonymized data (probably specific queries?) are
>    exposed to community (and, consequently, public) to help build
>    dashboards/software/curriculum/reports
> 
> Data from Usage Recording App
> 
> Where the app works: _App => Log Files (=> DDD) => ¿¿MySQL??_
> Where the app doesn't work: _Interviewer => ¿¿ODK?? => ¿¿MySQL??_
> 1. Interviewers install app on respondent phones where applicable
> 2. App routinely collects and uploads small packets of data and
>    uploads them to AWS database (@dobbz https://github.com/dobbz:
>    correct?)
> 3. Interviewers collect data manually where app isn't available
>    - @dobbz https://github.com/dobbz @adamlofting
>      https://github.com/adamlofting: Where do they upload this data?
>      Through ODK?
> 4. ¿¿¿Data is available in a MySQL database??? (@dobbz
>    https://github.com/dobbz, is this going to be similar to how the
>    cleaned interview data is stored? The same?)
> 
> Data from Interventions
> - Need to have a good sense of what kind of curriculum/software we're
>   going to develop first
> - Ideally, usage data from any software winds up in a MySQL database,
>   similar to above
> - Ideally, some results from software that can tell us about
>   hypothesis results => MySQL
> - Ideally, interview data or surveys specific to interventions => MySQL
> - @dobbz https://github.com/dobbz @adamlofting
>   https://github.com/adamlofting what do you think here?
> - @LauraReynal https://github.com/LauraReynal missing something
>   important?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/40#issuecomment-185441338
> .

## 

Mr. Dobbz Mkolwe
​​
Database & Systems Administrator, DDD - Kenya
Paramount Plaza 7th Floor
P.O Box 4282 - 00506,  Nairobi, Kenya

Office: (+254) 771 19 1795  |  Cell (+254) 713 10 3222

http://www.digitaldividedata.com/*Creating a World of Digital
Possibilities http://www.digitaldividedata.com/ *

**Comment by lauradereynal** [comment]
Thanks for the documentation @secretrobotron - very helpful. 

I added a line on the intervention piece and it leads me to a question about qualitative data. 
Do we want to also store the more narrative data into My SQL as well? 

I'm thinking especially of 
- answers from the interviews that are more narrative, 
- and documentations from the workshops.

**Comment by secretrobotron** [comment]
> I added a line on the intervention piece

@LauraReynal cool! where?

IIRC the narrative data will be stored in MySQL because it gets typed out by interviewers into ODK. 

What kind of documentation from workshops are you hoping makes it into a database? Questionnaire responses, or photos and documents?

**Comment by lauradereynal** [comment]
`What kind of documentation from workshops are you hoping makes it into a database? Questionnaire responses, or photos and documents?`

I think mostly text from the open researchers, documenting what they see. 
Maybe also some questionnaire answers when needed?

**Comment by secretrobotron** [comment]
> I think mostly text from the open researchers, documenting what they see.

That's something interesting to ask them, actually. I think we can avoid some overhead by having everyone write observations in a place that (a) they feel comfortable, and (b) they can share easily. Maybe we can make some recommendations (maybe a Google doc with a template we prepare?), but I think hooking that up to MySQL directly somehow would be difficult.

That being said, we can always put significant things into a databased once we're done. But, @LauraReynal, what's the best method to look through broad observations and long-form answers?

**Comment by lauradereynal** [comment]
@secretrobotron thanks for the details and information here. 
Do you think this is ready to be published on the blog or on a github file so that's it's easily accessible?

**Comment by secretrobotron** [comment]
@LauraReynal  We still don't have a great answer for the stuff you just asked about. What kind of detail should we expect from researchers during interventions?
- For prepared questions concerning a hypothesis: we need a way for researchers to enter data. @dobbz suggested that we could still use some software to do that, which would upload to the same DB that stores the rest of our interview data. Would we build questionnaires in ODK before interventions that are specifically for researchers to capture data?
- For ambient observations, should we recommend something like Google docs?

**Comment by secretrobotron** [comment]
@dobbz do you mind detailing the data storage for the data collection app a bit here? From the call yesterday, I gathered that we're going to use Splunk to look at the data. Is it still being stored on AWS? The description above mentions MySQL still, but I don't know that we need it anymore in this case.

**Comment by dobbz** [comment]
We have 3 platforms that we are currently using to collect data.
- **android app** (collecting phone usage data)
  -- custom made android app that collects phone usage data from willing respondents usage data and syncs the data to an online MySQL database
- **ODK Aggregate** (collection of field survey data from enumerators)
  -- Platform that all field researchers use to collect data. They collect data using odk collect on their mobile phones and upload to the aggregate server
- **Splunk** (data analysis platform)
  -- This platform forms a layer that dashboards query the MySQL DB for data to do analysis
  Here is a schema

![dso data collection](https://cloud.githubusercontent.com/assets/16733688/13501682/ae6b93f2-e178-11e5-8648-c7f208180cdf.png)

**Comment by lauradereynal** [comment]
@dobbz @secretrobotron can we make this a blog post?

**Comment by JoashMango** [comment]
Yes i do agree to the idea of making it a blog post

**Comment by secretrobotron** [comment]
That sounds like a cool idea. If @dobbz wants to pen a draft, I'd be happy to help get it published.

(I would also suggest moving this to another bug. This one feels finished.)

**Comment by AI-DennisNdegwa** [comment]
Not my avenue....but how do you guys feel about text entries initially.....and collected audio to be transcribed later? I believe the audio is really important for getting "emotions". There can be a database for the audio and another one for the transcribed data...maybe photos can be attached to relevant conversations as well.

**Comment by secretrobotron** [comment]
This is well underway and @dobbz's graphic explains a ton. Closing.
