### ISSUE TITLE
Devise method for detecting and investigating sharing with control group

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#44]
What happens when someone from the control group is taught about an aspect of DFS or their smartphone by someone in the experimental group? Can we track what happened through interviews? What does that tell us? Should we try to prevent it?

@JoashMango @DuncanGW @LauraReynal @benrito

**Comment by lauradereynal** [comment]
I dont think we should try to prevent it. 
Agreed that we should find a way to track it. Can we add a questions in the diaries?

**Comment by lauradereynal** [comment]
Hey Team, how did we decide that we would tackle this ?

**Comment by secretrobotron** [comment]
This might be coming out in journal entires. @DuncanGW @LauraReynal @JoashMango we can investigate by reading interview material soon? Something to comment on in mid-study report, I would imagine.

**Comment by secretrobotron** [comment]
We'll need to be alert about this as the next prototype rolls out. There are questions we're asking about this specifically in future interviews/surveys. Let's keep an eye on it and put information here if it comes up.

**Comment by secretrobotron** [comment]
Never got to this.
