### ISSUE TITLE
Get some awesome new people on this project!

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#45]
Invite the DSO bootcamp participants to this repo.
### List of contributors:
- @zuma1
- @festolangat
- @FauziaIsmail
- @Obadha
- @Shey02
- @uwanja
- @chanditome 
- @WinnieMakokha 
- @Ednahkiome
- @denomain
- @josiahmuyesu
- @xelawafs
- @Arwa40 
- @ChristabelAchieng
- @dobbz
- @nekesawekesa
- @nmarita
- @marywashe
- @alexanderamolo

**Comment by chanditome** [comment]
Thanks for the invite guys.

**Comment by lauradereynal** [comment]
@nao07

**Comment by Obadha** [comment]
I'm here. Virtually of course. =)

**Comment by zuma1** [comment]
thanks i got email.

**Comment by nekesawekesa** [comment]
am here

**Comment by nao07** [comment]
Got it!

**Comment by shey02** [comment]
am alive!

**Comment by Obadha** [comment]
omg! me too! :D

**Comment by shey02** [comment]
really

**Comment by shey02** [comment]
prove it

**Comment by FauziaIsmail** [comment]
<3

**Comment by xelawafs** [comment]
Made it

**Comment by ChristabelAchieng** [comment]
:-)

**Comment by Obadha** [comment]
yes, really. lol o:)

**Comment by Obadha** [comment]
why does github not allow us to use smiley faces :/

**Comment by AI-DennisNdegwa** [comment]
The one.

**Comment by marywashe** [comment]
Think Chiswick just did it

**Comment by festolangat** [comment]
Niko area

**Comment by secretrobotron** [comment]
> why does github not allow us to use smiley faces :/

It does, @Obadha :smile: !

**Comment by secretrobotron** [comment]
Everyone is a project contributor now.

Let me know if you have any questions!
