### ISSUE TITLE
Make your first github issue

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#46]
Hello everyone! Let's get acquainted with github and this project. Try this:

**GOAL**: Introduce yourself to everyone in the project by making a new github issue.
- Make a new "issue" by clicking on the "New Issue" button in the top-right corner
- In the issue, write a little bit about yourself. Include:
  - What is your name?
  - What is your favourite word (Swahili, English, French, Japanese, or otherwise)
  - What do you want your role to be in this project?
  - If you feel brave, include some of your friends/colleagues in your issue by "mentioning" them. e.g. `@secretrobotron`, or `@festolangat`. Use the list below to find people.
  - Experiment with emojis. (hint: Write a colon, `:`, and a menu will pop up to help.)
- Click the "Submit new issue"
- Once your issue has been saved (submitted), write its number down in a comment here. e.g. this issue is #46, so I would write `Hooray! I made an issue! It's #46!`.

cc
@zuma1
@festolangat
@FauziaIsmail
@Obadha
@Shey02
@uwanja
@chanditome
@WinnieMakokha
@Ednahkiome
@denomain
@josiahmuyesu
@xelawafs
@Arwa40
@ChristabelAchieng
@dobbz
@nekesawekesa
@nmarita
@marywashe
@alexanderamolo
@nao07
@DuncanGW
@JoashMango

**Comment by zuma1** [comment]
hello guys. l created the issue  #53

**Comment by josiahmuyesu** [comment]
Hey Team, I also created issue #52 .It's pretty easy.

**Comment by Obadha** [comment]
Loso add issue. Loso issue #56 .

Loso happy to learn emoji. Loso thank @secretrobotron  :+1:

**Comment by chanditome** [comment]
#59 is live.

**Comment by dobbz** [comment]
#61 :eyeglasses:

**Comment by lauradereynal** [comment]
:joy_cat:

**Comment by WinnieMakokha** [comment]
#57 loves that people are learning to communicate on GitHub. Am learning too!! keep up the learning curve!!

**Comment by FauziaIsmail** [comment]
Made an issue
#71

**Comment by AI-DennisNdegwa** [comment]
Issues issues issues. :\ Here's my issue. #73

**Comment by zuma1** [comment]
#53 likes the way people are motivated to work as ateam.

**Comment by Amuti** [comment]
#75 alive! Sorry i jumped in a bit too late guys :+1:

**Comment by AI-DennisNdegwa** [comment]
Issue #73 alive and kicking. Team DSO all the way.

**Comment by lauradereynal** [comment]
YAAAYY !! so many cool tickets here :smile_cat: 
@secretrobotron How do you want to take this further ?

**Comment by secretrobotron** [comment]
Well, this was rad. Thanks everyone. You're now github gurus. See you all online.

![mission accomplished small](https://cloud.githubusercontent.com/assets/403231/13143109/96b7c506-d60f-11e5-87ed-26e45043f3d7.png)
