### ISSUE TITLE
Add to & refine research questions

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#47]
A couple things came up in #38:
- We need to include gender questions as well; Do gender have an effect in the use of different applications in smartphones? (@JoashMango)
- Are digital skills more / less / equally important than financial skills when it comes to the adoption of DFS? i.e. digital literacy vs. financial literacy (@LauraReynal)

**Comment by secretrobotron** [comment]
Also from some thinking @LauraReynal and I did yesterday:

We could also go like this: 

|  | Active | Passive |
| --- | --- | --- |
| Formal |  |  |
| Informal |  |  |

Where a hypothesis would be tested inside any one of those cells (by using a workshop, app, etc., depending on where you are in the matrix).

This requires us to define formal and informal methods –– i.e. do we actually mean that the formal education methods are institutions/schools?

**Comment by lauradereynal** [comment]
Note: Need to add the gender question. I don't know how it got out of the study.

**Comment by secretrobotron** [comment]
From @nekesawekesa in #55:

> After your first experience with smartphone do you intend to continue using a smartphone or you think you are better off using a feature phone?

**Comment by KalpanaSimhan** [comment]
Some gender questions to consider:
1) Women tend to have less access to education and lower literacy rates, how does this effect smartphone use?
2) Do women make independent decisions to purchase smartphones, or do the rely on men (husbands, father etc.) to provide money and/or permission to purchase? Does the cost of a smartphone in particular prevent women from purchasing or making independent purchases?
3) Do men have access to women's phones (e.g. can they read their texts, know who the called, etc.)?
4) Do women make or have a say in financial decisions within their families? How does this impact the use of DFS?

Also, are we providing our data collectors with any gender sensitization training? And are we looking at how and where we are collecting data with a gender lens?

**Comment by JoashMango** [comment]
Yes our data collectors have gender sensitization training. In the recruitment they have gender lens. will share blog with results of the recruitment

**Comment by secretrobotron** [comment]
Refined list added to https://github.com/MozillaFoundation/digital-skills-observatory/blob/master/questions.md.
