### ISSUE TITLE
Follow up on github training

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#48]
From experience in workshop, fill this out: https://docs.google.com/a/mozillafoundation.org/forms/d/16U6fXW7Y5Gk__Hg1wP9k3GtsiJeQN8NZTiFP-Kx82Yc/viewform

**Comment by lauradereynal** [comment]
Hey @secretrobotron what is the status of this one ?

**Comment by WinnieMakokha** [comment]
Hey @LauraReynal and @secretrobotron  I apologize for sending late apologies for not eing able to attend the skype call. I also remember I didnt submit my skype ID and i cant seem to trace the google doc that we were to add on. Please add me rabera2@live.com

**Comment by lauradereynal** [comment]
Thanks @WinnieMakokha

**Comment by lauradereynal** [comment]
@secretrobotron what is this survey for?

**Comment by secretrobotron** [comment]
@LauraReynal designing pieces of curriculum. In our case, providing github training to people. Thought we could provide some useful insights based on our experience now.

**Comment by shey02** [comment]
hey @secretrobotron and @LauraReynal i would also like to apologize for being out of touch for quite sometime,i cannot seem to trace the google doc where we were to add our Skype ID's ,kindly add me up;  sheyy021 for the next call in advance

**Comment by lauradereynal** [comment]
@secretrobotron it would be good to tackle this in July

**Comment by WinnieMakokha** [comment]
@LauraReynal & @secretrobotron I am trying to learn more about using GitHub seeing as I learnt about it first from DSO projec. its been a long time coming though . So one of the things am doing i trying to build up my profile and account(dont know if those are the right words). Any tips?Help?

**Comment by secretrobotron** [comment]
@WinnieMakokha interesting. What are you hoping to do with github? We use it a lot for project management and storage. Are you trying to bolster your profile here?

**Comment by WinnieMakokha** [comment]
@secretrobotron well that was one way to put it ,but really i want to know how much more i can utilize the platform(borrowing from this project experience) other than for 'code'

**Comment by secretrobotron** [comment]
Ah, great! @WinnieMakokha can you look this over then? http://joeyklee.github.io/friendly-github-intro/

@acabunoc (a very cool person that you should definitely get to know) shared it with me, and will be trying to use it in her work to develop methods and practice for open source contribution. Considering your background and your experience with this project, I think she could use your feedback on whether or not it's a helpful tutorial.

**Comment by secretrobotron** [comment]
@WinnieMakokha and if it is, we can circulate it within the project.
