### ISSUE TITLE
Make plan for the Interventions 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#5]
Make plan specific to interventions for 2016 
- What is the big picture ?
- How do we make them meaningful ?
- What is the best frequency etc. 

@secretrobotron will help :smiling_imp:

**Comment by secretrobotron** [comment]
Do we need to divide the treatment groups into subgroups for more validity?

**Comment by lauradereynal** [comment]
Are we designing cumulative interventions, which would lead us to understand how people learn and to document the learnings from the iterative process 

OR 

Are we doing non-cumulative and different interventions to understand the impact of specific content.

**Comment by lauradereynal** [comment]
Will figure these details during the bootcamp, once we can work on the overall timeline + questions + interventions. Needs to be done with DDD  and better if done Face to face in Kenya. 
Closing this for now.
