### ISSUE TITLE
Follow up with DSO community members that couldn't attend the bootcamp

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#50]
We should communicate with everyone who applied and other peripheral interested parties.

**Comment by lauradereynal** [comment]
Should we add them on the mailing list?
Can we identify new people to invite for the next round?

**Comment by chanditome** [comment]
Do we still have the call today at 8pm GMT+3?

**Comment by lauradereynal** [comment]
this is no longer a priority - will assess and re-open if needed.
