### ISSUE TITLE
Introduction_Josiah Muyesu

### ISSUE THREAD

**Issue by josiahmuyesu** [MozillaFoundation/digital-skills-observatory#52]
Hi Team,

My name is Josiah and my favorite word is "Ambition". My role on the project would be more on Project Management/Community Management. I look forward to working with all of you on the DSO Project.

**Comment by secretrobotron** [comment]
Hey, thanks @josiahmuyesu. Now, try this:

Write a comment in [my issue](https://github.com/MozillaFoundation/digital-skills-observatory/issues/46) including the number of this one. e.g. this issue is #52, so I would write something like `Hooray! I made an issue! It's #52!.`

**Comment by lauradereynal** [comment]
Hey @josiahmuyesu thanks for making this issue :smile_cat: :fallen_leaf: :dancers:
