### ISSUE TITLE
Faith profile

### ISSUE THREAD

**Issue by zuma1** [MozillaFoundation/digital-skills-observatory#53]
My names is Faith Zuma. My favorite word is favorite word is Umoja. My role to this project is to help in curriculum designing/community management/engagement. I am passionate about finding more information on about DSO projects and working together with you all. :+1:

**Comment by secretrobotron** [comment]
Thanks @zuma1! Now, try this:

Write a comment in [my issue](https://github.com/MozillaFoundation/digital-skills-observatory/issues/46) including the number of this one. e.g. this issue is #53, so I would write something like `Hooray! I made an issue! It's #53!.`

**Comment by secretrobotron** [comment]
Thanks @zuma1 :+1: !
