### ISSUE TITLE
Document community guidelines and processes for the project

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#54]
@secretrobotron 
Make a simple one pager with basic process information and guidelines.

Inspiration and help from @Saallen would be awesome.
- How to participate ?
- Where comms happen and useful links ?
- Policy regarding expenses / hotels / transportations etc. => @Saallen do you have Mozfest documents we could use for this one ?

**Comment by xelawafs** [comment]
@LauraReynal so will the one pager just be a summary of guidelines and processes? Meaning having more detailed documentation leading back to the one pager.

**Comment by lauradereynal** [comment]
We don't need something long. Just a summary.

**Comment by Saallen** [comment]
i can of course share my MozFest docs on travel and expanse processes. I will email you what I have.
:email:

**Comment by Saallen** [comment]
@LauraReynal 
I realise what I have is very specific with Mozfest- there are certain points you can take but we might need further input from Alex. As you requesting these policies for volunteers or yourselves?
Either way @edrushka and myself are setting out the goals for convenings this year and will add these requests in. :email:  on the way

**Comment by lauradereynal** [comment]
Thanks for the email and the details @Saallen 
I'll send a meeting to @edrushka and you for drafting something specific to this project.

**Comment by lauradereynal** [comment]
Update: @secretrobotron and I to review and produce :fearful: :construction_worker: :muscle: :mushroom:

**Comment by secretrobotron** [comment]
@acabunoc we had some stuff here that could be beneficial to review as part of your program.
