### ISSUE TITLE
Meet Loso.

### ISSUE THREAD

**Issue by Obadha** [MozillaFoundation/digital-skills-observatory#56]
Loso make issue.

Loso speak in 3rd person. Like Hulk. Or Rath. :japanese_ogre: 
Loso favorite word, Bankai. Japanese. Word said by shinigami in anime (Japanese animation), Bleach.

Loso prefer Open Researcher. Loso also involve in Software Prototyping.

Loso use emoji. A lot. :angel: 

@shey02 notice Loso :stuck_out_tongue:

**Comment by secretrobotron** [comment]
Thanks @Obadha :smile:. Nice work.
