### ISSUE TITLE
lovely people

### ISSUE THREAD

**Issue by WinnieMakokha** [MozillaFoundation/digital-skills-observatory#57]
S o much laughter. so much learning. a toast to life:-)
@shey02 your ice-cream says hello.:-)

**Comment by secretrobotron** [comment]
Thanks @WinnieMakokha! Now, try this:

Write a comment in [my issue](https://github.com/MozillaFoundation/digital-skills-observatory/issues/46) including the number of this one. e.g. this issue is #57, so I would write something like `Hooray! I made an issue! It's #57!.`

**Comment by chanditome** [comment]
Keep learning @winniemakokha!

**Comment by lauradereynal** [comment]
Thanks for filling this first ticket @WinnieMakokha I hope github seems less difficult now ! 
Let us know if you have more questions. I will close this ticket now so that we can have a really clean repository.
Feel free to re-open if you have more questions.
