### ISSUE TITLE
Chandi, the fish-lover.

### ISSUE THREAD

**Issue by chanditome** [MozillaFoundation/digital-skills-observatory#58]
Hey guys, I am Chandi the fish lover.

**Comment by secretrobotron** [comment]
Excellent thought, @chanditome. How should we take action?

**Comment by secretrobotron** [comment]
:fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish: :fish: :tropical_fish:
