### ISSUE TITLE
Tryin' it out too

### ISSUE THREAD

**Issue by marywashe** [MozillaFoundation/digital-skills-observatory#60]

**Comment by marywashe** [comment]
It's that easy

**Comment by lauradereynal** [comment]
Hey @marywashe thanks for trying to file an issue ! 
Is there anything that is confusing ? 

Try adding the community label? 
Try assigning this issue to me?

**Comment by secretrobotron** [comment]
Thanks @marywashe! Now, try this:

Write a comment in [my issue](https://github.com/MozillaFoundation/digital-skills-observatory/issues/46) including the number of this one. e.g. this issue is #60, so I would write something like `Hooray! I made an issue! It's #60!.`

**Comment by marywashe** [comment]
Hi guys, I'm Mary Washe,  my favourite phrase is 'never give up'. Things  will always  seem to be  challenging in the beginning but keep the spirit my fellow researchers.

**Comment by secretrobotron** [comment]
Hey @marywashe. Before you close this issue, check out my suggestion above: https://github.com/MozillaFoundation/digital-skills-observatory/issues/60#issuecomment-172841234

Once you've tried that, our mission here is accomplished!

**Comment by lauradereynal** [comment]
@secretrobotron do you want to keep these tickets or can we close ?

**Comment by secretrobotron** [comment]
We can close and catch up with @marywashe if she's got further questions.
