### ISSUE TITLE
Create a glossary in the README

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#62]
To define terms we use often. Everyone can contribute and ask for clarifications.

**Comment by secretrobotron** [comment]
Some terms:
- DSO
- DFS
- KFD 
- BOP 
- **Intervention**
- Hypothesis
- Curriculum
- Workshop
- Software
  - Testing
  - Data-collection
- Prototype
- Quantitative
- Qualitative
- Data 
- Diary
- Questionnaire 

cc @LauraReynal @JoashMango @DuncanGW

**Comment by JoashMango** [comment]
UCD
Control
Treatment

**Comment by xelawafs** [comment]
RCT
KFD
Phones (Dumb, Feature, Smart)

**Comment by lauradereynal** [comment]
@benrito @metaphorista @adamlofting @KalpanaSimhan feel free to add words that would need to be in the glossary

**Comment by zuma1** [comment]
You can add mobile app as a word

**Comment by secretrobotron** [comment]
A version should be published as a blog post when done.

**Comment by secretrobotron** [comment]
@JoashMango would you be able to define UCD, Control, and Treatment so that I can put them in a glossary entry and sound intelligent? :smile:

**Comment by secretrobotron** [comment]
@JoashMango and RCT?

**Comment by secretrobotron** [comment]
Created a [glossary.md](https://github.com/MozillaFoundation/digital-skills-observatory/blob/master/glossary.md) file for us to keep track of terms. **Please, add to it when you find something that can be defined!**

**Comment by JoashMango** [comment]
**User Center Design**: User requirements are considered right from the beginning and included into the whole product cycle. These requirements are noted and refined through investigative methods including: ethnographic study, contextual inquiry, prototype testing, usability testing and other methods
**Randomized Control Trial:** A study design that randomly assigns participants into an experimental group or a control group. As the study is conducted the experiment group for our case is where we will train them on use of the phone through workshop. The control group will not be trained on anything. But at the end of the study we will check on both treatment and control if there is any difference in the use of phone. If incase the training had any effect to usage or not.
**Control:** There is a group in the study but nothing is induced to them. For our case it is the group that will have all the requirement for the research but no training will be conducted for them but we will only follow up with questions to see how they progress with phone usage and DFS.
**Treatment:** This is a group in study where different interventions will be conducted with them. Training in different modules both for phone usage or DFS. At the end evaluation will be done to see the effect of the interventions versus group without interventions.

**Comment by JoashMango** [comment]
@secretrobotron  i have define the terms

**Comment by xelawafs** [comment]
This being a good first bug issue, here's a brief description on how to tackle it:

1. Jump to the **glossary.md** file in edit mode, here's a direct link to edit mode: [link](https://github.com/MozillaFoundation/digital-skills-observatory/edit/master/glossary.md)
2. Enter a term followed by its definition making sure to maintain the same format. While at it, you can click the **Preview changes** tab to review your contribution before committing/saving.
3. Just before clicking **commit changes** button at the bottom of the page, make sure to insert a comment in the commit changes section highlighting/defining changes you've made.

If you are already here, you can start by adding the terms and definitions by @JoashMango above

**Comment by chanditome** [comment]
As proposed by @xelawafs in #62, I have added @JoashMango 's terms, but only the first two. Hoping someone else who wants to learn can add the other two. 

I also made a few changes on the grammar/clarity of the first term; 'randomized control trial'.

Thanks for the lesson Alex, thanks for the definitions Joash and thanks for creating the good first bug @secretrobotron!

**Comment by lauradereynal** [comment]
WOW ! :fireworks: thanks everyone for the great documentation here. 

I only have one feedback: I think we can do a better job at defining a smartphone versus a feature phone. Are there some specific technical details to include? What is the main difference with the OS? Do feature phone have similar application ecosystems?

**Comment by lauradereynal** [comment]
I'm adding this video to our glossary 
https://vimeo.com/106505300 you should check it out !

**Comment by chanditome** [comment]
Thanks for the update and video link @LauraReynal. Yes, "feature" phone is apt.

**Comment by lauradereynal** [comment]
Thanks to everyone who contributed to this glossary :+1: 
Closing for now.

**Comment by secretrobotron** [comment]
Ordered alphabetically now :).
