### ISSUE TITLE
Create the bootcamp feedback survey 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#63]
Gather feedback from the community 
@secretrobotron @JoashMango @DuncanGW 

I'll give it a first try and send it to you for feedback.

**Comment by chanditome** [comment]
Sounds good! We are ready.

**Comment by lauradereynal** [comment]
http://goo.gl/forms/BV3oJftb2N Here is a first draft for a quick survey.
Sending on the list to everyone today :smile:

**Comment by lauradereynal** [comment]
This has been sent to the list. Closing this ticket.
