### ISSUE TITLE
Figure out how to use our geo-tracking data

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#64]
@secretrobotron

**Comment by secretrobotron** [comment]
Very nice. Uploading now. Would love @cassiemc and @lovegushwa's feedback here.

**Comment by lauradereynal** [comment]
Can we publish a map of our first field trip ?

What does it look like right now @secretrobotron?

**Comment by lauradereynal** [comment]
https://docs.google.com/document/d/1GVbhxJgQr9eGjU6KWb95qo-PHaPhvWLPl2uvcEHtAu8/edit 
Adding this note to our production document. We can close this ticket. There is not big need for Kenya.
