### ISSUE TITLE
Blog post - learnings from our first interview  

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#65]
Blog about our field trip monday 
@secretrobotron can we add a couple of questions from the DDD researchers too ?

**Comment by chanditome** [comment]
Looking forward to read on your individual personal experiences @LauraReynal and @secretrobotron .

**Comment by WinnieMakokha** [comment]
Me too!! would like to read what it was like for @LauraReynal & @secretrobotron - personal experience!

**Comment by lauradereynal** [comment]
What we did 
Why it's important to do it
What we learned from it

Attach the interview as a link on the blog post

**Comment by lauradereynal** [comment]
@secretrobotron Here is a doc we can use to keep all our blog posts 
https://docs.google.com/document/d/1oK0ZNd8zpq6uCxOxY2YeZxxEab-ucjHaU5V72S5uq3w/edit#

**Comment by secretrobotron** [comment]
@LauraReynal rad. Do you mind if we write each post as a new doc? Will be easier to work & edit I think.

**Comment by lauradereynal** [comment]
@secretrobotron I did a pass on this blog post. It's not the best but I think we should still publish it.
What do you think ? 
Can you do a content and copy review ?

I think with some pictures and an extract of the interview questions it will be interesting. We did learn a lot that day.

https://docs.google.com/document/d/1oK0ZNd8zpq6uCxOxY2YeZxxEab-ucjHaU5V72S5uq3w/edit#

@JoashMango @DuncanGW Can you please do a review of this blog post about our first field test in Wote? 

Proposed Deadline For posting: This friday

**Comment by JoashMango** [comment]
we will work on it

**Comment by JoashMango** [comment]
just commented on it

**Comment by lauradereynal** [comment]
Thanks for the feedback @JoashMango

**Comment by AI-DennisNdegwa** [comment]
@secretrobotron  @JoashMango @LauraReynal  Will the research focus on people that have not used a smartphone for over three months (in reference to the blog post)? Or will it focus on people that have never owned a smartphone?

**Comment by lauradereynal** [comment]
@denomain we are targeting first time smartphone users. We will have participants that have never used a smartphone, as well as participants who have used a smartphone for less than 3 months.

**Comment by lauradereynal** [comment]
@secretrobotron –– as our director of publication, can you give me a go (or not) for this blog post?

**Comment by secretrobotron** [comment]
I made some heavy edits. Check it out!

Content looks good though. Let's get it on the blog ASAP.

**Comment by lauradereynal** [comment]
Thanks for the heavy edits. 

It's published on the blog :fireworks:

**Comment by lauradereynal** [comment]
https://mozilla-foundation-research.herokuapp.com/running-an-interview-recruiting-pilot-digital-skills-observatory-2/
