### ISSUE TITLE
Blog post - community members about the bootcamp 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#66]
ask a couple of volunteers to share their experience about the bootcamp

**Comment by chanditome** [comment]
I promised to submit a blogpost. When's the deadline for this?

**Comment by lauradereynal** [comment]
Hey @chanditome Sounds great. How about next friday for a deadline?

**Comment by lauradereynal** [comment]
Hey Chandi, did you get a chance to write something yet ?

**Comment by chanditome** [comment]
Hey @LauraReynal, I just sent it out to you.

**Comment by lauradereynal** [comment]
Thanks for writing about the bootcamp @chanditome. Closing this ticket.
