### ISSUE TITLE
Set up regular community call

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#67]
Skype is the default preference, but happy to do somewhere more convenient for everyone.

@LauraReynal

**Comment by josiahmuyesu** [comment]
Hi Laura,

Skype is also my preference. Thanks☺

On Tue, Jan 19, 2016 at 12:02 PM, Bobby Richter notifications@github.com
wrote:

> Skype is the default preference, but happy to do somewhere more convenient
> for everyone.
> 
> @LauraReynal https://github.com/LauraReynal
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/67
> .

## 

_Mr. Josiah Muyesu_

_Research Field Supervisor_

_Digital Divide Data_

_Paramount Plaza,7th Floor4828-00506_

_Nairobi,Kenya_

_josiah.muyesu@digitaldividedata.com
josiah.muyesu@digitaldividedata.comOffice: +254.772.191.795_
_Mobile: +254.725.790.973 / 735.790.973_

Digital Divide Data: Creating a World Of Digital Possibilities
http://www.digitaldividedata.org

..the greatest results in life are usually attained by simple means and the
exercise of ordinary qualities.These may for the most part be summed in
these two:Common-sense and Perseverance....

**Comment by secretrobotron** [comment]
@josiahmuyesu 

> Hi Laura,

I'm Bobby! :stuck_out_tongue_winking_eye:

**Comment by chanditome** [comment]
Slack has just introduced the ability to call team members via Skype within Slack. That's crucial :-)
I am fine with Skype. If majority feel different then we can consider an alternative.
Please remember that parts out of Nairobi have connectivity challenges. Kilifi and Vihiga for example will need to be well prepared to make this call when that time comes.

**Comment by josiahmuyesu** [comment]
Hi Bobby, my skype username is josiah.muyesu

On Tue, Jan 19, 2016 at 12:12 PM, Bobby Richter notifications@github.com
wrote:

> @josiahmuyesu https://github.com/josiahmuyesu
> 
> Hi Laura,
> 
> I'm Bobby! [image: :stuck_out_tongue_winking_eye:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/67#issuecomment-172783384
> .

## 

_Mr. Josiah Muyesu_

_Research Field Supervisor_

_Digital Divide Data_

_Paramount Plaza,7th Floor4828-00506_

_Nairobi,Kenya_

_josiah.muyesu@digitaldividedata.com
josiah.muyesu@digitaldividedata.comOffice: +254.772.191.795_
_Mobile: +254.725.790.973 / 735.790.973_

Digital Divide Data: Creating a World Of Digital Possibilities
http://www.digitaldividedata.org

..the greatest results in life are usually attained by simple means and the
exercise of ordinary qualities.These may for the most part be summed in
these two:Common-sense and Perseverance....

**Comment by secretrobotron** [comment]
Let's try for Thursdays. I can send around a calendar invite. What time do people prefer?

Here's a minutes document we can use: https://docs.google.com/document/d/1xI437hHk8TPrxNfATXll5ypSf83MCyBTbj97oMI4x6k

**Comment by Uwanja** [comment]
I have sent this to the Mozilla Kenya Telegram group and the DSO bootcamp WhatsApp group just in case people miss the notifications on email.

My Skype name is mana.nas

**Comment by secretrobotron** [comment]
Thanks @Uwanja :D.
