### ISSUE TITLE
Consent form - add something about the workshops 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#68]

**Comment by JoashMango** [comment]
will have a conversation with participants who will attend the workshop

**Comment by chanditome** [comment]
@JoashMango I am making the assumption that DDD already has preconceived needs especially with the data to be collected. Does this therefore mean that we should approach the participants with a draft consent form then ask for their input on the issues they are going to sign up for?

**Comment by lauradereynal** [comment]
I believe we can close this ticket for now. Last time we talked about this, @JoashMango and @DuncanGW were going to have conversations about the workshops with participants. Feel free to re-open if needed.
