### ISSUE TITLE
Design intervention documentation template for the researchers and volunteers 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#69]
Goal: For each intervention–– especially digital skills trainings–– the open researchers will need to observe attentively and document participants reactions and comments. 
We will use a documentation template so that each group follows the same structure.

To do: 
- [ ] Create first draft of the template for intervention 1
- [ ] Review and validate

**Comment by chanditome** [comment]
How do we go about this @LauraReynal & @secretrobotron? Are we collaborating on it on Google Docs then share it here or are you two going to work on it then share it with us?

**Comment by lauradereynal** [comment]
Updated the description of the task here. 

I propose that we collaborate on this google doc: https://docs.google.com/document/d/1Camp1cJZ0zEcx1cjFXcaFYPg3qzZ_f5LiKNyn3h1R8g/edit 

Who wants to give it a first try ? This is a good first task for anyone interested in analysis and research work.

**Comment by lauradereynal** [comment]
@Amuti Would you like to help on this task ? I think your research expertise would be very valuable here.

**Comment by chanditome** [comment]
@WinnieMakokha has some experience as well. Could you please contribute as well?

**Comment by WinnieMakokha** [comment]
@LauradeReynal just had a look at the template and am a bit at sea. Maybe a
little more light..

Are we giving suggestions based on what we imagine to be things that we
will report about the intervention?

 Regards,

Winnie Makokha

_Adopt the pace of nature, her secret is patience_

**Comment by Amuti** [comment]
@LauraReynal noted. Will forward a draft by the end of the week

**Comment by lauradereynal** [comment]
Thanks @Amuti and @WinnieMakokha . 

This ticket is a duplicate from #99 so I'll close it to avoid confusion.
