### ISSUE TITLE
Design formal communication plan

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#7]
- Who are the stakeholders?
- What does each need to know?
- What's the right format for each stakeholder?
- What's the schedule for each?
- Do the participants in the study need their own form of communication?

**Comment by secretrobotron** [comment]
Stakeholders
- Gates:
- MoFo Level 1: 
- MoFo Level 2:
- DFS ecosystem:
- Community members:

**Comment by lauradereynal** [comment]
@metaphorista @KalpanaSimhan @kevzawacki 
What are the news from Gates regarding press release ? 

Are we allowed to start writing blog posts and sharing slide decks and recruiting volunteers publicly ? (eg can we share somehting on twitter now or do we need to wait ?)

**Comment by lauradereynal** [comment]
@secretrobotron are we going to use github to have a blog for this project, or did you want to use something different ?

**Comment by secretrobotron** [comment]
I'd like to still use the still-unformed research blog if we can. If that's not up before we have a planning sprint for the bootcamp, I'll just set something up on this repo. But, that's firmly a backup sort of plan.

**Comment by lauradereynal** [comment]
Moving this to milestone end of January

**Comment by lauradereynal** [comment]
@secretrobotron here is a folder where we can keep all our communication materials? 
https://drive.google.com/open?id=0B0X05aIHuAbeYnJyUjZFVDJza1E

**Comment by secretrobotron** [comment]
@LauraReynal that's a really cool folder. :+1:

**Comment by KalpanaSimhan** [comment]
@secretrobotron @LauraReynal  - I added the Gates comms guidelines into the Google Drive folder.

**Comment by secretrobotron** [comment]
From convo w/ Ben:

#### Level 1: ambient data flow (GitHub)
- Audience: anyone who really cares about in-depth research

#### Level 2: regular blog — weekly update, narrating what's going
- Audience: anyone who really cares but doesn't have time to parse Level 1

#### Level 3: publications, small case studies (research queue)
- Audience: people who are casually engaged project, who we want to share

#### Level 4: announcement, Mozilla blog
- Audience: the WORLD

**Comment by secretrobotron** [comment]
> I added the Gates comms guidelines into the Google Drive folder.

Thanks @KalpanaSimhan :+1: .

**Comment by lauradereynal** [comment]
I'm happy to take a crack at this with you when you want @secretrobotron 
Do we need to publish that somewhere or is it just internal ? 
Maybe it should go in a text file of the repo?

**Comment by lauradereynal** [comment]
Maybe @KalpanaSimhan can help here. Do you think we need this to be documented externally ?

**Comment by secretrobotron** [comment]
+1 to adding to the repo in some fashion when we're done. That would just be nice for openness' sake. Starting some work here though for quick collab: https://docs.google.com/document/d/1ssNRFXyD5v4aC2L7HKsVCjSl-elLEUwrvi0Hc_4aMgk

**Comment by lauradereynal** [comment]
Thanks @secretrobotron it's awesome! I moved this doc into our folder.

Closing this ticket, now that we have a nice plan.
