### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by shey02** [MozillaFoundation/digital-skills-observatory#70]
Hello everyone,its shey the Adventure freak ;) 

My favorite word is 'inspiration'.

I would love to to help in community engagement,project management,event organizing,field work research and maybe also curriculum development.

Great minds
Amazing team
Cool people @denomain @WinnieMakokha @chanditome @secretrobotron  @ChristabelAchieng @Obadha @Ednahkiome @alexanderamolo @LauraReynal  @DuncanGW and all the others.Was great meeting you'all

**Comment by shey02** [comment]
issue 70#

**Comment by secretrobotron** [comment]
Thanks, @shey02 ! Just try putting that `#` on the other side of the number. Then it will link properly.

**Comment by lauradereynal** [comment]
Thanks for posting your first issue @shey02 :smile: :high_brightness: 
Hope you find github easy to use now !

I'm closing these tickets for now, so that our repo is a bit easier to navigate.
