### ISSUE TITLE
Fauzia :)

### ISSUE THREAD

**Issue by FauziaIsmail** [MozillaFoundation/digital-skills-observatory#71]
Hi everyone. It's Fauzia. 

My favorite word is innovate.

I would love to help in community management, communication/blog and event organizing. 

:)

**Comment by FauziaIsmail** [comment]
Issue #71

**Comment by chanditome** [comment]
We have the same interests @FauziaIsmail.
So as @secretrobotron advises, you need to go back to  #46, then comment with reference to this particular issue. :-)

**Comment by FauziaIsmail** [comment]
Thank you @chanditome

Done :)

**Comment by chanditome** [comment]
Great! @FauziaIsmail  :-)

**Comment by secretrobotron** [comment]
Thanks friends :+1:!
