### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by AI-DennisNdegwa** [MozillaFoundation/digital-skills-observatory#73]
Hi everyone, My name is Dennis Ndegwa from Nairobi. A Mozillian and lover of anything open source. My favorite word is "sumimasen" which means "excuse me" in Japanese.

I would like to be an open researcher, blogger, and community manager during the one year period during which this project will run. Also, looking forward to working with and learning from the very interesting and knowledgeable people that I met on 15th, 16th, 17th Jan 2016. @JoashMango @Shey02 @chanditome @DuncanGW @dobbz @secretrobotron etc. :+1:

**Comment by secretrobotron** [comment]
Thanks @denomain ! Now, try this:

Write a comment in [my issue](https://github.com/MozillaFoundation/digital-skills-observatory/issues/46) including the number of this one. e.g. this issue is #73, so I would write something like `Hooray! I made an issue! It's #73!.`

**Comment by AI-DennisNdegwa** [comment]
@secretrobotron done and done.

**Comment by secretrobotron** [comment]
Rad, @denomain. Thanks :dancer:.
