### ISSUE TITLE
Myself

### ISSUE THREAD

**Issue by festolangat** [MozillaFoundation/digital-skills-observatory#74]
I am Langat Festus Mozillian Mombasa and FSA Jkuat Taita Taveta, My favourite Phrase is in Matthew 5:14 "You are the light of the world....". I will love to participate in this project as Community Management as well as events organizer . I do recognise @secretrobotron, @zuma1, @LauraReynal, @FauziaIsmail,@Obadha,@Shey02,@uwanja,@chanditome,@WinnieMakokha,
@Ednahkiome,@denomain,@josiahmuyesu,@xelawafs,@Arwa40,@ChristabelAchieng,@dobbz,@nekesawekesa,@nmarita,@marywashe,@alexanderamolo,@nao07,@DuncanGW,@JoashMango as my best project mentors. You all are awesome to me!.

**Comment by chanditome** [comment]
Honored to be on your list. I am learning a lot from you as well.

**Comment by alexanderamolo** [comment]
Thanks langat

**Comment by zuma1** [comment]
Thanks tip tip aka lang'at

**Comment by Uwanja** [comment]
Thanks Festus.

**Comment by alexanderamolo** [comment]
How are you guys
