### ISSUE TITLE
Allo! Allo!

### ISSUE THREAD

**Issue by Amuti** [MozillaFoundation/digital-skills-observatory#75]
My name is Marie Amuti. A budding UX Designer who would love to do more user research. I love to meet people and understand how they live
On the other hand I am a secret introvert (I know right!) who loves potato couching and watching reruns of sci-fi movies
Looking forward to going out to the field and doing lots of prototyping!

**Comment by chanditome** [comment]
@Amuti, welcome to git!

**Comment by Arwa40** [comment]
Welcome to Kisumu and enjoy field work

**Comment by secretrobotron** [comment]
Thanks @Amuti! Now, try this:

Write a comment in [my issue](https://github.com/MozillaFoundation/digital-skills-observatory/issues/46) including the number of this one. e.g. this issue is #75, so I would write something like `Hooray! I made an issue! It's #75!.`

**Comment by secretrobotron** [comment]
Thanks @Amuti :smile_cat: !
