### ISSUE TITLE
Hi Bobby and Laura, how's the going concerning the community call? 

### ISSUE THREAD

**Issue by marywashe** [MozillaFoundation/digital-skills-observatory#76]

**Comment by xelawafs** [comment]
Hey @marywashe the call happened yesterday (4th February) 8 pm EAT. You can find the agenda here: https://docs.google.com/document/d/1xI437hHk8TPrxNfATXll5ypSf83MCyBTbj97oMI4x6k/edit#

Make sure to send @secretrobotron your Skype ID to join the next one

**Comment by marywashe** [comment]
Ok, thanks for the link #xelawafs

**Comment by chanditome** [comment]
Let me bestow the honor of closing this issue upon myself :-)
