### ISSUE TITLE
Design (steal) Github training for January meetup

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#8]
For DDD, Researchers, Mozillians, staff, etc.
- Issues and Milestones
- Wiki
- Adding "code"
- Labels
- Users (+cc'ing)

I'm sure there are github training ideas/agendas to steal out on the web.

**Comment by lauradereynal** [comment]
@secretrobotron There is a group that met in Orlando and worked on this. I think Zannah is the right person to reach out to.

**Comment by secretrobotron** [comment]
Thanks @LauraReynal. Reached out.

**Comment by secretrobotron** [comment]
@cassiemc @edrushka do you have a good source of documentation we can use here?

**Comment by edrushka** [comment]
Sorry, I have no documentation :( I've never found anything online for using GH as a project management tool.

**Comment by secretrobotron** [comment]
Winging it a bit: https://github.com/MozillaFoundation/digital-skills-observatory/issues/46
