### ISSUE TITLE
Discuss data storage, and make a plan for dashboards

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/digital-skills-observatory#81]
1. DDD IT team to share some information about the data we are going to store
2. Adam to suggest some options for how we can analyse or display this data
3. Together agree a plan
4. Do the work :smile:

**Comment by adamlofting** [comment]
cc @dobbz

**Comment by lauradereynal** [comment]
linked with #40 from @secretrobotron

**Comment by secretrobotron** [comment]
Tried to sketch out the data flow in https://github.com/MozillaFoundation/digital-skills-observatory/issues/40#issuecomment-185441338. Writing some ideas about useful dashboards based on it:

### For Internal Organization/Logistics
- Number of interviews conducted per area, per interview period
- Number of people attending interventions and responding to interview/survey requests
- Community member activity
- (@DuncanGW, what else do you think would be useful here?)

### For Public Interest
- Phone/app/data statistics
- DFS service usage statistics
- Hypotheses drafted/untested/testing/accepted/rejected
- Other trends in Phone/Literacy/DFS usage that come up from the data

**Comment by lauradereynal** [comment]
Can we post this information into a google doc somwhere? 
What is the status?

**Comment by secretrobotron** [comment]
Working on a new set of questions to track in some dashboards: https://docs.google.com/document/d/1vpfwZk0D25nwQMWcwrfQxuM8TQUFOJZ03OGmqLJGMSc/edit

@DuncanGW @dobbz @allankimata

**Comment by secretrobotron** [comment]
@DuncanGW is hard at work on these dashboards.

**Comment by DuncanGW** [comment]
@secretrobotron Pole sana! (Translation: very sorry about that)  CC: @allankimata , were you able to try what I had shared on email, for entry point.

**Comment by secretrobotron** [comment]
I've got access to the DB now, and can think about ways to use & visualize.

**Comment by secretrobotron** [comment]
Using silk with Caspar and Jurian.
