### ISSUE TITLE
DDD shares the details of data collection 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#82]
Goal: Finalize the application for data collection - by friday 19th

@JoashMango @DuncanGW @dobbz @adamlofting @secretrobotron

**Comment by adamlofting** [comment]
Step 1. What data are we confident we can collect with the app today? (DDD to share)
Step 2. Is there anything we're missing that is so important we should add these as manual questions to the interview (limit this to a sensible number)?

**Comment by lauradereynal** [comment]
@dobbz if you can share the list, that would be awesome, and we can have a look asap.

**Comment by dobbz** [comment]
[Here](https://docs.google.com/spreadsheets/d/1GePvKidWnvll_jj3RLFWLzouUmmsDbDerA3JjLHcMaw/edit#gid=2121995020) is a shared document with app features.

[Here](https://onedrive.live.com/redir?resid=A72FEBC4FFECB843!3926&authkey=!AJ_QDm1aC2iZEog&ithint=file%2cxlsx) is some sample data

**Comment by secretrobotron** [comment]
Thanks @dobbz . Can you open up the access to the doc? Can't see it yet.

**Comment by secretrobotron** [comment]
Also, this is some nice data so far! Love the detail.

What were the test phones that gave us this data? Just inside DDD's IT lab? Looks like all the phones are running Android 4.3+.

**Comment by adamlofting** [comment]
I've just requested access to the app features list.

@dobbz thanks for sharing the sample data. I know this is just the sample data (so it's fine), but I wanted to make sure that when this is ready, we never share the real user data publicly like this. :+1:

**Comment by dobbz** [comment]
@DuncanGW please grant access to the shared doc.

@secretrobotron They were all DDD. That was an excerpt. we have data from
different versions of android from 2.3.3 to 5.0

@adamlofting Raw data or access to it will never be shared publicly.

On 18 February 2016 at 13:40, Adam Lofting notifications@github.com wrote:

> I've just requested access to the app features list.
> 
> @dobbz https://github.com/dobbz thanks for sharing the sample data. I
> know this is just the sample data (so it's fine), but I wanted to make sure
> that when this is ready, we never share the real user data publicly like
> this. [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/digital-skills-observatory/issues/82#issuecomment-185647258
> .

## 

Mr. Dobbz Mkolwe
​​
Database & Systems Administrator, DDD - Kenya
Paramount Plaza 7th Floor
P.O Box 4282 - 00506,  Nairobi, Kenya

Office: (+254) 771 19 1795  |  Cell (+254) 713 10 3222

http://www.digitaldividedata.com/*Creating a World of Digital
Possibilities http://www.digitaldividedata.com/ *

**Comment by lauradereynal** [comment]
Requested access to both documents

**Comment by lauradereynal** [comment]
Details have been shared. Closing.
