### ISSUE TITLE
Work out logistics for first intervention

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#87]
Let's work out the logistics for the first intervention, starting with people who can commit to lead the planning and coordination for each. Either add your name below, or add a new comment here with the location in which you'll be able to help out.
## Dates
- End of April (exact dates TBD)
### Nairobi
- Dennis Ndegwa - @denomain
- Alex Wafula - @xelawafs 
- Marie Amuti - @amuti
- _[add your name & github username here]_
### Mombasa
- Shehnaz - @shey02
- Fauzia Ismail - @FauziaIsmail 
### Kisumu
- Chandi Tome - @chanditome
- Christabel  - @ChristabelAchieng 
### Vihiga
- Chandi Tome - @chanditome (I think I can handle Vihiga town as well if no one else volunteers).
- Walter Loso - @Obadha (assuming they won't be running concurrently in each town I should be able to help out in Vihiga too)
### Kilifi
- Walter Loso - @Obadha
- Faith Zuma - @zuma1

---
### Nairobi
- ???
### Mombasa
- ???
### Kisumu

I vote Lake Hub Kisumu @DuncanGW
### Vihiga
- I am going to look for a public school hall that could host us. Feedback in 2 days. 
### Kilifi
- ???

**Comment by lauradereynal** [comment]
:cat: :cactus: :cake: Awesome. Thanks @secretrobotron

**Comment by lauradereynal** [comment]
Thanks for signing up @denomain I'm happy to see you lead the Nairobi workshop :smile:

**Comment by lauradereynal** [comment]
@Amuti will you also be helping for Nairobi? That would be really awesome !

**Comment by secretrobotron** [comment]
Thanks for volunteering, @Obadha :+1: .

**Comment by ChristabelAchieng** [comment]
I'll be able to help out in Kisumu.
Christabel.

**Comment by lauradereynal** [comment]
Awesome @ChristabelAchieng I added you to the list

**Comment by shey02** [comment]
Hey everyone,my apologies @LauraReynal and @secretrobotron i have been out of touch for quite sometime but i am back now ready to get down to work,i would like to help out with Mombasa :)

**Comment by zuma1** [comment]
hello everyone. i will help with the Kilifi part

**Comment by secretrobotron** [comment]
Thanks @zuma1 and @shey02!

**Comment by secretrobotron** [comment]
I've added a section [above](https://github.com/MozillaFoundation/digital-skills-observatory/issues/87#issue-134644816) to figure out where exactly these interventions will happen. If you have any preferences/ideas/guidance, please jot that down :smile:. @DuncanGW @JoashMango, any specifics we should be aware of?

**Comment by Amuti** [comment]
Hey @LauraReynal am in! Any other issue you would like me to assist on? You can reference it here :+1:

**Comment by JoashMango** [comment]
For kisumu and Vihiga we can combine the intervention workshop. Mombasa, Kilifi and Nairobi will be site specific.

**Comment by chanditome** [comment]
We should be able to do this at a quite public park, or a university right? Or do we need a more enclosed environment and what would be the implications for both?
@LakeHub provides a collaborative space for entrepreneurs, programmers and designers in Kisumu. The space can be hired out for the Kisumu events at a small fee if you could take that option.

**Comment by AI-DennisNdegwa** [comment]
@LauraReynal looking forward to the workshop and doing some hands on stuff.  :-) :-)

**Comment by FauziaIsmail** [comment]
Hi everyone. Hoping you are all going good.
I'd like to help out in Mombasa.

**Comment by simeonoriko** [comment]
Happy to help out in Nairobi, Kisumu and Vihiga.

+1 to @chanditome's idea to use LakeHub - mostly because there's a pre-existing community you can tap into there.

**Comment by DuncanGW** [comment]
@LauraReynal @secretrobotron . Keeping in Mind some respondents are busy or from remote areas, then logistic wise we should be moving closer to them than pulling them to a central place. A suggestion, Can we have the intervention pilot Kisumu? If so should we plan on recruiting smartphone user with various issues/challenges to an intervention pilot before the actual?

**Comment by lauradereynal** [comment]
That's awesome ! So happy to see some great activity here :smile_cat: 

@chanditome thanks for the Lakehub proposition. What is the cost for a half day booking ? 
I'll have a look at the budget if you want to send me information by email ? 

Regarding the dates, I think we can find solutions that will fit most of our requirements. 
Let's cover this in the call tomorrow. @secretrobotron and are planning to spend 3days in each location to help out. So we should coordinate.

**Comment by lauradereynal** [comment]
@DuncanGW 
I agree that we should move closer to participants rather than pulling them to a central place. 

Regarding intervention pilot, I think it would be great, but I am worried that we don't have enough time to do it. Let's talk about it during the call today.

**Comment by sylvan-d-ash** [comment]
Happy to help out in Nairobi. Without solid dates, I can't guarantee myself for Kilifi...though I'd have loved to go there ;)

**Comment by shey02** [comment]
Hey everyone, @LauraReynal @secretrobotron so when exactly are we starting out to help with the planning and coordination for the respective towns and what exactly is to be done??

**Comment by secretrobotron** [comment]
We're just sketching all of that out right meow :smile_cat:, @shey02.
- @LauraReynal and I are going to be working with people in each location to pick dates that work best.
- If you have any suggestions for dates/venues, please leave them here and we can talk about them.
- We will have a "What exactly do we need to do now?" thing ASAP.

**Comment by shey02** [comment]
Thats cool😺_meow_😺as for the date,i just wish it's not scheduled during the first two weeks of April as most universities will be having exams,otherwise am cool with any other date but ofcourse looking forward to suggestions from many more of us

**Comment by AI-DennisNdegwa** [comment]
In my way of thinking. I think this would work best by identifying the target groups first and fast. Are they scattered over a wide area in every location or are they more or less within the same vicinity? After that, we can come up with an effective schedule of how to move to them and who can access them with minimal effort. Do we have to do one location at a time as a team to do it in the most efficient way? Or can we have nearest people to a location visiting the participants as of when required without necessarily having to make people from far locations travel all the way to help out?

**Comment by chanditome** [comment]
@LauraReynal sorry I missed your question. Sending you an email right away.

**Comment by lauradereynal** [comment]
Thanks for all this work team :smile: we can now close this ticket since all the interventions are done :dancer:
