### ISSUE TITLE
Gather exisitng curriculum about smartphones and DFS 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#88]
Hey everyone, do you know any existing curriculum that teaches people about:
- Smartphones 
- Mobile internet 
- Basic Digital skills 
- Digital Financial Services 
  ...and anything else that might be relevant for this project? 

Can you please add resources in this folder? https://drive.google.com/open?id=0B0X05aIHuAbeWEo2dldaYTFsNkU 
1. Look for curriculum you have or know about
2. Put it in the folder
3. Paste a comment on this issue and share the link in this ticket

**Comment by zuma1** [comment]
#53 Hello everyone, Laura I was asking about the curriculum, does it need to be a PDF or websites or links ?

**Comment by lauradereynal** [comment]
@zuma1 it does not need to be a specific format. Do you know any existing curriculum that would be relevant in this case?

**Comment by zuma1** [comment]
#53 YES  I did, here is the link 
http://www.eib.org/attachments/country/study_digital_financial_services_in_africa_en.pdf
it explains different DFS around Africa including Kenya tob and how it used by people.

**Comment by zuma1** [comment]
#53 Here are two more.
http://www.eib.org/attachments/country/study_digital_financial_services_in_africa_en.pdf
https://www2.deloitte.com/content/dam/Deloitte/sg/Documents/financial-services/sea-fsi-digital-financial-services-in-Indonesia-noexp.pdf

**Comment by lauradereynal** [comment]
OH awesome :cherries: Thanks for sharing documents. 

@zuma1 you don't need to reference your issue #53 when you post new ticket. You can just type. 

these links are awesome reports and resources, but we are looking more for teaching resources. Have you ever done a teaching event ? A curriculum would be the way to prepare your teaching event. 
Example, like https://teach.mozilla.org/activities 

Does it make more sense ?

**Comment by zuma1** [comment]
OK Laura its clear now  let me check for some. thanks for the clarification.

**Comment by lauradereynal** [comment]
Added the GSMA curriculum in the folder. Have a look @zuma1 it's a good benchmark.https://drive.google.com/open?id=0B0X05aIHuAbecXpGaDJVZi1xRjg

**Comment by secretrobotron** [comment]
Thanks for contributing, everyone :).
