### ISSUE TITLE
Run a pilot for intervention 1 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#89]
Goal: Test our intervention methods and documentation questions.

**Comment by chanditome** [comment]
Month 2 is coming to a close. When is the proposed date for this?

**Comment by lauradereynal** [comment]
good catch @chanditome Thanks ! I changed the milestone to Month 3.
Since the first intervention is in April, we could do a pilot before the end of March. 

It would require to find some new participants, and run a couple of workshops to test the content and the reporting process. Thoughts?

**Comment by chanditome** [comment]
Sounds good. In which areas (expertise) would these participants be needed? Let me know how many you would need from Kisumu, I will help recruit.

**Comment by lauradereynal** [comment]
Sounds great. Let's talk about it in the next community call? 
I filled this ticket but have not yet spent time on this idea.

**Comment by chanditome** [comment]
@LauraReynal sure!

**Comment by Obadha** [comment]
hi @LauraReynal . A pilot was not talked about in the last skype call. If this is still the plan, together with @chanditome and @ChristabelAchieng could we get this in motion while we still have good time?

**Comment by chanditome** [comment]
@Obadha yes Walter. Let me get in touch with @ChristabelAchieng right away regarding this.

**Comment by lauradereynal** [comment]
I think it would be very benefitial to run a pilot. 
If you are keen to help, then let's do it. :dancer:

A few questions: 
- Do you think you might be able to find ~5 people to participate as learners? ideally they would be first time smartphone users. 
- Would you like to set up a date together ? I was thinking some time in the last week of March. That would give us enough time to prepare, and enough time to learn from this pilot.

**Comment by chanditome** [comment]
First mini test coming up Monday 21st. Will report here. 
Can we post the public link to the curriculum here?

**Comment by lauradereynal** [comment]
@chanditome the curriculum is here https://docs.google.com/document/d/17QuzlrAsz8dIN6PGzWoxK5NUedTnmAiO7PopnA7RrBQ/edit?ts=56d8587d#

**Comment by lauradereynal** [comment]
Cant wait to see what you report here. I'm preparing a document to help do that. Also, we should debrief via skype call. 

What about you @denomain do you have a date estimate for your pilot?

**Comment by lauradereynal** [comment]
@chanditome @denomain How are you guys doing with the pilot ?

**Comment by chanditome** [comment]
@LauraReynal mine went pretty smooth. Both participants complained about the length of the exercise and the rather "technical nature of the language".

All in all I can say that the curriculum is ready to go.

**Comment by lauradereynal** [comment]
@chanditome thank you very much for this first debrief. Let's chat again soon.

**Comment by chanditome** [comment]
I completed my 3rd and 4th pilot this evening. These ones went pretty well since I learned from the previous two experiences last week and made a few changes to the approach. Happy to share when the time comes, I will fill up the docs shortly.

**Comment by lauradereynal** [comment]
Awesome @chanditome 
Can you share tomorrow with the group ?

**Comment by lauradereynal** [comment]
Can you fill out this documentation questionnaire to see if this method is appropriate to document interventions ?
https://docs.google.com/a/mozillafoundation.org/forms/d/1uW0fJZXTh1Os7fx5za2srgNDmuDNu8qHjW6X6KwUOFQ/edit?usp=sharing_eid&ts=56fb3eb1

**Comment by chanditome** [comment]
@LauraReynal, I think I already filled this up. Yes, I will share my experience with the team tomorrow.

**Comment by AI-DennisNdegwa** [comment]
@LauraReynal Preparing to do a pilot today. Will get back to you after.

**Comment by lauradereynal** [comment]
Thanks for all the work on intervention 1 ! it's done :smile: 
Now on to intervention 2 !
