### ISSUE TITLE
Write a read me intro for this repo

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#9]
Task: Write a short intro about this project and this repo, so that it feels more welcoming and less empty

@secretrobotron are you up for it ?

**Comment by secretrobotron** [comment]
:+1:
suggest we have a deck and pull the relevant bits into here

**Comment by secretrobotron** [comment]
Relies on #3

**Comment by lauradereynal** [comment]
Hey @secretrobotron i tried to make a short intro. 
I would like to add these images but I dont know how to insert it in the readme

![digital skills observatory - research overview - new page](https://cloud.githubusercontent.com/assets/8261945/11897924/02c16268-a594-11e5-8598-9c397767848c.png)
![dso venn diagram - plain](https://cloud.githubusercontent.com/assets/8261945/11897925/02dd8650-a594-11e5-9f26-080b546edbcf.png)
[timeline.pdf](https://github.com/MozillaFoundation/digital-skills-observatory/files/66623/timeline.pdf)

**Comment by secretrobotron** [comment]
Done! Also added a bit more of a description. Check it out when you get a chance, @LauraReynal.

**Comment by lauradereynal** [comment]
thank you it's perfect :+1: :cactus:
