### ISSUE TITLE
Prepare and reach out to informal advisors 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#90]
Goal: gather expert's input on the project design and content.

todo:
- [x] reach out to people
- [x] prepare questions and things to review 

cc @secretrobotron and @benrito

**Comment by secretrobotron** [comment]
Just to clear this up: this is for hypotheses (to begin with), correct?

**Comment by lauradereynal** [comment]
yes, and general inputs about the interventions.

**Comment by lauradereynal** [comment]
I drafted some questions we could talk about here 
https://docs.google.com/document/d/1Da3BLSPhILhJQCjPllvh33BGVmspi6Tr4gTdu4hjb3Y/edit#
feel free to jump in.

**Comment by lauradereynal** [comment]
Should we get this reviewed by Dave (since he is going to reach out to his network as well)?

**Comment by lauradereynal** [comment]
A first round of meetings has been done. Let's plan to do this again in May and add new people. We need to make more progress in the meanwhile, and run our first intervention.
