### ISSUE TITLE
DSO Website meta 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#92]
@secretrobotron 

The number of information online and google docs is already starting to pile up. Can we have a more friendly way to publish the files in this github repository ? 

I am imagining a very very simple website / github pages where we can make content easy to navigate. This was a feedback from community members as well.

**Comment by lauradereynal** [comment]
What do you think ?

Something like this 

http://mozilla.github.io/mobile-opportunity/ 

With the following 
- The project 
- Research questions 
- Research methods 
- Timeline 
- Curriculum 
  ....
  etc

**Comment by secretrobotron** [comment]
@LauraReynal definitely. We can add a super-simple `index.html` to the repo that links out to important docs. Or we can use the wiki (pretty easy to edit).

**Comment by secretrobotron** [comment]
@LauraReynal actually, I would love to propose something with the assets we have to the design team to make a simple, static webpage with that handful of links. We can start with something on our own and then ask for feedback.

**Comment by lauradereynal** [comment]
@secretrobotron I love the idea of a simple static webpage way more than a wiki 
Can we start on our own and then bring it to crit?

**Comment by chanditome** [comment]
@LauraReynal @secretrobotron a wiki allows for pretty decent headers and sub-headers if you have the time :-)

**Comment by secretrobotron** [comment]
@chanditome any good examples you can point us at?

**Comment by secretrobotron** [comment]
Threw this together this morning: http://secretrobotron.github.io/digital-skills-observatory/

#### Why it's good
- Simple
- Easy to update
- Uses the assets we get from the field

#### Where it can go
- Could make it more exciting in the future when we have results to share
- Could make it more immersive by using audio/video (probably a mini-project unto itself)

#### What we should do
- Add attribution and finalize links
- Publish it
- Bring it to design crit
- ¿Localize it?

**Comment by lauradereynal** [comment]
Thanks @secretrobotron I really love it, and I wonder what the community thinks ! 

Some thoughts: 
- On the copy for the tagline, it should say Research somehow. Maybe something like: 
  "A year-long research project where we follow new smartphone users, as they learn new digital skills and use Digital Financial services." That's probably too long, but I think it should say that it's a research project. 
- Can you add a "contact" section ? with our names and emails and the community mailing list? 

Otherwise I think it's awesome –– let's bring it to crit on wednesday

**Comment by lauradereynal** [comment]
New idea: 

Can you create a space on the landing page for a small text introduction of the project? 
I'm thiking 5-10 lines maximum, that will communicate right away about what this project is.

What do you think?

**Comment by JoashMango** [comment]
Yes i do agree with you. We need a summary about the project

**Comment by lauradereynal** [comment]
@secretrobotron can we work on adding a description and making changes to this page ? 

When is a good deadline for this mini-project? 

We could also ask Matthew for a design resource if you want.

**Comment by lauradereynal** [comment]
we need to add a contact section

**Comment by lauradereynal** [comment]
I wrote a first couple of ideas in this document https://docs.google.com/document/d/1k9-zuWNejeBt-2T7K9umJfoZRbERVh8o_AS4SaIPhZE/edit# 

If it's okay with you @secretrobotron I'll file sub-tickets so we can see more clearly what we can do
