### ISSUE TITLE
Write design brief for Intervention #1

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#93]
We need to write a design brief for the first Intervention, likely a piece of curriculum and corresponding workshop based on digital skills training around smartphones and apps.

cc @LauraReynal @chadsansing

**Comment by lauradereynal** [comment]
Based on our meeting with @chadsansing here is what I understood: 
- [x] Finish to write the brief with the information Chad needs 
- [x] @chadsansing produces first brainstorm in close collaboration with the community

Thoughts ? I probably forgot some steps - feel free to edit

**Comment by chadsansing** [comment]
Let's tighten the scope of what will be produced by the end of the month - i.e. how many modules do we want in-hand by when?

**Comment by lauradereynal** [comment]
OK. I just finished writing this design brief for @chadsansing and the community.

Input appreciated. Especially @chadsansing let me know if this does not have all the information you need? 
https://docs.google.com/document/d/1DetmRvBcSn5tUl6zIXcwUixzrJq4MBXPYCcg5tVbEvE/edit#

**Comment by lauradereynal** [comment]
Thanks everyone - this work is done
