### ISSUE TITLE
Send February update to Gates

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#94]
### Format
- Use [template](https://docs.google.com/document/d/1onoUL09WtyOaGKnywaYKnbKk5l1Sp8rnXgYl3BIqgUk) from last month
#### Topics
- Hypothesis/research question refinement and expert outreach/commentary
- Iteration on Intervention logistics/implementation design
- Community calls and engagement on github (glossary, first bugs)
- Structuring Intervention [logistics](https://github.com/MozillaFoundation/digital-skills-observatory/issues/87) w/ community
- Building a design brief for Intervention 1
- Respondent recruitment
- Data collection specification and app implementation
- Blog (mzl.la/dso)
- Communications plan
#### Reference
- Closed bugs on [github](https://github.com/MozillaFoundation/digital-skills-observatory/issues?q=milestone%3A%22Month+2%22+is%3Aclosed)

**Comment by lauradereynal** [comment]
First draft of the update is written in the document
Please copy and content edit without holding back :smile: 

@KalpanaSimhan @secretrobotron @metaphorista @DuncanGW @JoashMango @dobbz 
@adamlofting 
I also flagged specific areas for some of you.

**Comment by lauradereynal** [comment]
@KalpanaSimhan @metaphorista we are done editing the monthly reporting. 
Feel free to review one last time and to edit and ship when you want. 

@davidascher @benrito if you want to have a look, here is our february update for Gates: 
https://docs.google.com/document/d/1onoUL09WtyOaGKnywaYKnbKk5l1Sp8rnXgYl3BIqgUk/edit#heading=h.h4d42slybxkm

**Comment by lauradereynal** [comment]
Thanks for shipping @metaphorista and thanks for the great team effort everyone.
