### ISSUE TITLE
[blog] Summarize and comment on survey results from first bootcamp

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#95]
Write a blog about survey results from the participants of bootcamp 1 so that we can work on making bootcamp 2 better.

**Comment by lauradereynal** [comment]
I suggest to close this. We have learned everything we needed from the first bootcamp and have a debrief with staff and a good chunk of feedback from the volunteers. Also, we arent sure to even host a second bootcamp.

Do you mind if we close this topic?
