### ISSUE TITLE
Summarize first 3 months in cool slide deck

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#96]
Let's build a deck to summarize everything that's been happening and what's next. Socialize on relevant channels and with friends :smile: .

**Comment by lauradereynal** [comment]
Yes. Related, we should update our existing documentation

**Comment by secretrobotron** [comment]
@LauraReynal part of position paper. Is there another bug for that?

**Comment by lauradereynal** [comment]
We can close this one, because 
1. everything is on the blog 
2. we are going to write a summary blog post 
3. we are committed to a mid-study report 
...
ok ?
