### ISSUE TITLE
Prepare documentation of the first intervention 

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#99]
What kind of documentation should we be prepared to write/shoot/cook/capture in the first intervention? What kind of stories should we be on the lookout for?

Off the top of my head, we might want to consider:
- Audio/video/imagery of people interacting and doing stuff
- Feedback from participants
- Answers to some questions in ad-hoc interviews
- People may have epiphanies, good times, or otherwise (great for story-telling)

**Comment by lauradereynal** [comment]
Related to #69 where the goal is to design a template that everyone can use to document the interventions. I propose to organize a meeting with community members to design this template together.

**Comment by Amuti** [comment]
Noted

**Comment by secretrobotron** [comment]
Oh yes! :+1: Thanks, @LauraReynal.

@FauziaIsmail @shey02 what do you think?

**Comment by secretrobotron** [comment]
Note: need to document the hypotheses too: https://github.com/MozillaFoundation/digital-skills-observatory/issues/100

**Comment by shey02** [comment]
@secretrobotron on my side,i think that will be great👍

**Comment by AI-DennisNdegwa** [comment]
My idea of how this would look like is, Having two sets of questionnaires where the interviewer does all or most of the writing and ticking. One to be used as a template for asking the subject questions. Then the second one to be used by the interviewer to give remarks and commentaries. There could possibly be voice recording with the subject's consent.

**Comment by lauradereynal** [comment]
@denomain that's a good idea to have some pre-determined questions. 
It would be nice to start thinking about them based on the content of the first intervention. 

Some more details: 

**Intervention 1** is a workshop, where you (and others) are going to teach participants some specific skills. 
As a teacher and a researcher, ask yourself the following questions: 
- what should I observe about my participants ? 
- How do I know if they have learned and assimilated the different topics I am teaching? 
- what do we need to document for research purposes? 
- what form that documentation can take ? (text, images, voice recording, questionnaires...)

does that help ? 
We are on the right track, but I think we need to flesh that out a bit more.

**Comment by AI-DennisNdegwa** [comment]
@LauraReynal I think working on the questions.md (https://github.com/MozillaFoundation/digital-skills-observatory/blob/master/questions.md) and any questions document from DDD will give us the best template of predetermined questions to work with. This is where we derive interview friendly questions and things to be measured from each category. From that, we can then try to figure out how we could have control questions incorporated. These will help us figure out what secondary information we are supposed to look out for. It will also enable us to form better judgment on things like the truthfulness/reliability of answers given, whether or not the participants have learned something new. etc. Do we have a doc containing a developing template of possible interview questions and activities somewhere?

**Comment by lauradereynal** [comment]
@secretrobotron I wonder if we should set up a drive folder for each team to updload images and other media.

I have started to work on an analysis template here: https://docs.google.com/document/d/1Camp1cJZ0zEcx1cjFXcaFYPg3qzZ_f5LiKNyn3h1R8g/edit 
cc @chanditome

**Comment by lauradereynal** [comment]
Thanks everyone for the great work on intervention 1. This is done, onwards to intervention 2
